// UNRELEASED until the release that first ships it; from then on field numbers,
// field names and RPC shapes are permanent, under the same rules as flexiq.v1
// (§2.2 of tasks/specs/2026-09-01-flexiq-v1-proto-design.md):
//
//   1. Field numbers are never reused and never renumbered.
//   2. Fields are deprecated in place, and on removal both the number and the
//      name are reserved — the name because JSON clients encode against it.
//   3. New RPCs, messages, fields and enum values are additive and never bump
//      the package version.
//   4. A field's meaning and units are frozen with its number.
//   5. Readers tolerate what they do not know: unknown fields, unknown enum
//      values, unknown oneof arms.
//
// This package is deliberately separate from flexiq.v1. A producer and an
// operator are different audiences and must not share a credential, so each
// package is its own scope. flexiq.admin.v1 may import flexiq.v1; the reverse
// import is forbidden. Design: tasks/specs/2026-09-23-admin-service-design.md.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: flexiq/admin/v1/admin_service.proto

package adminv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminService_ListQueues_FullMethodName          = "/flexiq.admin.v1.AdminService/ListQueues"
	AdminService_PauseQueue_FullMethodName          = "/flexiq.admin.v1.AdminService/PauseQueue"
	AdminService_ResumeQueue_FullMethodName         = "/flexiq.admin.v1.AdminService/ResumeQueue"
	AdminService_GetThroughput_FullMethodName       = "/flexiq.admin.v1.AdminService/GetThroughput"
	AdminService_ListDeadLetters_FullMethodName     = "/flexiq.admin.v1.AdminService/ListDeadLetters"
	AdminService_GetDeadLetter_FullMethodName       = "/flexiq.admin.v1.AdminService/GetDeadLetter"
	AdminService_ReplayDeadLetter_FullMethodName    = "/flexiq.admin.v1.AdminService/ReplayDeadLetter"
	AdminService_DeleteDeadLetter_FullMethodName    = "/flexiq.admin.v1.AdminService/DeleteDeadLetter"
	AdminService_PurgeDeadLetters_FullMethodName    = "/flexiq.admin.v1.AdminService/PurgeDeadLetters"
	AdminService_ListWorkers_FullMethodName         = "/flexiq.admin.v1.AdminService/ListWorkers"
	AdminService_DrainWorker_FullMethodName         = "/flexiq.admin.v1.AdminService/DrainWorker"
	AdminService_ListPeriodicTasks_FullMethodName   = "/flexiq.admin.v1.AdminService/ListPeriodicTasks"
	AdminService_GetPeriodicTask_FullMethodName     = "/flexiq.admin.v1.AdminService/GetPeriodicTask"
	AdminService_PutPeriodicTask_FullMethodName     = "/flexiq.admin.v1.AdminService/PutPeriodicTask"
	AdminService_DeletePeriodicTask_FullMethodName  = "/flexiq.admin.v1.AdminService/DeletePeriodicTask"
	AdminService_PausePeriodicTask_FullMethodName   = "/flexiq.admin.v1.AdminService/PausePeriodicTask"
	AdminService_ResumePeriodicTask_FullMethodName  = "/flexiq.admin.v1.AdminService/ResumePeriodicTask"
	AdminService_TriggerPeriodicTask_FullMethodName = "/flexiq.admin.v1.AdminService/TriggerPeriodicTask"
	AdminService_ListOverrides_FullMethodName       = "/flexiq.admin.v1.AdminService/ListOverrides"
	AdminService_SetTaskOverride_FullMethodName     = "/flexiq.admin.v1.AdminService/SetTaskOverride"
	AdminService_ClearTaskOverride_FullMethodName   = "/flexiq.admin.v1.AdminService/ClearTaskOverride"
	AdminService_SetQueueOverride_FullMethodName    = "/flexiq.admin.v1.AdminService/SetQueueOverride"
	AdminService_ClearQueueOverride_FullMethodName  = "/flexiq.admin.v1.AdminService/ClearQueueOverride"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The operator door: the queue, dead-letter, worker, periodic-task and
// override operations the dashboard performs, as operations — never as a
// storage proxy.
//
// Every RPC acts on the credential's namespace and nothing else. A resource in
// another namespace is indistinguishable from one that does not exist.
//
// Two scopes, chosen by the method's idempotency level rather than listed:
// `inspect` calls the NO_SIDE_EFFECTS methods, `admin` calls the rest. They are
// not a hierarchy; an operator's token carries both.
//
// What it does not offer:
//
//   - A settings door. The settings KV holds credentials and published
//     policy; a generic read or write of it is not an operator operation.
//   - Draining an attached or push executor. `DrainWorker` reaches registered
//     workers — the rows `ListWorkers` shows; an executor behind the
//     scheduler has no row of its own.
//   - Live effect for overrides. A worker reads overrides when it starts, so a
//     change reaches the next worker start and no running worker.
type AdminServiceClient interface {
	// Every queue the namespace has a job, a pause or an override for.
	ListQueues(ctx context.Context, in *ListQueuesRequest, opts ...grpc.CallOption) (*ListQueuesResponse, error)
	// Stop dispatching from a queue. Jobs already running finish.
	PauseQueue(ctx context.Context, in *PauseQueueRequest, opts ...grpc.CallOption) (*PauseQueueResponse, error)
	// Resume dispatching from a paused queue.
	ResumeQueue(ctx context.Context, in *ResumeQueueRequest, opts ...grpc.CallOption) (*ResumeQueueResponse, error)
	// How many jobs finished per queue over a recent window.
	GetThroughput(ctx context.Context, in *GetThroughputRequest, opts ...grpc.CallOption) (*GetThroughputResponse, error)
	// Page through the dead-letter queue, newest first.
	ListDeadLetters(ctx context.Context, in *ListDeadLettersRequest, opts ...grpc.CallOption) (*ListDeadLettersResponse, error)
	// Read one dead-letter entry.
	GetDeadLetter(ctx context.Context, in *GetDeadLetterRequest, opts ...grpc.CallOption) (*GetDeadLetterResponse, error)
	// Enqueue a dead letter again as a fresh job, removing the entry.
	//
	// Not idempotent: each successful call makes a job, and a second call finds
	// no entry.
	ReplayDeadLetter(ctx context.Context, in *ReplayDeadLetterRequest, opts ...grpc.CallOption) (*ReplayDeadLetterResponse, error)
	// Delete one dead-letter entry.
	DeleteDeadLetter(ctx context.Context, in *DeleteDeadLetterRequest, opts ...grpc.CallOption) (*DeleteDeadLetterResponse, error)
	// Delete dead-letter entries in bulk.
	PurgeDeadLetters(ctx context.Context, in *PurgeDeadLettersRequest, opts ...grpc.CallOption) (*PurgeDeadLettersResponse, error)
	// The namespace's registered workers and their heartbeats.
	ListWorkers(ctx context.Context, in *ListWorkersRequest, opts ...grpc.CallOption) (*ListWorkersResponse, error)
	// Ask one worker to drain: it stops claiming work, finishes what it holds,
	// and unregisters — the same graceful stop a SIGTERM gives it.
	//
	// The worker reads the request on its next heartbeat, a few seconds later,
	// so the answer is the request recorded, not the drain done: the worker
	// comes back DRAINING, and leaves ListWorkers once it has stopped.
	DrainWorker(ctx context.Context, in *DrainWorkerRequest, opts ...grpc.CallOption) (*DrainWorkerResponse, error)
	// Every periodic task in the namespace.
	ListPeriodicTasks(ctx context.Context, in *ListPeriodicTasksRequest, opts ...grpc.CallOption) (*ListPeriodicTasksResponse, error)
	// Read one periodic task.
	GetPeriodicTask(ctx context.Context, in *GetPeriodicTaskRequest, opts ...grpc.CallOption) (*GetPeriodicTaskResponse, error)
	// Create a periodic task, or replace an existing one's definition.
	//
	// A replace keeps what an operator set and a definition does not own:
	// whether the task is paused, and when it last ran. Its next run moves only
	// when the cron expression or the timezone changed. A task also declared in
	// a worker's code is declared again when that worker starts.
	PutPeriodicTask(ctx context.Context, in *PutPeriodicTaskRequest, opts ...grpc.CallOption) (*PutPeriodicTaskResponse, error)
	// Delete a periodic task. Jobs it already fired are untouched.
	DeletePeriodicTask(ctx context.Context, in *DeletePeriodicTaskRequest, opts ...grpc.CallOption) (*DeletePeriodicTaskResponse, error)
	// Stop a periodic task firing, keeping its definition.
	PausePeriodicTask(ctx context.Context, in *PausePeriodicTaskRequest, opts ...grpc.CallOption) (*PausePeriodicTaskResponse, error)
	// Let a paused periodic task fire again.
	ResumePeriodicTask(ctx context.Context, in *ResumePeriodicTaskRequest, opts ...grpc.CallOption) (*ResumePeriodicTaskResponse, error)
	// Fire a periodic task now, whether or not it is paused.
	//
	// Enqueues the job the schedule would, and leaves the schedule alone: the
	// next run and the last run are unchanged. Not idempotent — each call is a
	// job.
	TriggerPeriodicTask(ctx context.Context, in *TriggerPeriodicTaskRequest, opts ...grpc.CallOption) (*TriggerPeriodicTaskResponse, error)
	// Every task and queue override in the namespace.
	ListOverrides(ctx context.Context, in *ListOverridesRequest, opts ...grpc.CallOption) (*ListOverridesResponse, error)
	// Replace one task's override. Not a merge: a field left unset is no longer
	// overridden.
	SetTaskOverride(ctx context.Context, in *SetTaskOverrideRequest, opts ...grpc.CallOption) (*SetTaskOverrideResponse, error)
	// Remove one task's override, so its declared values apply again.
	ClearTaskOverride(ctx context.Context, in *ClearTaskOverrideRequest, opts ...grpc.CallOption) (*ClearTaskOverrideResponse, error)
	// Replace one queue's override. Not a merge.
	SetQueueOverride(ctx context.Context, in *SetQueueOverrideRequest, opts ...grpc.CallOption) (*SetQueueOverrideResponse, error)
	// Remove one queue's override.
	ClearQueueOverride(ctx context.Context, in *ClearQueueOverrideRequest, opts ...grpc.CallOption) (*ClearQueueOverrideResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) ListQueues(ctx context.Context, in *ListQueuesRequest, opts ...grpc.CallOption) (*ListQueuesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListQueuesResponse)
	err := c.cc.Invoke(ctx, AdminService_ListQueues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) PauseQueue(ctx context.Context, in *PauseQueueRequest, opts ...grpc.CallOption) (*PauseQueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PauseQueueResponse)
	err := c.cc.Invoke(ctx, AdminService_PauseQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ResumeQueue(ctx context.Context, in *ResumeQueueRequest, opts ...grpc.CallOption) (*ResumeQueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeQueueResponse)
	err := c.cc.Invoke(ctx, AdminService_ResumeQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetThroughput(ctx context.Context, in *GetThroughputRequest, opts ...grpc.CallOption) (*GetThroughputResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetThroughputResponse)
	err := c.cc.Invoke(ctx, AdminService_GetThroughput_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListDeadLetters(ctx context.Context, in *ListDeadLettersRequest, opts ...grpc.CallOption) (*ListDeadLettersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDeadLettersResponse)
	err := c.cc.Invoke(ctx, AdminService_ListDeadLetters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetDeadLetter(ctx context.Context, in *GetDeadLetterRequest, opts ...grpc.CallOption) (*GetDeadLetterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeadLetterResponse)
	err := c.cc.Invoke(ctx, AdminService_GetDeadLetter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ReplayDeadLetter(ctx context.Context, in *ReplayDeadLetterRequest, opts ...grpc.CallOption) (*ReplayDeadLetterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplayDeadLetterResponse)
	err := c.cc.Invoke(ctx, AdminService_ReplayDeadLetter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) DeleteDeadLetter(ctx context.Context, in *DeleteDeadLetterRequest, opts ...grpc.CallOption) (*DeleteDeadLetterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDeadLetterResponse)
	err := c.cc.Invoke(ctx, AdminService_DeleteDeadLetter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) PurgeDeadLetters(ctx context.Context, in *PurgeDeadLettersRequest, opts ...grpc.CallOption) (*PurgeDeadLettersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PurgeDeadLettersResponse)
	err := c.cc.Invoke(ctx, AdminService_PurgeDeadLetters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListWorkers(ctx context.Context, in *ListWorkersRequest, opts ...grpc.CallOption) (*ListWorkersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkersResponse)
	err := c.cc.Invoke(ctx, AdminService_ListWorkers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) DrainWorker(ctx context.Context, in *DrainWorkerRequest, opts ...grpc.CallOption) (*DrainWorkerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DrainWorkerResponse)
	err := c.cc.Invoke(ctx, AdminService_DrainWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListPeriodicTasks(ctx context.Context, in *ListPeriodicTasksRequest, opts ...grpc.CallOption) (*ListPeriodicTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPeriodicTasksResponse)
	err := c.cc.Invoke(ctx, AdminService_ListPeriodicTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetPeriodicTask(ctx context.Context, in *GetPeriodicTaskRequest, opts ...grpc.CallOption) (*GetPeriodicTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPeriodicTaskResponse)
	err := c.cc.Invoke(ctx, AdminService_GetPeriodicTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) PutPeriodicTask(ctx context.Context, in *PutPeriodicTaskRequest, opts ...grpc.CallOption) (*PutPeriodicTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutPeriodicTaskResponse)
	err := c.cc.Invoke(ctx, AdminService_PutPeriodicTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) DeletePeriodicTask(ctx context.Context, in *DeletePeriodicTaskRequest, opts ...grpc.CallOption) (*DeletePeriodicTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePeriodicTaskResponse)
	err := c.cc.Invoke(ctx, AdminService_DeletePeriodicTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) PausePeriodicTask(ctx context.Context, in *PausePeriodicTaskRequest, opts ...grpc.CallOption) (*PausePeriodicTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PausePeriodicTaskResponse)
	err := c.cc.Invoke(ctx, AdminService_PausePeriodicTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ResumePeriodicTask(ctx context.Context, in *ResumePeriodicTaskRequest, opts ...grpc.CallOption) (*ResumePeriodicTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumePeriodicTaskResponse)
	err := c.cc.Invoke(ctx, AdminService_ResumePeriodicTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) TriggerPeriodicTask(ctx context.Context, in *TriggerPeriodicTaskRequest, opts ...grpc.CallOption) (*TriggerPeriodicTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerPeriodicTaskResponse)
	err := c.cc.Invoke(ctx, AdminService_TriggerPeriodicTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListOverrides(ctx context.Context, in *ListOverridesRequest, opts ...grpc.CallOption) (*ListOverridesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOverridesResponse)
	err := c.cc.Invoke(ctx, AdminService_ListOverrides_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) SetTaskOverride(ctx context.Context, in *SetTaskOverrideRequest, opts ...grpc.CallOption) (*SetTaskOverrideResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetTaskOverrideResponse)
	err := c.cc.Invoke(ctx, AdminService_SetTaskOverride_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ClearTaskOverride(ctx context.Context, in *ClearTaskOverrideRequest, opts ...grpc.CallOption) (*ClearTaskOverrideResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearTaskOverrideResponse)
	err := c.cc.Invoke(ctx, AdminService_ClearTaskOverride_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) SetQueueOverride(ctx context.Context, in *SetQueueOverrideRequest, opts ...grpc.CallOption) (*SetQueueOverrideResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetQueueOverrideResponse)
	err := c.cc.Invoke(ctx, AdminService_SetQueueOverride_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ClearQueueOverride(ctx context.Context, in *ClearQueueOverrideRequest, opts ...grpc.CallOption) (*ClearQueueOverrideResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearQueueOverrideResponse)
	err := c.cc.Invoke(ctx, AdminService_ClearQueueOverride_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
//
// The operator door: the queue, dead-letter, worker, periodic-task and
// override operations the dashboard performs, as operations — never as a
// storage proxy.
//
// Every RPC acts on the credential's namespace and nothing else. A resource in
// another namespace is indistinguishable from one that does not exist.
//
// Two scopes, chosen by the method's idempotency level rather than listed:
// `inspect` calls the NO_SIDE_EFFECTS methods, `admin` calls the rest. They are
// not a hierarchy; an operator's token carries both.
//
// What it does not offer:
//
//   - A settings door. The settings KV holds credentials and published
//     policy; a generic read or write of it is not an operator operation.
//   - Draining an attached or push executor. `DrainWorker` reaches registered
//     workers — the rows `ListWorkers` shows; an executor behind the
//     scheduler has no row of its own.
//   - Live effect for overrides. A worker reads overrides when it starts, so a
//     change reaches the next worker start and no running worker.
type AdminServiceServer interface {
	// Every queue the namespace has a job, a pause or an override for.
	ListQueues(context.Context, *ListQueuesRequest) (*ListQueuesResponse, error)
	// Stop dispatching from a queue. Jobs already running finish.
	PauseQueue(context.Context, *PauseQueueRequest) (*PauseQueueResponse, error)
	// Resume dispatching from a paused queue.
	ResumeQueue(context.Context, *ResumeQueueRequest) (*ResumeQueueResponse, error)
	// How many jobs finished per queue over a recent window.
	GetThroughput(context.Context, *GetThroughputRequest) (*GetThroughputResponse, error)
	// Page through the dead-letter queue, newest first.
	ListDeadLetters(context.Context, *ListDeadLettersRequest) (*ListDeadLettersResponse, error)
	// Read one dead-letter entry.
	GetDeadLetter(context.Context, *GetDeadLetterRequest) (*GetDeadLetterResponse, error)
	// Enqueue a dead letter again as a fresh job, removing the entry.
	//
	// Not idempotent: each successful call makes a job, and a second call finds
	// no entry.
	ReplayDeadLetter(context.Context, *ReplayDeadLetterRequest) (*ReplayDeadLetterResponse, error)
	// Delete one dead-letter entry.
	DeleteDeadLetter(context.Context, *DeleteDeadLetterRequest) (*DeleteDeadLetterResponse, error)
	// Delete dead-letter entries in bulk.
	PurgeDeadLetters(context.Context, *PurgeDeadLettersRequest) (*PurgeDeadLettersResponse, error)
	// The namespace's registered workers and their heartbeats.
	ListWorkers(context.Context, *ListWorkersRequest) (*ListWorkersResponse, error)
	// Ask one worker to drain: it stops claiming work, finishes what it holds,
	// and unregisters — the same graceful stop a SIGTERM gives it.
	//
	// The worker reads the request on its next heartbeat, a few seconds later,
	// so the answer is the request recorded, not the drain done: the worker
	// comes back DRAINING, and leaves ListWorkers once it has stopped.
	DrainWorker(context.Context, *DrainWorkerRequest) (*DrainWorkerResponse, error)
	// Every periodic task in the namespace.
	ListPeriodicTasks(context.Context, *ListPeriodicTasksRequest) (*ListPeriodicTasksResponse, error)
	// Read one periodic task.
	GetPeriodicTask(context.Context, *GetPeriodicTaskRequest) (*GetPeriodicTaskResponse, error)
	// Create a periodic task, or replace an existing one's definition.
	//
	// A replace keeps what an operator set and a definition does not own:
	// whether the task is paused, and when it last ran. Its next run moves only
	// when the cron expression or the timezone changed. A task also declared in
	// a worker's code is declared again when that worker starts.
	PutPeriodicTask(context.Context, *PutPeriodicTaskRequest) (*PutPeriodicTaskResponse, error)
	// Delete a periodic task. Jobs it already fired are untouched.
	DeletePeriodicTask(context.Context, *DeletePeriodicTaskRequest) (*DeletePeriodicTaskResponse, error)
	// Stop a periodic task firing, keeping its definition.
	PausePeriodicTask(context.Context, *PausePeriodicTaskRequest) (*PausePeriodicTaskResponse, error)
	// Let a paused periodic task fire again.
	ResumePeriodicTask(context.Context, *ResumePeriodicTaskRequest) (*ResumePeriodicTaskResponse, error)
	// Fire a periodic task now, whether or not it is paused.
	//
	// Enqueues the job the schedule would, and leaves the schedule alone: the
	// next run and the last run are unchanged. Not idempotent — each call is a
	// job.
	TriggerPeriodicTask(context.Context, *TriggerPeriodicTaskRequest) (*TriggerPeriodicTaskResponse, error)
	// Every task and queue override in the namespace.
	ListOverrides(context.Context, *ListOverridesRequest) (*ListOverridesResponse, error)
	// Replace one task's override. Not a merge: a field left unset is no longer
	// overridden.
	SetTaskOverride(context.Context, *SetTaskOverrideRequest) (*SetTaskOverrideResponse, error)
	// Remove one task's override, so its declared values apply again.
	ClearTaskOverride(context.Context, *ClearTaskOverrideRequest) (*ClearTaskOverrideResponse, error)
	// Replace one queue's override. Not a merge.
	SetQueueOverride(context.Context, *SetQueueOverrideRequest) (*SetQueueOverrideResponse, error)
	// Remove one queue's override.
	ClearQueueOverride(context.Context, *ClearQueueOverrideRequest) (*ClearQueueOverrideResponse, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) ListQueues(context.Context, *ListQueuesRequest) (*ListQueuesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListQueues not implemented")
}
func (UnimplementedAdminServiceServer) PauseQueue(context.Context, *PauseQueueRequest) (*PauseQueueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PauseQueue not implemented")
}
func (UnimplementedAdminServiceServer) ResumeQueue(context.Context, *ResumeQueueRequest) (*ResumeQueueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeQueue not implemented")
}
func (UnimplementedAdminServiceServer) GetThroughput(context.Context, *GetThroughputRequest) (*GetThroughputResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetThroughput not implemented")
}
func (UnimplementedAdminServiceServer) ListDeadLetters(context.Context, *ListDeadLettersRequest) (*ListDeadLettersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDeadLetters not implemented")
}
func (UnimplementedAdminServiceServer) GetDeadLetter(context.Context, *GetDeadLetterRequest) (*GetDeadLetterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeadLetter not implemented")
}
func (UnimplementedAdminServiceServer) ReplayDeadLetter(context.Context, *ReplayDeadLetterRequest) (*ReplayDeadLetterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplayDeadLetter not implemented")
}
func (UnimplementedAdminServiceServer) DeleteDeadLetter(context.Context, *DeleteDeadLetterRequest) (*DeleteDeadLetterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDeadLetter not implemented")
}
func (UnimplementedAdminServiceServer) PurgeDeadLetters(context.Context, *PurgeDeadLettersRequest) (*PurgeDeadLettersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PurgeDeadLetters not implemented")
}
func (UnimplementedAdminServiceServer) ListWorkers(context.Context, *ListWorkersRequest) (*ListWorkersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWorkers not implemented")
}
func (UnimplementedAdminServiceServer) DrainWorker(context.Context, *DrainWorkerRequest) (*DrainWorkerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DrainWorker not implemented")
}
func (UnimplementedAdminServiceServer) ListPeriodicTasks(context.Context, *ListPeriodicTasksRequest) (*ListPeriodicTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPeriodicTasks not implemented")
}
func (UnimplementedAdminServiceServer) GetPeriodicTask(context.Context, *GetPeriodicTaskRequest) (*GetPeriodicTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPeriodicTask not implemented")
}
func (UnimplementedAdminServiceServer) PutPeriodicTask(context.Context, *PutPeriodicTaskRequest) (*PutPeriodicTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutPeriodicTask not implemented")
}
func (UnimplementedAdminServiceServer) DeletePeriodicTask(context.Context, *DeletePeriodicTaskRequest) (*DeletePeriodicTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePeriodicTask not implemented")
}
func (UnimplementedAdminServiceServer) PausePeriodicTask(context.Context, *PausePeriodicTaskRequest) (*PausePeriodicTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PausePeriodicTask not implemented")
}
func (UnimplementedAdminServiceServer) ResumePeriodicTask(context.Context, *ResumePeriodicTaskRequest) (*ResumePeriodicTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumePeriodicTask not implemented")
}
func (UnimplementedAdminServiceServer) TriggerPeriodicTask(context.Context, *TriggerPeriodicTaskRequest) (*TriggerPeriodicTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TriggerPeriodicTask not implemented")
}
func (UnimplementedAdminServiceServer) ListOverrides(context.Context, *ListOverridesRequest) (*ListOverridesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOverrides not implemented")
}
func (UnimplementedAdminServiceServer) SetTaskOverride(context.Context, *SetTaskOverrideRequest) (*SetTaskOverrideResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTaskOverride not implemented")
}
func (UnimplementedAdminServiceServer) ClearTaskOverride(context.Context, *ClearTaskOverrideRequest) (*ClearTaskOverrideResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearTaskOverride not implemented")
}
func (UnimplementedAdminServiceServer) SetQueueOverride(context.Context, *SetQueueOverrideRequest) (*SetQueueOverrideResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetQueueOverride not implemented")
}
func (UnimplementedAdminServiceServer) ClearQueueOverride(context.Context, *ClearQueueOverrideRequest) (*ClearQueueOverrideResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearQueueOverride not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call pancis, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_ListQueues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListQueuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListQueues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListQueues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListQueues(ctx, req.(*ListQueuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_PauseQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).PauseQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_PauseQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).PauseQueue(ctx, req.(*PauseQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ResumeQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ResumeQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ResumeQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ResumeQueue(ctx, req.(*ResumeQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetThroughput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetThroughputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetThroughput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetThroughput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetThroughput(ctx, req.(*GetThroughputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListDeadLetters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeadLettersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListDeadLetters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListDeadLetters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListDeadLetters(ctx, req.(*ListDeadLettersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetDeadLetter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeadLetterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetDeadLetter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetDeadLetter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetDeadLetter(ctx, req.(*GetDeadLetterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ReplayDeadLetter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplayDeadLetterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ReplayDeadLetter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ReplayDeadLetter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ReplayDeadLetter(ctx, req.(*ReplayDeadLetterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_DeleteDeadLetter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDeadLetterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).DeleteDeadLetter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_DeleteDeadLetter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).DeleteDeadLetter(ctx, req.(*DeleteDeadLetterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_PurgeDeadLetters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurgeDeadLettersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).PurgeDeadLetters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_PurgeDeadLetters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).PurgeDeadLetters(ctx, req.(*PurgeDeadLettersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListWorkers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListWorkers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListWorkers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListWorkers(ctx, req.(*ListWorkersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_DrainWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrainWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).DrainWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_DrainWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).DrainWorker(ctx, req.(*DrainWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListPeriodicTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPeriodicTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListPeriodicTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListPeriodicTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListPeriodicTasks(ctx, req.(*ListPeriodicTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetPeriodicTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPeriodicTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetPeriodicTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetPeriodicTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetPeriodicTask(ctx, req.(*GetPeriodicTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_PutPeriodicTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutPeriodicTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).PutPeriodicTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_PutPeriodicTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).PutPeriodicTask(ctx, req.(*PutPeriodicTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_DeletePeriodicTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePeriodicTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).DeletePeriodicTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_DeletePeriodicTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).DeletePeriodicTask(ctx, req.(*DeletePeriodicTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_PausePeriodicTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PausePeriodicTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).PausePeriodicTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_PausePeriodicTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).PausePeriodicTask(ctx, req.(*PausePeriodicTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ResumePeriodicTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumePeriodicTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ResumePeriodicTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ResumePeriodicTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ResumePeriodicTask(ctx, req.(*ResumePeriodicTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_TriggerPeriodicTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerPeriodicTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).TriggerPeriodicTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_TriggerPeriodicTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).TriggerPeriodicTask(ctx, req.(*TriggerPeriodicTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListOverrides_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOverridesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListOverrides(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListOverrides_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListOverrides(ctx, req.(*ListOverridesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_SetTaskOverride_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTaskOverrideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SetTaskOverride(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_SetTaskOverride_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SetTaskOverride(ctx, req.(*SetTaskOverrideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ClearTaskOverride_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearTaskOverrideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ClearTaskOverride(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ClearTaskOverride_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ClearTaskOverride(ctx, req.(*ClearTaskOverrideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_SetQueueOverride_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetQueueOverrideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SetQueueOverride(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_SetQueueOverride_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SetQueueOverride(ctx, req.(*SetQueueOverrideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ClearQueueOverride_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearQueueOverrideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ClearQueueOverride(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ClearQueueOverride_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ClearQueueOverride(ctx, req.(*ClearQueueOverrideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flexiq.admin.v1.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListQueues",
			Handler:    _AdminService_ListQueues_Handler,
		},
		{
			MethodName: "PauseQueue",
			Handler:    _AdminService_PauseQueue_Handler,
		},
		{
			MethodName: "ResumeQueue",
			Handler:    _AdminService_ResumeQueue_Handler,
		},
		{
			MethodName: "GetThroughput",
			Handler:    _AdminService_GetThroughput_Handler,
		},
		{
			MethodName: "ListDeadLetters",
			Handler:    _AdminService_ListDeadLetters_Handler,
		},
		{
			MethodName: "GetDeadLetter",
			Handler:    _AdminService_GetDeadLetter_Handler,
		},
		{
			MethodName: "ReplayDeadLetter",
			Handler:    _AdminService_ReplayDeadLetter_Handler,
		},
		{
			MethodName: "DeleteDeadLetter",
			Handler:    _AdminService_DeleteDeadLetter_Handler,
		},
		{
			MethodName: "PurgeDeadLetters",
			Handler:    _AdminService_PurgeDeadLetters_Handler,
		},
		{
			MethodName: "ListWorkers",
			Handler:    _AdminService_ListWorkers_Handler,
		},
		{
			MethodName: "DrainWorker",
			Handler:    _AdminService_DrainWorker_Handler,
		},
		{
			MethodName: "ListPeriodicTasks",
			Handler:    _AdminService_ListPeriodicTasks_Handler,
		},
		{
			MethodName: "GetPeriodicTask",
			Handler:    _AdminService_GetPeriodicTask_Handler,
		},
		{
			MethodName: "PutPeriodicTask",
			Handler:    _AdminService_PutPeriodicTask_Handler,
		},
		{
			MethodName: "DeletePeriodicTask",
			Handler:    _AdminService_DeletePeriodicTask_Handler,
		},
		{
			MethodName: "PausePeriodicTask",
			Handler:    _AdminService_PausePeriodicTask_Handler,
		},
		{
			MethodName: "ResumePeriodicTask",
			Handler:    _AdminService_ResumePeriodicTask_Handler,
		},
		{
			MethodName: "TriggerPeriodicTask",
			Handler:    _AdminService_TriggerPeriodicTask_Handler,
		},
		{
			MethodName: "ListOverrides",
			Handler:    _AdminService_ListOverrides_Handler,
		},
		{
			MethodName: "SetTaskOverride",
			Handler:    _AdminService_SetTaskOverride_Handler,
		},
		{
			MethodName: "ClearTaskOverride",
			Handler:    _AdminService_ClearTaskOverride_Handler,
		},
		{
			MethodName: "SetQueueOverride",
			Handler:    _AdminService_SetQueueOverride_Handler,
		},
		{
			MethodName: "ClearQueueOverride",
			Handler:    _AdminService_ClearQueueOverride_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flexiq/admin/v1/admin_service.proto",
}
