package org.byteveda.flexiq.graalvm;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.util.List;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;
import org.byteveda.flexiq.FlexiQ;
import org.byteveda.flexiq.JobContext;
import org.byteveda.flexiq.events.EventName;
import org.byteveda.flexiq.model.JobFilter;
import org.byteveda.flexiq.scheduling.PeriodicTask;
import org.byteveda.flexiq.task.RetryPolicy;
import org.byteveda.flexiq.task.Task;
import org.byteveda.flexiq.worker.Worker;

/**
 * Drives the SDK's JNI dispatch and Jackson (de)serialization end to end so a
 * GraalVM native image of this class proves the shipped reachability metadata is
 * complete. Exits non-zero on any failure.
 */
public final class Smoke {

    private Smoke() {}

    /**
     * Runs the smoke checks, exiting non-zero on the first failure.
     *
     * @param args ignored
     * @throws Exception if any check fails, which fails the native-image job
     */
    public static void main(String[] args) throws Exception {
        Path dir = Files.createTempDirectory("flexiq-graalvm-smoke");
        Task<String> echo = Task.of("echo", String.class);
        Task<String> doomed = Task.of("doomed", String.class).maxRetries(0);
        // Durable steps cross the JNI boundary in both directions and in ways
        // nothing else here does: the binding *constructs* Java records
        // (StepDecision, StepSleepOutcome) and *throws* Java classes by name.
        // Neither is reachable from bytecode, so only exercising them proves the
        // shipped JNI metadata covers them.
        RetryPolicy fast = RetryPolicy.delays(Duration.ofMillis(10), Duration.ofMillis(10));
        Task<String> stepped = Task.of("stepped", String.class).maxRetries(2).retryPolicy(fast);
        Task<String> drifting = Task.of("drifting", String.class).maxRetries(5).retryPolicy(fast);

        try (FlexiQ queue = FlexiQ.builder()
                .backend("sqlite")
                .url(dir.resolve("smoke.db").toString())
                .open()) {
            String id = queue.enqueue(echo, "graalvm");
            queue.enqueue(doomed, "dead-letter");
            // CounterTasks is generated by the @TaskHandler processor; nothing here
            // registers its handler, and no code names it at worker-build time.
            String totalId = queue.enqueue(CounterTasks.TOTAL, List.of(1, 2, 3, 4));
            String steppedId = queue.enqueue(stepped, "graalvm");
            queue.enqueue(drifting, "diverge");

            // echo, the discovered counter, and the step task.
            CountDownLatch done = new CountDownLatch(3);
            CountDownLatch dead = new CountDownLatch(2);
            AtomicInteger steppedBodies = new AtomicInteger();
            AtomicInteger driftingAttempts = new AtomicInteger();
            Worker worker = queue.worker()
                    .discover() // handlers listed in META-INF/services at compile time
                    .handle(echo, (String payload) -> payload.length())
                    .handle(doomed, (String payload) -> {
                        throw new IllegalStateException("always fails");
                    })
                    // A step, then a sleep that ends the attempt: the waking
                    // attempt replays the step as a memo hit, so this covers a
                    // fresh decision, a memoized one, and both sleep outcomes.
                    .handle(stepped, (String payload) -> {
                        JobContext ctx = JobContext.current();
                        int length = ctx.step().run("measure", Integer.class, () -> {
                            steppedBodies.incrementAndGet();
                            return payload.length();
                        });
                        ctx.step().sleep(Duration.ofMillis(50));
                        return length;
                    })
                    // A divergence, which the binding reports by throwing a Java
                    // class it names as a string — the one JNI path that only
                    // runs when something has already gone wrong.
                    .handle(drifting, (String payload) -> {
                        JobContext ctx = JobContext.current();
                        if (driftingAttempts.incrementAndGet() == 1) {
                            ctx.step().run("first", String.class, () -> "a");
                            throw new IllegalStateException("die once, so the replay diverges");
                        }
                        return ctx.step().run("second", String.class, () -> "b");
                    })
                    .on(EventName.SUCCESS, event -> done.countDown())
                    .on(EventName.DEAD, event -> dead.countDown())
                    .start();
            try (worker) {
                if (!done.await(20, TimeUnit.SECONDS)) {
                    throw new IllegalStateException("tasks did not complete");
                }
                if (!dead.await(20, TimeUnit.SECONDS)) {
                    throw new IllegalStateException("doomed and diverging tasks did not dead-letter");
                }
            }

            // Once across two attempts: the sleep ended the first one, and the
            // second replayed the step from its committed row.
            if (steppedBodies.get() != 1) {
                throw new IllegalStateException("step body ran " + steppedBodies.get() + " times, expected 1");
            }
            int measured = queue.getResult(steppedId, Integer.class)
                    .orElseThrow(() -> new IllegalStateException("no result for the step task"));
            if (measured != 7) {
                throw new IllegalStateException("unexpected step result: " + measured);
            }
            // Two attempts, not the five its budget allows: a divergence is
            // permanent, so the binding's retry verdict crossed intact.
            if (driftingAttempts.get() != 2) {
                throw new IllegalStateException("diverging task ran " + driftingAttempts.get() + " attempts");
            }

            // The discovered handler ran, and its generic payload deserialized —
            // both under whatever reachability metadata the image was built with.
            int total = queue.getResult(totalId, Integer.class)
                    .orElseThrow(() -> new IllegalStateException("no result for the discovered task"));
            if (total != 10) {
                throw new IllegalStateException("unexpected discovered result: " + total);
            }

            byte[] result = queue.getResult(id).orElseThrow(() -> new IllegalStateException("no result persisted"));
            String value = new String(result, StandardCharsets.UTF_8);
            if (!"7".equals(value)) {
                throw new IllegalStateException("unexpected result: " + value);
            }

            // Exercise the Jackson DTO paths (PeriodicInfo + DeadJob + Page
            // deserialization). The agent generates the reflection metadata from
            // what this actually calls, so a DTO the smoke never touches gets no
            // entry and fails under --no-fallback at runtime.
            queue.registerPeriodic(
                    PeriodicTask.builder("nightly", "echo", "0 0 0 * * *").build());
            if (queue.listPeriodic().isEmpty()) {
                throw new IllegalStateException("listPeriodic returned empty");
            }
            // Non-empty on purpose: DeadJob's @JsonCreator constructor must be
            // invocable under native-image, and an empty page never exercises it.
            if (queue.listDead(10, 0).isEmpty()) {
                throw new IllegalStateException("listDead returned empty");
            }
            // Page is generic, so its element type has to be exercised too.
            queue.listJobsAfter(JobFilter.builder().limit(10).build(), null);

            System.out.println("flexiq graalvm smoke ok");
        }
    }
}
