package org.byteveda.flexiq.graalvm;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;
import org.byteveda.flexiq.FlexiQ;
import org.byteveda.flexiq.events.EventName;
import org.byteveda.flexiq.model.JobFilter;
import org.byteveda.flexiq.scheduling.PeriodicTask;
import org.byteveda.flexiq.task.Task;
import org.byteveda.flexiq.worker.Worker;

/**
 * Drives the SDK's JNI dispatch and Jackson (de)serialization end to end so a
 * GraalVM native image of this class proves the shipped reachability metadata is
 * complete. Exits non-zero on any failure.
 */
public final class Smoke {

    private Smoke() {}

    public static void main(String[] args) throws Exception {
        Path dir = Files.createTempDirectory("flexiq-graalvm-smoke");
        Task<String> echo = Task.of("echo", String.class);
        Task<String> doomed = Task.of("doomed", String.class).maxRetries(0);

        try (FlexiQ queue = FlexiQ.builder()
                .backend("sqlite")
                .url(dir.resolve("smoke.db").toString())
                .open()) {
            String id = queue.enqueue(echo, "graalvm");
            queue.enqueue(doomed, "dead-letter");
            // CounterTasks is generated by the @TaskHandler processor; nothing here
            // registers its handler, and no code names it at worker-build time.
            String totalId = queue.enqueue(CounterTasks.TOTAL, List.of(1, 2, 3, 4));

            CountDownLatch done = new CountDownLatch(2);
            CountDownLatch dead = new CountDownLatch(1);
            Worker worker = queue.worker()
                    .discover() // handlers listed in META-INF/services at compile time
                    .handle(echo, (String payload) -> payload.length())
                    .handle(doomed, (String payload) -> {
                        throw new IllegalStateException("always fails");
                    })
                    .on(EventName.SUCCESS, event -> done.countDown())
                    .on(EventName.DEAD, event -> dead.countDown())
                    .start();
            try (worker) {
                if (!done.await(20, TimeUnit.SECONDS)) {
                    throw new IllegalStateException("tasks did not complete");
                }
                if (!dead.await(20, TimeUnit.SECONDS)) {
                    throw new IllegalStateException("doomed task did not dead-letter");
                }
            }

            // The discovered handler ran, and its generic payload deserialized —
            // both under whatever reachability metadata the image was built with.
            int total = queue.getResult(totalId, Integer.class)
                    .orElseThrow(() -> new IllegalStateException("no result for the discovered task"));
            if (total != 10) {
                throw new IllegalStateException("unexpected discovered result: " + total);
            }

            byte[] result = queue.getResult(id).orElseThrow(() -> new IllegalStateException("no result persisted"));
            String value = new String(result, StandardCharsets.UTF_8);
            if (!"7".equals(value)) {
                throw new IllegalStateException("unexpected result: " + value);
            }

            // Exercise the Jackson DTO paths (PeriodicInfo + DeadJob + Page
            // deserialization). The agent generates the reflection metadata from
            // what this actually calls, so a DTO the smoke never touches gets no
            // entry and fails under --no-fallback at runtime.
            queue.registerPeriodic(
                    PeriodicTask.builder("nightly", "echo", "0 0 0 * * *").build());
            if (queue.listPeriodic().isEmpty()) {
                throw new IllegalStateException("listPeriodic returned empty");
            }
            // Non-empty on purpose: DeadJob's @JsonCreator constructor must be
            // invocable under native-image, and an empty page never exercises it.
            if (queue.listDead(10, 0).isEmpty()) {
                throw new IllegalStateException("listDead returned empty");
            }
            // Page is generic, so its element type has to be exercised too.
            queue.listJobsAfter(JobFilter.builder().limit(10).build(), null);

            System.out.println("flexiq graalvm smoke ok");
        }
    }
}
