{{- if include "flexiq-server.createsSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flexiq-server.secretName" . }}
  labels:
    {{- include "flexiq-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if and .Values.storage.dsn (not .Values.storage.existingSecret) }}
  dsn: {{ .Values.storage.dsn | quote }}
  {{- end }}
  {{- if and .Values.attach.token (not .Values.attach.existingSecret) }}
  attach-token: {{ .Values.attach.token | quote }}
  {{- end }}
  {{- if and .Values.dashboard.adminPassword (not .Values.dashboard.existingSecret) }}
  admin-password: {{ .Values.dashboard.adminPassword | quote }}
  {{- end }}
  {{- with .Values.dashboard.metricsToken }}
  metrics-token: {{ . | quote }}
  {{- end }}
{{- end }}
