# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: flexiq/executor/v1/executor_service.proto for package 'FlexiQ.Executor.V1'
# Original file comments:
# STABLE as of 2.0.0, the release that first shipped the gRPC role. Field
# numbers, field names and RPC shapes are permanent from here (§2.2 of
# tasks/specs/2026-09-01-flexiq-v1-proto-design.md): the `proto-breaking`
# label is for reverting a mistake made in the same release train, never for
# changing a shipped shape.
#
# The rules this package is held to, because a client reads the .proto and not
# the design document:
#
#   1. Field numbers are never reused and never renumbered.
#   2. Fields are deprecated in place, and on removal both the number and the
#      name are reserved.
#   3. New RPCs, messages, fields and enum values are additive and never bump
#      the package version.
#   4. A field's meaning and units are frozen with its number.
#   5. Readers tolerate what they do not know: unknown fields, unknown enum
#      values, unknown oneof arms.
#
# This package is deliberately separate from flexiq.v1. The audiences,
# credentials and exposure differ: a producer submits work, an executor runs
# it. flexiq.executor.v1 may import flexiq.v1; the reverse import is forbidden,
# so the package a third party generates a producer client from stays
# compilable and reviewable on its own.
#

require 'grpc'
require 'flexiq/executor/v1/executor_service_pb'

module FlexiQ
  module Executor
    module V1
      module ExecutorService
        # The executor door: attach, run what you are given, report what happened.
        #
        # An attached executor holds no database credential. It never reads a job row,
        # never writes a result, and never resolves its own namespace, owner or attempt
        # — the scheduler applies every one of those from the dispatch it recorded.
        # That is what makes this a door an application container may dial out through.
        #
        # The frames below are the worker frame protocol in BINDING_CONTRACT.md, with
        # the same ordering rules and the same meanings. This service is a fourth
        # transport for that protocol, not a second one: an executor attached over gRPC
        # and an executor attached over a socket are the same executor to the
        # scheduler, are placed by the same rules, and appear side by side in the same
        # registry.
        #
        # What this service deliberately does not have:
        #
        #   * No HTTP binding, ever. The JSON facade serves flexiq.v1 and nothing else.
        #   * No admin surface, and no producer surface. A credential scoped to this
        #     package may run work; it may not submit any.
        #   * No way to name a namespace, an owner, an attempt or a resource cap.
        #     Anything an executor could name is something an executor could forge, so
        #     the scheduler resolves all of them itself.
        #   * No registry fingerprint on the wire. `hello` carries `tasks` and the
        #     scheduler derives the fingerprint from it; a wire field would be a second
        #     copy of one fact, free to disagree with the first.
        #
        # One thing a client must do for itself: **raise its own message-size limits.**
        # gRPC libraries default to 4 MiB in each direction, and this door carries the
        # payloads the worker frame protocol allows — up to 64 MiB, plus envelope. An
        # executor that leaves the default in place attaches fine and then fails on its
        # first large job, which is the worst time to find out.
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'flexiq.executor.v1.ExecutorService'

          # Attach for the lifetime of one stream: `hello` in, `hello_ack` out, then
          # jobs out and results in until either side ends it.
          #
          # **The stream is bounded on purpose.** A stream cannot be load balanced once
          # it has started, so the scheduler ends it on a timer and expects the
          # executor to reconnect. Before it does, it stops matching new work to the
          # stream and waits for what the executor already holds, so a rotation never
          # costs a job. A clean end means "reconnect"; a `shutdown` frame means "stop".
          rpc :Attach, stream(::FlexiQ::Executor::V1::AttachRequest), stream(::FlexiQ::Executor::V1::AttachResponse)
          # Report liveness and current free capacity.
          #
          # Off the dispatch stream on purpose. A heartbeat sharing the stream it is
          # meant to report on cannot distinguish a busy stream from a dead peer, and
          # it is the first thing a stream-per-connection design has to take back out.
          #
          # `session` comes from the `flexiq-attach-session-bin` metadata on the Attach
          # response. It is the scheduler's own value handed back: an executor naming
          # itself here could shrink a peer's advertised capacity by claiming its id.
          #
          # The metadata arrives before the handshake finishes, but this RPC is still
          # ordered behind it: `hello` is the first thing the scheduler reads on a
          # stream, and a heartbeat that overtakes it is read *as* the handshake and
          # refuses the attach. Wait for `hello_ack`.
          rpc :Heartbeat, ::FlexiQ::Executor::V1::HeartbeatRequest, ::FlexiQ::Executor::V1::HeartbeatResponse
          # Report the outcome of a dispatch that outlived the request it arrived on.
          #
          # For a push target, which is handed a job over HTTP and answers `202
          # Accepted` because the work will not finish inside the platform's request
          # deadline. The connection that started the job is gone by the time this is
          # called; the lease inside the frame is what says which dispatch of which
          # attempt is being settled.
          #
          # **Single-use, and fenced.** The scheduler records one settle marker per
          # accepted dispatch and removes it in the same statement that tests it, so
          # exactly one of this RPC, the same RPC on another replica, and the settle
          # deadline passing can win. A call that lost that race is
          # FAILED_PRECONDITION — never ABORTED, which sits in the retry-with-backoff
          # class: a settle that lost its fence must not be resent, because resending
          # it is the double execution the fence exists to refuse.
          rpc :Settle, ::FlexiQ::Executor::V1::SettleRequest, ::FlexiQ::Executor::V1::SettleResponse
          # Ask for longer before the attempt is considered lost.
          #
          # An accepted dispatch is waited on until a deadline, and a target that
          # needs longer than the job's timeout must be able to say so or the job is
          # retried under it. Repeatable: the ceiling is per call, not in total, so a
          # target that needs six hours asks six times and its asking is the liveness
          # signal. A target that stops asking is one the deadline will collect.
          rpc :ExtendLease, ::FlexiQ::Executor::V1::ExtendLeaseRequest, ::FlexiQ::Executor::V1::ExtendLeaseResponse
          # Report progress for an accepted dispatch.
          #
          # The frame the attach stream carries, off the stream — a push target has no
          # stream to put it on. Fire and forget, as it is there: a task that only
          # wanted to report progress must never block on the scheduler to do it, and
          # an empty response says the frame was taken, not that a row was written.
          rpc :ReportProgress, ::FlexiQ::Executor::V1::ReportProgressRequest, ::FlexiQ::Executor::V1::ReportProgressResponse
          # Write one structured log line for an accepted dispatch. As
          # ReportProgress, and with the same fire-and-forget meaning.
          rpc :WriteTaskLog, ::FlexiQ::Executor::V1::WriteTaskLogRequest, ::FlexiQ::Executor::V1::WriteTaskLogResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
