{{- if and .Values.dashboard.enabled .Values.dashboard.ingress.enabled }}
{{- $fullname := include "taskito-server.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullname }}-dashboard
  labels:
    {{- include "taskito-server.labels" . | nindent 4 }}
  {{- with .Values.dashboard.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.dashboard.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.dashboard.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.dashboard.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.dashboard.ingress.path }}
            pathType: {{ .Values.dashboard.ingress.pathType }}
            backend:
              service:
                name: {{ $fullname }}-dashboard
                port:
                  name: dashboard
{{- end }}
