// STABLE as of 2.0.0, the release that first shipped the gRPC role. Field
// numbers, field names and RPC shapes are permanent from here (§2.2 of
// tasks/specs/2026-09-01-flexiq-v1-proto-design.md): the `proto-breaking`
// label is for reverting a mistake made in the same release train, never for
// changing a shipped shape.
//
// The rules this package is held to, because a client reads the .proto and not
// the design document:
//
//   1. Field numbers are never reused and never renumbered.
//   2. Fields are deprecated in place, and on removal both the number and the
//      name are reserved.
//   3. New RPCs, messages, fields and enum values are additive and never bump
//      the package version.
//   4. A field's meaning and units are frozen with its number.
//   5. Readers tolerate what they do not know: unknown fields, unknown enum
//      values, unknown oneof arms.
//
// This package is deliberately separate from flexiq.v1. The audiences,
// credentials and exposure differ: a producer submits work, an executor runs
// it. flexiq.executor.v1 may import flexiq.v1; the reverse import is forbidden,
// so the package a third party generates a producer client from stays
// compilable and reviewable on its own.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: flexiq/executor/v1/executor_service.proto

package executorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExecutorService_Attach_FullMethodName         = "/flexiq.executor.v1.ExecutorService/Attach"
	ExecutorService_Heartbeat_FullMethodName      = "/flexiq.executor.v1.ExecutorService/Heartbeat"
	ExecutorService_Settle_FullMethodName         = "/flexiq.executor.v1.ExecutorService/Settle"
	ExecutorService_ExtendLease_FullMethodName    = "/flexiq.executor.v1.ExecutorService/ExtendLease"
	ExecutorService_ReportProgress_FullMethodName = "/flexiq.executor.v1.ExecutorService/ReportProgress"
	ExecutorService_WriteTaskLog_FullMethodName   = "/flexiq.executor.v1.ExecutorService/WriteTaskLog"
)

// ExecutorServiceClient is the client API for ExecutorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The executor door: attach, run what you are given, report what happened.
//
// An attached executor holds no database credential. It never reads a job row,
// never writes a result, and never resolves its own namespace, owner or attempt
// — the scheduler applies every one of those from the dispatch it recorded.
// That is what makes this a door an application container may dial out through.
//
// The frames below are the worker frame protocol in BINDING_CONTRACT.md, with
// the same ordering rules and the same meanings. This service is a fourth
// transport for that protocol, not a second one: an executor attached over gRPC
// and an executor attached over a socket are the same executor to the
// scheduler, are placed by the same rules, and appear side by side in the same
// registry.
//
// What this service deliberately does not have:
//
//   - No HTTP binding, ever. The JSON facade serves flexiq.v1 and nothing else.
//   - No admin surface, and no producer surface. A credential scoped to this
//     package may run work; it may not submit any.
//   - No way to name a namespace, an owner, an attempt or a resource cap.
//     Anything an executor could name is something an executor could forge, so
//     the scheduler resolves all of them itself.
//   - No registry fingerprint on the wire. `hello` carries `tasks` and the
//     scheduler derives the fingerprint from it; a wire field would be a second
//     copy of one fact, free to disagree with the first.
//
// One thing a client must do for itself: **raise its own message-size limits.**
// gRPC libraries default to 4 MiB in each direction, and this door carries the
// payloads the worker frame protocol allows — up to 64 MiB, plus envelope. An
// executor that leaves the default in place attaches fine and then fails on its
// first large job, which is the worst time to find out.
type ExecutorServiceClient interface {
	// Attach for the lifetime of one stream: `hello` in, `hello_ack` out, then
	// jobs out and results in until either side ends it.
	//
	// **The stream is bounded on purpose.** A stream cannot be load balanced once
	// it has started, so the scheduler ends it on a timer and expects the
	// executor to reconnect. Before it does, it stops matching new work to the
	// stream and waits for what the executor already holds, so a rotation never
	// costs a job. A clean end means "reconnect"; a `shutdown` frame means "stop".
	Attach(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AttachRequest, AttachResponse], error)
	// Report liveness and current free capacity.
	//
	// Off the dispatch stream on purpose. A heartbeat sharing the stream it is
	// meant to report on cannot distinguish a busy stream from a dead peer, and
	// it is the first thing a stream-per-connection design has to take back out.
	//
	// `session` comes from the `flexiq-attach-session-bin` metadata on the Attach
	// response. It is the scheduler's own value handed back: an executor naming
	// itself here could shrink a peer's advertised capacity by claiming its id.
	//
	// The metadata arrives before the handshake finishes, but this RPC is still
	// ordered behind it: `hello` is the first thing the scheduler reads on a
	// stream, and a heartbeat that overtakes it is read *as* the handshake and
	// refuses the attach. Wait for `hello_ack`.
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// Report the outcome of a dispatch that outlived the request it arrived on.
	//
	// For a push target, which is handed a job over HTTP and answers `202
	// Accepted` because the work will not finish inside the platform's request
	// deadline. The connection that started the job is gone by the time this is
	// called; the lease inside the frame is what says which dispatch of which
	// attempt is being settled.
	//
	// **Single-use, and fenced.** The scheduler records one settle marker per
	// accepted dispatch and removes it in the same statement that tests it, so
	// exactly one of this RPC, the same RPC on another replica, and the settle
	// deadline passing can win. A call that lost that race is
	// FAILED_PRECONDITION — never ABORTED, which sits in the retry-with-backoff
	// class: a settle that lost its fence must not be resent, because resending
	// it is the double execution the fence exists to refuse.
	Settle(ctx context.Context, in *SettleRequest, opts ...grpc.CallOption) (*SettleResponse, error)
	// Ask for longer before the attempt is considered lost.
	//
	// An accepted dispatch is waited on until a deadline, and a target that
	// needs longer than the job's timeout must be able to say so or the job is
	// retried under it. Repeatable: the ceiling is per call, not in total, so a
	// target that needs six hours asks six times and its asking is the liveness
	// signal. A target that stops asking is one the deadline will collect.
	ExtendLease(ctx context.Context, in *ExtendLeaseRequest, opts ...grpc.CallOption) (*ExtendLeaseResponse, error)
	// Report progress for an accepted dispatch.
	//
	// The frame the attach stream carries, off the stream — a push target has no
	// stream to put it on. Fire and forget, as it is there: a task that only
	// wanted to report progress must never block on the scheduler to do it, and
	// an empty response says the frame was taken, not that a row was written.
	ReportProgress(ctx context.Context, in *ReportProgressRequest, opts ...grpc.CallOption) (*ReportProgressResponse, error)
	// Write one structured log line for an accepted dispatch. As
	// ReportProgress, and with the same fire-and-forget meaning.
	WriteTaskLog(ctx context.Context, in *WriteTaskLogRequest, opts ...grpc.CallOption) (*WriteTaskLogResponse, error)
}

type executorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExecutorServiceClient(cc grpc.ClientConnInterface) ExecutorServiceClient {
	return &executorServiceClient{cc}
}

func (c *executorServiceClient) Attach(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AttachRequest, AttachResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ExecutorService_ServiceDesc.Streams[0], ExecutorService_Attach_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AttachRequest, AttachResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExecutorService_AttachClient = grpc.BidiStreamingClient[AttachRequest, AttachResponse]

func (c *executorServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, ExecutorService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorServiceClient) Settle(ctx context.Context, in *SettleRequest, opts ...grpc.CallOption) (*SettleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettleResponse)
	err := c.cc.Invoke(ctx, ExecutorService_Settle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorServiceClient) ExtendLease(ctx context.Context, in *ExtendLeaseRequest, opts ...grpc.CallOption) (*ExtendLeaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtendLeaseResponse)
	err := c.cc.Invoke(ctx, ExecutorService_ExtendLease_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorServiceClient) ReportProgress(ctx context.Context, in *ReportProgressRequest, opts ...grpc.CallOption) (*ReportProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportProgressResponse)
	err := c.cc.Invoke(ctx, ExecutorService_ReportProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executorServiceClient) WriteTaskLog(ctx context.Context, in *WriteTaskLogRequest, opts ...grpc.CallOption) (*WriteTaskLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteTaskLogResponse)
	err := c.cc.Invoke(ctx, ExecutorService_WriteTaskLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExecutorServiceServer is the server API for ExecutorService service.
// All implementations must embed UnimplementedExecutorServiceServer
// for forward compatibility.
//
// The executor door: attach, run what you are given, report what happened.
//
// An attached executor holds no database credential. It never reads a job row,
// never writes a result, and never resolves its own namespace, owner or attempt
// — the scheduler applies every one of those from the dispatch it recorded.
// That is what makes this a door an application container may dial out through.
//
// The frames below are the worker frame protocol in BINDING_CONTRACT.md, with
// the same ordering rules and the same meanings. This service is a fourth
// transport for that protocol, not a second one: an executor attached over gRPC
// and an executor attached over a socket are the same executor to the
// scheduler, are placed by the same rules, and appear side by side in the same
// registry.
//
// What this service deliberately does not have:
//
//   - No HTTP binding, ever. The JSON facade serves flexiq.v1 and nothing else.
//   - No admin surface, and no producer surface. A credential scoped to this
//     package may run work; it may not submit any.
//   - No way to name a namespace, an owner, an attempt or a resource cap.
//     Anything an executor could name is something an executor could forge, so
//     the scheduler resolves all of them itself.
//   - No registry fingerprint on the wire. `hello` carries `tasks` and the
//     scheduler derives the fingerprint from it; a wire field would be a second
//     copy of one fact, free to disagree with the first.
//
// One thing a client must do for itself: **raise its own message-size limits.**
// gRPC libraries default to 4 MiB in each direction, and this door carries the
// payloads the worker frame protocol allows — up to 64 MiB, plus envelope. An
// executor that leaves the default in place attaches fine and then fails on its
// first large job, which is the worst time to find out.
type ExecutorServiceServer interface {
	// Attach for the lifetime of one stream: `hello` in, `hello_ack` out, then
	// jobs out and results in until either side ends it.
	//
	// **The stream is bounded on purpose.** A stream cannot be load balanced once
	// it has started, so the scheduler ends it on a timer and expects the
	// executor to reconnect. Before it does, it stops matching new work to the
	// stream and waits for what the executor already holds, so a rotation never
	// costs a job. A clean end means "reconnect"; a `shutdown` frame means "stop".
	Attach(grpc.BidiStreamingServer[AttachRequest, AttachResponse]) error
	// Report liveness and current free capacity.
	//
	// Off the dispatch stream on purpose. A heartbeat sharing the stream it is
	// meant to report on cannot distinguish a busy stream from a dead peer, and
	// it is the first thing a stream-per-connection design has to take back out.
	//
	// `session` comes from the `flexiq-attach-session-bin` metadata on the Attach
	// response. It is the scheduler's own value handed back: an executor naming
	// itself here could shrink a peer's advertised capacity by claiming its id.
	//
	// The metadata arrives before the handshake finishes, but this RPC is still
	// ordered behind it: `hello` is the first thing the scheduler reads on a
	// stream, and a heartbeat that overtakes it is read *as* the handshake and
	// refuses the attach. Wait for `hello_ack`.
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// Report the outcome of a dispatch that outlived the request it arrived on.
	//
	// For a push target, which is handed a job over HTTP and answers `202
	// Accepted` because the work will not finish inside the platform's request
	// deadline. The connection that started the job is gone by the time this is
	// called; the lease inside the frame is what says which dispatch of which
	// attempt is being settled.
	//
	// **Single-use, and fenced.** The scheduler records one settle marker per
	// accepted dispatch and removes it in the same statement that tests it, so
	// exactly one of this RPC, the same RPC on another replica, and the settle
	// deadline passing can win. A call that lost that race is
	// FAILED_PRECONDITION — never ABORTED, which sits in the retry-with-backoff
	// class: a settle that lost its fence must not be resent, because resending
	// it is the double execution the fence exists to refuse.
	Settle(context.Context, *SettleRequest) (*SettleResponse, error)
	// Ask for longer before the attempt is considered lost.
	//
	// An accepted dispatch is waited on until a deadline, and a target that
	// needs longer than the job's timeout must be able to say so or the job is
	// retried under it. Repeatable: the ceiling is per call, not in total, so a
	// target that needs six hours asks six times and its asking is the liveness
	// signal. A target that stops asking is one the deadline will collect.
	ExtendLease(context.Context, *ExtendLeaseRequest) (*ExtendLeaseResponse, error)
	// Report progress for an accepted dispatch.
	//
	// The frame the attach stream carries, off the stream — a push target has no
	// stream to put it on. Fire and forget, as it is there: a task that only
	// wanted to report progress must never block on the scheduler to do it, and
	// an empty response says the frame was taken, not that a row was written.
	ReportProgress(context.Context, *ReportProgressRequest) (*ReportProgressResponse, error)
	// Write one structured log line for an accepted dispatch. As
	// ReportProgress, and with the same fire-and-forget meaning.
	WriteTaskLog(context.Context, *WriteTaskLogRequest) (*WriteTaskLogResponse, error)
	mustEmbedUnimplementedExecutorServiceServer()
}

// UnimplementedExecutorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExecutorServiceServer struct{}

func (UnimplementedExecutorServiceServer) Attach(grpc.BidiStreamingServer[AttachRequest, AttachResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Attach not implemented")
}
func (UnimplementedExecutorServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedExecutorServiceServer) Settle(context.Context, *SettleRequest) (*SettleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Settle not implemented")
}
func (UnimplementedExecutorServiceServer) ExtendLease(context.Context, *ExtendLeaseRequest) (*ExtendLeaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExtendLease not implemented")
}
func (UnimplementedExecutorServiceServer) ReportProgress(context.Context, *ReportProgressRequest) (*ReportProgressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportProgress not implemented")
}
func (UnimplementedExecutorServiceServer) WriteTaskLog(context.Context, *WriteTaskLogRequest) (*WriteTaskLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteTaskLog not implemented")
}
func (UnimplementedExecutorServiceServer) mustEmbedUnimplementedExecutorServiceServer() {}
func (UnimplementedExecutorServiceServer) testEmbeddedByValue()                         {}

// UnsafeExecutorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExecutorServiceServer will
// result in compilation errors.
type UnsafeExecutorServiceServer interface {
	mustEmbedUnimplementedExecutorServiceServer()
}

func RegisterExecutorServiceServer(s grpc.ServiceRegistrar, srv ExecutorServiceServer) {
	// If the following call pancis, it indicates UnimplementedExecutorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExecutorService_ServiceDesc, srv)
}

func _ExecutorService_Attach_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ExecutorServiceServer).Attach(&grpc.GenericServerStream[AttachRequest, AttachResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ExecutorService_AttachServer = grpc.BidiStreamingServer[AttachRequest, AttachResponse]

func _ExecutorService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutorService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutorService_Settle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServiceServer).Settle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutorService_Settle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServiceServer).Settle(ctx, req.(*SettleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutorService_ExtendLease_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtendLeaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServiceServer).ExtendLease(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutorService_ExtendLease_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServiceServer).ExtendLease(ctx, req.(*ExtendLeaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutorService_ReportProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServiceServer).ReportProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutorService_ReportProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServiceServer).ReportProgress(ctx, req.(*ReportProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecutorService_WriteTaskLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteTaskLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecutorServiceServer).WriteTaskLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecutorService_WriteTaskLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecutorServiceServer).WriteTaskLog(ctx, req.(*WriteTaskLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExecutorService_ServiceDesc is the grpc.ServiceDesc for ExecutorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExecutorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flexiq.executor.v1.ExecutorService",
	HandlerType: (*ExecutorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heartbeat",
			Handler:    _ExecutorService_Heartbeat_Handler,
		},
		{
			MethodName: "Settle",
			Handler:    _ExecutorService_Settle_Handler,
		},
		{
			MethodName: "ExtendLease",
			Handler:    _ExecutorService_ExtendLease_Handler,
		},
		{
			MethodName: "ReportProgress",
			Handler:    _ExecutorService_ReportProgress_Handler,
		},
		{
			MethodName: "WriteTaskLog",
			Handler:    _ExecutorService_WriteTaskLog_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Attach",
			Handler:       _ExecutorService_Attach_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "flexiq/executor/v1/executor_service.proto",
}
