// STABLE as of 2.0.0, the release that first shipped the gRPC role. Field
// numbers, field names and RPC shapes are permanent from here (§2.2 of
// tasks/specs/2026-09-01-flexiq-v1-proto-design.md): the `proto-breaking`
// label is for reverting a mistake made in the same release train, never for
// changing a shipped shape.
//
// The rules this package is held to, because a client reads the .proto and not
// the design document:
//
//   1. Field numbers are never reused and never renumbered.
//   2. Fields are deprecated in place, and on removal both the number and the
//      name are reserved.
//   3. New RPCs, messages, fields and enum values are additive and never bump
//      the package version.
//   4. A field's meaning and units are frozen with its number.
//   5. Readers tolerate what they do not know: unknown fields, unknown enum
//      values, unknown oneof arms.
//
// This package is deliberately separate from flexiq.v1. The audiences,
// credentials and exposure differ: a producer submits work, an executor runs
// it. flexiq.executor.v1 may import flexiq.v1; the reverse import is forbidden,
// so the package a third party generates a producer client from stays
// compilable and reviewable on its own.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: flexiq/executor/v1/executor_service.proto

package executorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Whether a step commit carries a memoized value or a deadline.
type StepKind int32

const (
	StepKind_STEP_KIND_UNSPECIFIED StepKind = 0
	// A step whose result is recorded so a later attempt replays it.
	StepKind_STEP_KIND_RUN StepKind = 1
	// A `step.sleep`: the attempt ends and the job is rescheduled.
	StepKind_STEP_KIND_SLEEP StepKind = 2
)

// Enum value maps for StepKind.
var (
	StepKind_name = map[int32]string{
		0: "STEP_KIND_UNSPECIFIED",
		1: "STEP_KIND_RUN",
		2: "STEP_KIND_SLEEP",
	}
	StepKind_value = map[string]int32{
		"STEP_KIND_UNSPECIFIED": 0,
		"STEP_KIND_RUN":         1,
		"STEP_KIND_SLEEP":       2,
	}
)

func (x StepKind) Enum() *StepKind {
	p := new(StepKind)
	*p = x
	return p
}

func (x StepKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StepKind) Descriptor() protoreflect.EnumDescriptor {
	return file_flexiq_executor_v1_executor_service_proto_enumTypes[0].Descriptor()
}

func (StepKind) Type() protoreflect.EnumType {
	return &file_flexiq_executor_v1_executor_service_proto_enumTypes[0]
}

func (x StepKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StepKind.Descriptor instead.
func (StepKind) EnumDescriptor() ([]byte, []int) {
	return file_flexiq_executor_v1_executor_service_proto_rawDescGZIP(), []int{0}
}

// What an executor should do about a refused step commit.
//
// Classified by the side that holds storage, because only it can see the error.
type StepFailure int32

const (
	StepFailure_STEP_FAILURE_UNSPECIFIED StepFailure = 0
	// Transient. The attempt fails and the job retries.
	StepFailure_STEP_FAILURE_RETRYABLE StepFailure = 1
	// The commit will never succeed. Retrying only wastes an attempt.
	StepFailure_STEP_FAILURE_PERMANENT StepFailure = 2
	// Another attempt owns this job now. This one must stop without writing.
	StepFailure_STEP_FAILURE_SUPERSEDED StepFailure = 3
)

// Enum value maps for StepFailure.
var (
	StepFailure_name = map[int32]string{
		0: "STEP_FAILURE_UNSPECIFIED",
		1: "STEP_FAILURE_RETRYABLE",
		2: "STEP_FAILURE_PERMANENT",
		3: "STEP_FAILURE_SUPERSEDED",
	}
	StepFailure_value = map[string]int32{
		"STEP_FAILURE_UNSPECIFIED": 0,
		"STEP_FAILURE_RETRYABLE":   1,
		"STEP_FAILURE_PERMANENT":   2,
		"STEP_FAILURE_SUPERSEDED":  3,
	}
)

func (x StepFailure) Enum() *StepFailure {
	p := new(StepFailure)
	*p = x
	return p
}

func (x StepFailure) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StepFailure) Descriptor() protoreflect.EnumDescriptor {
	return file_flexiq_executor_v1_executor_service_proto_enumTypes[1].Descriptor()
}

func (StepFailure) Type() protoreflect.EnumType {
	return &file_flexiq_executor_v1_executor_service_proto_enumTypes[1]
}

func (x StepFailure) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StepFailure.Descriptor instead.
func (StepFailure) EnumDescriptor() ([]byte, []int) {
	return file_flexiq_executor_v1_executor_service_proto_rawDescGZIP(), []int{1}
}

// One frame from the executor.
//
// A oneof, so a frame this build does not recognise decodes to no arm and is
// skipped rather than ending the stream — the protobuf form of the frame
// protocol's "an unknown frame type is skipped, not fatal".
type AttachRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*AttachRequest_Hello
	//	*AttachRequest_Success
	//	*AttachRequest_Failure
	//	*AttachRequest_Cancelled
	//	*AttachRequest_Slept
	//	*AttachRequest_Progress
	//	*AttachRequest_TaskLog
	//	*AttachRequest_StepCommit
	Frame         isAttachRequest_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachRequest) Reset() {
	*x = AttachRequest{}
	mi := &file_flexiq_executor_v1_executor_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachRequest) ProtoMessage() {}

func (x *AttachRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_executor_v1_executor_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachRequest.ProtoReflect.Descriptor instead.
func (*AttachRequest) Descriptor() ([]byte, []int) {
	return file_flexiq_executor_v1_executor_service_proto_rawDescGZIP(), []int{0}
}

func (x *AttachRequest) GetFrame() isAttachRequest_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *AttachRequest) GetHello() *HelloFrame {
	if x != nil {
		if x, ok := x.Frame.(*AttachRequest_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AttachRequest) GetSuccess() *SuccessFrame {
	if x != nil {
		if x, ok := x.Frame.(*AttachRequest_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *AttachRequest) GetFailure() *FailureFrame {
	if x != nil {
		if x, ok := x.Frame.(*AttachRequest_Failure); ok {
			return x.Failure
		}
	}
	return nil
}

func (x *AttachRequest) GetCancelled() *CancelledFrame {
	if x != nil {
		if x, ok := x.Frame.(*AttachRequest_Cancelled); ok {
			return x.Cancelled
		}
	}
	return nil
}

func (x *AttachRequest) GetSlept() *SleptFrame {
	if x != nil {
		if x, ok := x.Frame.(*AttachRequest_Slept); ok {
			return x.Slept
		}
	}
	return nil
}

func (x *AttachRequest) GetProgress() *ProgressFrame {
	if x != nil {
		if x, ok := x.Frame.(*AttachRequest_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *AttachRequest) GetTaskLog() *TaskLogFrame {
	if x != nil {
		if x, ok := x.Frame.(*AttachRequest_TaskLog); ok {
			return x.TaskLog
		}
	}
	return nil
}

func (x *AttachRequest) GetStepCommit() *StepCommitFrame {
	if x != nil {
		if x, ok := x.Frame.(*AttachRequest_StepCommit); ok {
			return x.StepCommit
		}
	}
	return nil
}

type isAttachRequest_Frame interface {
	isAttachRequest_Frame()
}

type AttachRequest_Hello struct {
	Hello *HelloFrame `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AttachRequest_Success struct {
	Success *SuccessFrame `protobuf:"bytes,2,opt,name=success,proto3,oneof"`
}

type AttachRequest_Failure struct {
	Failure *FailureFrame `protobuf:"bytes,3,opt,name=failure,proto3,oneof"`
}

type AttachRequest_Cancelled struct {
	Cancelled *CancelledFrame `protobuf:"bytes,4,opt,name=cancelled,proto3,oneof"`
}

type AttachRequest_Slept struct {
	Slept *SleptFrame `protobuf:"bytes,5,opt,name=slept,proto3,oneof"`
}

type AttachRequest_Progress struct {
	Progress *ProgressFrame `protobuf:"bytes,6,opt,name=progress,proto3,oneof"`
}

type AttachRequest_TaskLog struct {
	TaskLog *TaskLogFrame `protobuf:"bytes,7,opt,name=task_log,json=taskLog,proto3,oneof"`
}

type AttachRequest_StepCommit struct {
	StepCommit *StepCommitFrame `protobuf:"bytes,8,opt,name=step_commit,json=stepCommit,proto3,oneof"`
}

func (*AttachRequest_Hello) isAttachRequest_Frame() {}

func (*AttachRequest_Success) isAttachRequest_Frame() {}

func (*AttachRequest_Failure) isAttachRequest_Frame() {}

func (*AttachRequest_Cancelled) isAttachRequest_Frame() {}

func (*AttachRequest_Slept) isAttachRequest_Frame() {}

func (*AttachRequest_Progress) isAttachRequest_Frame() {}

func (*AttachRequest_TaskLog) isAttachRequest_Frame() {}

func (*AttachRequest_StepCommit) isAttachRequest_Frame() {}

// One frame from the scheduler. Unknown arms are skipped, as above.
type AttachResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*AttachResponse_HelloAck
	//	*AttachResponse_Job
	//	*AttachResponse_JobSteps
	//	*AttachResponse_StepAck
	//	*AttachResponse_Cancel
	//	*AttachResponse_Shutdown
	Frame         isAttachResponse_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachResponse) Reset() {
	*x = AttachResponse{}
	mi := &file_flexiq_executor_v1_executor_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachResponse) ProtoMessage() {}

func (x *AttachResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_executor_v1_executor_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachResponse.ProtoReflect.Descriptor instead.
func (*AttachResponse) Descriptor() ([]byte, []int) {
	return file_flexiq_executor_v1_executor_service_proto_rawDescGZIP(), []int{1}
}

func (x *AttachResponse) GetFrame() isAttachResponse_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *AttachResponse) GetHelloAck() *HelloAckFrame {
	if x != nil {
		if x, ok := x.Frame.(*AttachResponse_HelloAck); ok {
			return x.HelloAck
		}
	}
	return nil
}

func (x *AttachResponse) GetJob() *JobFrame {
	if x != nil {
		if x, ok := x.Frame.(*AttachResponse_Job); ok {
			return x.Job
		}
	}
	return nil
}

func (x *AttachResponse) GetJobSteps() *JobStepsFrame {
	if x != nil {
		if x, ok := x.Frame.(*AttachResponse_JobSteps); ok {
			return x.JobSteps
		}
	}
	return nil
}

func (x *AttachResponse) GetStepAck() *StepAckFrame {
	if x != nil {
		if x, ok := x.Frame.(*AttachResponse_StepAck); ok {
			return x.StepAck
		}
	}
	return nil
}

func (x *AttachResponse) GetCancel() *CancelFrame {
	if x != nil {
		if x, ok := x.Frame.(*AttachResponse_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

func (x *AttachResponse) GetShutdown() *ShutdownFrame {
	if x != nil {
		if x, ok := x.Frame.(*AttachResponse_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

type isAttachResponse_Frame interface {
	isAttachResponse_Frame()
}

type AttachResponse_HelloAck struct {
	HelloAck *HelloAckFrame `protobuf:"bytes,1,opt,name=hello_ack,json=helloAck,proto3,oneof"`
}

type AttachResponse_Job struct {
	Job *JobFrame `protobuf:"bytes,2,opt,name=job,proto3,oneof"`
}

type AttachResponse_JobSteps struct {
	JobSteps *JobStepsFrame `protobuf:"bytes,3,opt,name=job_steps,json=jobSteps,proto3,oneof"`
}

type AttachResponse_StepAck struct {
	StepAck *StepAckFrame `protobuf:"bytes,4,opt,name=step_ack,json=stepAck,proto3,oneof"`
}

type AttachResponse_Cancel struct {
	Cancel *CancelFrame `protobuf:"bytes,5,opt,name=cancel,proto3,oneof"`
}

type AttachResponse_Shutdown struct {
	Shutdown *ShutdownFrame `protobuf:"bytes,6,opt,name=shutdown,proto3,oneof"`
}

func (*AttachResponse_HelloAck) isAttachResponse_Frame() {}

func (*AttachResponse_Job) isAttachResponse_Frame() {}

func (*AttachResponse_JobSteps) isAttachResponse_Frame() {}

func (*AttachResponse_StepAck) isAttachResponse_Frame() {}

func (*AttachResponse_Cancel) isAttachResponse_Frame() {}

func (*AttachResponse_Shutdown) isAttachResponse_Frame() {}

// First frame on every stream: who is attaching and what it can run.
//
// It carries no credential. The bearer token authorised this RPC before it was
// entered, and a second credential inside the body would be a second thing to
// keep in step with the first.
type HelloFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable identity of this executor. One live stream per id; a second attach
	// under an id already attached is refused.
	ExecutorId string `protobuf:"bytes,1,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`
	// SDK this executor is built on, for logs and inventory.
	Sdk     string `protobuf:"bytes,2,opt,name=sdk,proto3" json:"sdk,omitempty"`
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// Tasks this executor has handlers for. Nothing else is ever sent to it, and
	// the scheduler derives its registry fingerprint from exactly this list.
	Tasks []string `protobuf:"bytes,4,rep,name=tasks,proto3" json:"tasks,omitempty"`
	// How many jobs it can run at once.
	Slots uint32 `protobuf:"varint,5,opt,name=slots,proto3" json:"slots,omitempty"`
	// Worker frame protocol version. A mismatch is refused, after an ack, so both
	// ends can log both numbers.
	ProtocolVersion uint32 `protobuf:"varint,6,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// Optional behaviours this executor takes part in, e.g. "steps", "lease".
	//
	// Strings, not an enum: adding a capability must not be a proto change, which
	// is the entire cost the capability mechanism exists to avoid. An executor
	// claims nothing it has not implemented, and the scheduler sends no frame for
	// a behaviour that was not claimed.
	Capabilities  []string `protobuf:"bytes,7,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloFrame) Reset() {
	*x = HelloFrame{}
	mi := &file_flexiq_executor_v1_executor_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloFrame) ProtoMessage() {}

func (x *HelloFrame) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_executor_v1_executor_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloFrame.ProtoReflect.Descriptor instead.
func (*HelloFrame) Descriptor() ([]byte, []int) {
	return file_flexiq_executor_v1_executor_service_proto_rawDescGZIP(), []int{2}
}

func (x *HelloFrame) GetExecutorId() string {
	if x != nil {
		return x.ExecutorId
	}
	return ""
}

func (x *HelloFrame) GetSdk() string {
	if x != nil {
		return x.Sdk
	}
	return ""
}

func (x *HelloFrame) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HelloFrame) GetTasks() []string {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *HelloFrame) GetSlots() uint32 {
	if x != nil {
		return x.Slots
	}
	return 0
}

func (x *HelloFrame) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *HelloFrame) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// Answer to HelloFrame, completing the handshake.
type HelloAckFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity of the scheduler that accepted the attach.
	SchedulerId     string `protobuf:"bytes,1,opt,name=scheduler_id,json=schedulerId,proto3" json:"scheduler_id,omitempty"`
	ProtocolVersion uint32 `protobuf:"varint,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// Behaviours this scheduler supports. An executor that sees no capability
	// sends no frames that depend on one.
	Capabilities  []string `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloAckFrame) Reset() {
	*x = HelloAckFrame{}
	mi := &file_flexiq_executor_v1_executor_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAckFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAckFrame) ProtoMessage() {}

func (x *HelloAckFrame) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_executor_v1_executor_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAckFrame.ProtoReflect.Descriptor instead.
func (*HelloAckFrame) Descriptor() ([]byte, []int) {
	return file_flexiq_executor_v1_executor_service_proto_rawDescGZIP(), []int{3}
}

func (x *HelloAckFrame) GetSchedulerId() string {
	if x != nil {
		return x.SchedulerId
	}
	return ""
}

func (x *HelloAckFrame) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *HelloAckFrame) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// Run a job.
type JobFrame struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskName string                 `protobuf:"bytes,2,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	// The tagged envelope from BINDING_CONTRACT.md, opaque and never re-encoded.
	Payload []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// Retries already attempted.
	RetryCount int32  `protobuf:"varint,4,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	MaxRetries int32  `protobuf:"varint,5,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	Queue      string `protobuf:"bytes,6,opt,name=queue,proto3" json:"queue,omitempty"`
	// How long this attempt may run. Unset means no limit — which is also what
	// the frame protocol's non-positive `timeout_ms` means.
	Timeout *durationpb.Duration `protobuf:"bytes,7,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// Namespace the job belongs to, so a task that needs it does not have to ask.
	// Told to the executor; never accepted from one.
	Namespace *string `protobuf:"bytes,8,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	// Middleware the operator has disabled for this task, resolved at dispatch.
	//
	// It rides the dispatch because an executor has no settings store to read it
	// from. A toggle flipped in the dashboard takes effect on the next job.
	DisabledMiddleware []string `protobuf:"bytes,9,rep,name=disabled_middleware,json=disabledMiddleware,proto3" json:"disabled_middleware,omitempty"`
	// The job's metadata blob as stored: opaque JSON text, byte-preserved.
	Metadata *string `protobuf:"bytes,10,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	// The lease this dispatch was made under. Opaque, minted by the scheduler,
	// and required back on every frame that settles or advances the attempt.
	//
	// Absent when the executor did not advertise the "lease" capability. It is
	// not a credential and grants nothing: it identifies *which dispatch* of this
	// job a frame belongs to, so a stalled executor cannot write over the attempt
	// that replaced it.
	Lease         []byte `protobuf:"bytes,11,opt,name=lease,proto3,oneof" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobFrame) Reset() {
	*x = JobFrame{}
	mi := &file_flexiq_executor_v1_executor_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobFrame) ProtoMessage() {}

func (x *JobFrame) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_executor_v1_executor_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobFrame.ProtoReflect.Descriptor instead.
func (*JobFrame) Descriptor() ([]byte, []int) {
	return file_flexiq_executor_v1_executor_service_proto_rawDescGZIP(), []int{4}
}

func (x *JobFrame) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobFrame) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *JobFrame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *JobFrame) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *JobFrame) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *JobFrame) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *JobFrame) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *JobFrame) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

func (x *JobFrame) GetDisabledMiddleware() []string {
	if x != nil {
		return x.DisabledMiddleware
	}
	return nil
}

func (x *JobFrame) GetMetadata() string {
	if x != nil && x.Metadata != nil {
		return *x.Metadata
	}
	return ""
}

func (x *JobFrame) GetLease() []byte {
	if x != nil {
		return x.Lease
	}
	return nil
}

// The steps a job has already committed, sent immediately before its JobFrame
// so the executor can answer a memo hit without a storage read it has no
// credentials for.
//
// No frame means an empty snapshot, never an unknown one. Sent only to an
// executor that advertised the "steps" capability.
type JobStepsFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Job the snapshot belongs to. The JobFrame that follows repeats it.
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// The encoded snapshot, in the encoding BINDING_CONTRACT.md pins.
	Snapshot      []byte `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStepsFrame) Reset() {
	*x = JobStepsFrame{}
	mi := &file_flexiq_executor_v1_executor_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStepsFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStepsFrame) ProtoMessage() {}

func (x *JobStepsFrame) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_executor_v1_executor_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStepsFrame.ProtoReflect.Descriptor instead.
func (*JobStepsFrame) Descriptor() ([]byte, []int) {
	return file_flexiq_executor_v1_executor_service_proto_rawDescGZIP(), []int{5}
}

func (x *JobStepsFrame) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobStepsFrame) GetSnapshot() []byte {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

// Answer to StepCommitFrame.
//
// The executor blocks on this before returning from a step: an unconfirmed
// commit is indistinguishable from one that never happened, and carrying on
// past it re-runs the step next attempt with the side effect already applied.
type StepAckFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	JobId string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Position the commit named. (job_id, seq) is the correlation — one executor
	// runs many jobs, and a job id alone would not pair them.
	Seq int32 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	// Whether the step is durable now. True covers a fresh write and a
	// byte-identical retransmission alike.
	Ok bool `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
	// A byte-identical row was already at this position: a retransmission after a
	// lost ack, which is a success.
	Already bool `protobuf:"varint,4,opt,name=already,proto3" json:"already,omitempty"`
	// Deadline the job was *actually* rescheduled to, for a sleep commit. On a
	// replay this is the stored deadline, not the one proposed.
	WakeAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=wake_at,json=wakeAt,proto3" json:"wake_at,omitempty"`
	// Why the commit was refused, when ok is false.
	Error *string `protobuf:"bytes,6,opt,name=error,proto3,oneof" json:"error,omitempty"`
	// What to do about it, when ok is false.
	Failure       StepFailure `protobuf:"varint,7,opt,name=failure,proto3,enum=flexiq.executor.v1.StepFailure" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepAckFrame) Reset() {
	*x = StepAckFrame{}
	mi := &file_flexiq_executor_v1_executor_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepAckFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepAckFrame) ProtoMessage() {}

func (x *StepAckFrame) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_executor_v1_executor_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepAckFrame.ProtoReflect.Descriptor instead.
func (*StepAckFrame) Descriptor() ([]byte, []int) {
	return file_flexiq_executor_v1_executor_service_proto_rawDescGZIP(), []int{6}
}

func (x *StepAckFrame) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *StepAckFrame) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *StepAckFrame) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *StepAckFrame) GetAlready() bool {
	if x != nil {
		return x.Already
	}
	return false
}

func (x *StepAckFrame) GetWakeAt() *timestamppb.Timestamp {
	if x != nil {
		return x.WakeAt
	}
	return nil
}

func (x *StepAckFrame) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *StepAckFrame) GetFailure() StepFailure {
	if x != nil {
		return x.Failure
	}
	return StepFailure_STEP_FAILURE_UNSPECIFIED
}

// Cooperative cancel, so an executor observes a cancel without polling storage.
type CancelFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelFrame) Reset() {
	*x = CancelFrame{}
	mi := &file_flexiq_executor_v1_executor_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelFrame) ProtoMessage() {}

func (x *CancelFrame) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_executor_v1_executor_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelFrame.ProtoReflect.Descriptor instead.
func (*CancelFrame) Descriptor() ([]byte, []int) {
	return file_flexiq_executor_v1_executor_service_proto_rawDescGZIP(), []int{7}
}

func (x *CancelFrame) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

// Stop accepting work and exit once in-flight jobs finish.
//
// Distinct from the stream simply ending, which means "reconnect".
type ShutdownFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownFrame) Reset() {
	*x = ShutdownFrame{}
	mi := &file_flexiq_executor_v1_executor_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownFrame) ProtoMessage() {}

func (x *ShutdownFrame) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_executor_v1_executor_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownFrame.ProtoReflect.Descriptor instead.
func (*ShutdownFrame) Descriptor() ([]byte, []int) {
	return file_flexiq_executor_v1_executor_service_proto_rawDescGZIP(), []int{8}
}

// Progress for a running job, applied to storage by the scheduler.
//
// Fire and forget: there is nothing to answer, and a task that only wanted to
// report progress must never block on the scheduler to do it.
type ProgressFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The scheduler drops a frame naming a job the sending stream is not running.
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// 0-100. Anything else is dropped rather than stored.
	Progress int32 `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"`
	// See JobFrame.lease.
	Lease         []byte `protobuf:"bytes,3,opt,name=lease,proto3,oneof" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressFrame) Reset() {
	*x = ProgressFrame{}
	mi := &file_flexiq_executor_v1_executor_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressFrame) ProtoMessage() {}

func (x *ProgressFrame) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_executor_v1_executor_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressFrame.ProtoReflect.Descriptor instead.
func (*ProgressFrame) Descriptor() ([]byte, []int) {
	return file_flexiq_executor_v1_executor_service_proto_rawDescGZIP(), []int{9}
}

func (x *ProgressFrame) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ProgressFrame) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *ProgressFrame) GetLease() []byte {
	if x != nil {
		return x.Lease
	}
	return nil
}

// One structured log line for a running job, applied by the scheduler.
//
// A published partial is this frame at level "result", so logging and
// publishing share one frame.
type TaskLogFrame struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	JobId    string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	TaskName string                 `protobuf:"bytes,2,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	// e.g. "info", or "result" for a published partial.
	Level string `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`
	// Empty for a published partial, whose value lives in `extra`.
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// Pre-encoded JSON. Bytes rather than a string because the scheduler already
	// decides what to do with a blob that is not UTF-8 — it drops the blob and
	// keeps the line — and a string field would instead lose the whole frame.
	Extra []byte `protobuf:"bytes,5,opt,name=extra,proto3,oneof" json:"extra,omitempty"`
	// See JobFrame.lease.
	Lease         []byte `protobuf:"bytes,6,opt,name=lease,proto3,oneof" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskLogFrame) Reset() {
	*x = TaskLogFrame{}
	mi := &file_flexiq_executor_v1_executor_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskLogFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskLogFrame) ProtoMessage() {}

func (x *TaskLogFrame) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_executor_v1_executor_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskLogFrame.ProtoReflect.Descriptor instead.
func (*TaskLogFrame) Descriptor() ([]byte, []int) {
	return file_flexiq_executor_v1_executor_service_proto_rawDescGZIP(), []int{10}
}

func (x *TaskLogFrame) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *TaskLogFrame) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *TaskLogFrame) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *TaskLogFrame) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskLogFrame) GetExtra() []byte {
	if x != nil {
		return x.Extra
	}
	return nil
}

func (x *TaskLogFrame) GetLease() []byte {
	if x != nil {
		return x.Lease
	}
	return nil
}

// The task completed.
type SuccessFrame struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	JobId    string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	TaskName string                 `protobuf:"bytes,2,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	// Absent means the task returned nothing; present and empty means it returned
	// an empty value. They are different answers.
	Result []byte `protobuf:"bytes,3,opt,name=result,proto3,oneof" json:"result,omitempty"`
	// Wall-clock time the attempt ran.
	WallTime *durationpb.Duration `protobuf:"bytes,4,opt,name=wall_time,json=wallTime,proto3" json:"wall_time,omitempty"`
	// See JobFrame.lease.
	Lease         []byte `protobuf:"bytes,5,opt,name=lease,proto3,oneof" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuccessFrame) Reset() {
	*x = SuccessFrame{}
	mi := &file_flexiq_executor_v1_executor_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuccessFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessFrame) ProtoMessage() {}

func (x *SuccessFrame) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_executor_v1_executor_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessFrame.ProtoReflect.Descriptor instead.
func (*SuccessFrame) Descriptor() ([]byte, []int) {
	return file_flexiq_executor_v1_executor_service_proto_rawDescGZIP(), []int{11}
}

func (x *SuccessFrame) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SuccessFrame) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *SuccessFrame) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *SuccessFrame) GetWallTime() *durationpb.Duration {
	if x != nil {
		return x.WallTime
	}
	return nil
}

func (x *SuccessFrame) GetLease() []byte {
	if x != nil {
		return x.Lease
	}
	return nil
}

// The task raised or timed out.
type FailureFrame struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	JobId    string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	TaskName string                 `protobuf:"bytes,2,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	// Canonical JSON {errtype, message, traceback[]} when the SDK wrote one, and
	// free prose otherwise. Readers fall back on non-JSON.
	Error      string               `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	RetryCount int32                `protobuf:"varint,4,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	MaxRetries int32                `protobuf:"varint,5,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	WallTime   *durationpb.Duration `protobuf:"bytes,6,opt,name=wall_time,json=wallTime,proto3" json:"wall_time,omitempty"`
	// The executor decides: only it can see the exception, and the scheduler
	// never inspects one.
	ShouldRetry bool `protobuf:"varint,7,opt,name=should_retry,json=shouldRetry,proto3" json:"should_retry,omitempty"`
	// The failure was an execution timeout.
	TimedOut bool `protobuf:"varint,8,opt,name=timed_out,json=timedOut,proto3" json:"timed_out,omitempty"`
	// See JobFrame.lease.
	Lease         []byte `protobuf:"bytes,9,opt,name=lease,proto3,oneof" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailureFrame) Reset() {
	*x = FailureFrame{}
	mi := &file_flexiq_executor_v1_executor_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailureFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailureFrame) ProtoMessage() {}

func (x *FailureFrame) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_executor_v1_executor_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailureFrame.ProtoReflect.Descriptor instead.
func (*FailureFrame) Descriptor() ([]byte, []int) {
	return file_flexiq_executor_v1_executor_service_proto_rawDescGZIP(), []int{12}
}

func (x *FailureFrame) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *FailureFrame) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *FailureFrame) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *FailureFrame) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *FailureFrame) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *FailureFrame) GetWallTime() *durationpb.Duration {
	if x != nil {
		return x.WallTime
	}
	return nil
}

func (x *FailureFrame) GetShouldRetry() bool {
	if x != nil {
		return x.ShouldRetry
	}
	return false
}

func (x *FailureFrame) GetTimedOut() bool {
	if x != nil {
		return x.TimedOut
	}
	return false
}

func (x *FailureFrame) GetLease() []byte {
	if x != nil {
		return x.Lease
	}
	return nil
}

// The task observed its cancel request and stopped.
type CancelledFrame struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	JobId    string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	TaskName string                 `protobuf:"bytes,2,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	WallTime *durationpb.Duration   `protobuf:"bytes,3,opt,name=wall_time,json=wallTime,proto3" json:"wall_time,omitempty"`
	// See JobFrame.lease.
	Lease         []byte `protobuf:"bytes,4,opt,name=lease,proto3,oneof" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelledFrame) Reset() {
	*x = CancelledFrame{}
	mi := &file_flexiq_executor_v1_executor_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelledFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelledFrame) ProtoMessage() {}

func (x *CancelledFrame) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_executor_v1_executor_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelledFrame.ProtoReflect.Descriptor instead.
func (*CancelledFrame) Descriptor() ([]byte, []int) {
	return file_flexiq_executor_v1_executor_service_proto_rawDescGZIP(), []int{13}
}

func (x *CancelledFrame) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CancelledFrame) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *CancelledFrame) GetWallTime() *durationpb.Duration {
	if x != nil {
		return x.WallTime
	}
	return nil
}

func (x *CancelledFrame) GetLease() []byte {
	if x != nil {
		return x.Lease
	}
	return nil
}

// Commit one durable step, or one sleep, through the scheduler.
//
// The frame carries no owner, and must not. An owner an executor fills in is an
// owner it can forge, and after a reclaim a stale executor sending the current
// owner's id would write straight into the live attempt's sequence. The
// scheduler supplies both halves of the fence from the dispatch it recorded.
//
// A retransmission after a lost ack is expected and safe: the same (seq,
// step_key) and payload comes back as `already`.
type StepCommitFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	JobId string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Position in the job's step sequence, which must be exactly the number of
	// steps already committed.
	Seq int32 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	// Identity of the step within the job ("name#occurrence" or "name:key").
	StepKey string   `protobuf:"bytes,3,opt,name=step_key,json=stepKey,proto3" json:"step_key,omitempty"`
	Kind    StepKind `protobuf:"varint,4,opt,name=kind,proto3,enum=flexiq.executor.v1.StepKind" json:"kind,omitempty"`
	// The encoded result. Empty for a sleep, which commits no bytes.
	Payload []byte `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	// Candidate deadline for a sleep. A sleep row already at this position keeps
	// the deadline it was first given, which is what the ack echoes back.
	WakeAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=wake_at,json=wakeAt,proto3" json:"wake_at,omitempty"`
	// See JobFrame.lease. Not in tension with "carries no owner" above: the lease
	// is not the executor's claim of identity, it is the scheduler's own value
	// handed back, and it says which dispatch this frame belongs to.
	Lease         []byte `protobuf:"bytes,7,opt,name=lease,proto3,oneof" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepCommitFrame) Reset() {
	*x = StepCommitFrame{}
	mi := &file_flexiq_executor_v1_executor_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepCommitFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepCommitFrame) ProtoMessage() {}

func (x *StepCommitFrame) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_executor_v1_executor_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepCommitFrame.ProtoReflect.Descriptor instead.
func (*StepCommitFrame) Descriptor() ([]byte, []int) {
	return file_flexiq_executor_v1_executor_service_proto_rawDescGZIP(), []int{14}
}

func (x *StepCommitFrame) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *StepCommitFrame) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *StepCommitFrame) GetStepKey() string {
	if x != nil {
		return x.StepKey
	}
	return ""
}

func (x *StepCommitFrame) GetKind() StepKind {
	if x != nil {
		return x.Kind
	}
	return StepKind_STEP_KIND_UNSPECIFIED
}

func (x *StepCommitFrame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StepCommitFrame) GetWakeAt() *timestamppb.Timestamp {
	if x != nil {
		return x.WakeAt
	}
	return nil
}

func (x *StepCommitFrame) GetLease() []byte {
	if x != nil {
		return x.Lease
	}
	return nil
}

// The attempt ended in a sleep, and the job is already scheduled at its
// deadline. Ends the attempt like a cancel, without being a failure.
type SleptFrame struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	JobId    string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	TaskName string                 `protobuf:"bytes,2,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	// The deadline storage settled on, which on a replay is not the one proposed.
	WakeAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=wake_at,json=wakeAt,proto3" json:"wake_at,omitempty"`
	// Wall-clock time the attempt ran before it slept.
	WallTime *durationpb.Duration `protobuf:"bytes,4,opt,name=wall_time,json=wallTime,proto3" json:"wall_time,omitempty"`
	// See JobFrame.lease.
	Lease         []byte `protobuf:"bytes,5,opt,name=lease,proto3,oneof" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SleptFrame) Reset() {
	*x = SleptFrame{}
	mi := &file_flexiq_executor_v1_executor_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SleptFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SleptFrame) ProtoMessage() {}

func (x *SleptFrame) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_executor_v1_executor_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SleptFrame.ProtoReflect.Descriptor instead.
func (*SleptFrame) Descriptor() ([]byte, []int) {
	return file_flexiq_executor_v1_executor_service_proto_rawDescGZIP(), []int{15}
}

func (x *SleptFrame) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SleptFrame) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *SleptFrame) GetWakeAt() *timestamppb.Timestamp {
	if x != nil {
		return x.WakeAt
	}
	return nil
}

func (x *SleptFrame) GetWallTime() *durationpb.Duration {
	if x != nil {
		return x.WallTime
	}
	return nil
}

func (x *SleptFrame) GetLease() []byte {
	if x != nil {
		return x.Lease
	}
	return nil
}

type HeartbeatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The `flexiq-attach-session-bin` value from the Attach response's metadata.
	// Opaque, minted by the scheduler, and the only thing that says which stream
	// this heartbeat belongs to. A `-bin` key because the value is bytes; gRPC
	// base64s it on the wire and hands the raw bytes back.
	Session []byte `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	// Slots free right now. Local accounting is exact, so this may only shrink
	// the scheduler's view of free capacity, never grow it.
	FreeSlots     uint32 `protobuf:"varint,2,opt,name=free_slots,json=freeSlots,proto3" json:"free_slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_flexiq_executor_v1_executor_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_executor_v1_executor_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_flexiq_executor_v1_executor_service_proto_rawDescGZIP(), []int{16}
}

func (x *HeartbeatRequest) GetSession() []byte {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *HeartbeatRequest) GetFreeSlots() uint32 {
	if x != nil {
		return x.FreeSlots
	}
	return 0
}

// Empty today. It is a message rather than nothing so it can grow a field
// without becoming a new response type.
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_flexiq_executor_v1_executor_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_executor_v1_executor_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_flexiq_executor_v1_executor_service_proto_rawDescGZIP(), []int{17}
}

var File_flexiq_executor_v1_executor_service_proto protoreflect.FileDescriptor

const file_flexiq_executor_v1_executor_service_proto_rawDesc = "" +
	"\n" +
	")flexiq/executor/v1/executor_service.proto\x12\x12flexiq.executor.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x90\x04\n" +
	"\rAttachRequest\x126\n" +
	"\x05hello\x18\x01 \x01(\v2\x1e.flexiq.executor.v1.HelloFrameH\x00R\x05hello\x12<\n" +
	"\asuccess\x18\x02 \x01(\v2 .flexiq.executor.v1.SuccessFrameH\x00R\asuccess\x12<\n" +
	"\afailure\x18\x03 \x01(\v2 .flexiq.executor.v1.FailureFrameH\x00R\afailure\x12B\n" +
	"\tcancelled\x18\x04 \x01(\v2\".flexiq.executor.v1.CancelledFrameH\x00R\tcancelled\x126\n" +
	"\x05slept\x18\x05 \x01(\v2\x1e.flexiq.executor.v1.SleptFrameH\x00R\x05slept\x12?\n" +
	"\bprogress\x18\x06 \x01(\v2!.flexiq.executor.v1.ProgressFrameH\x00R\bprogress\x12=\n" +
	"\btask_log\x18\a \x01(\v2 .flexiq.executor.v1.TaskLogFrameH\x00R\ataskLog\x12F\n" +
	"\vstep_commit\x18\b \x01(\v2#.flexiq.executor.v1.StepCommitFrameH\x00R\n" +
	"stepCommitB\a\n" +
	"\x05frame\"\x8a\x03\n" +
	"\x0eAttachResponse\x12@\n" +
	"\thello_ack\x18\x01 \x01(\v2!.flexiq.executor.v1.HelloAckFrameH\x00R\bhelloAck\x120\n" +
	"\x03job\x18\x02 \x01(\v2\x1c.flexiq.executor.v1.JobFrameH\x00R\x03job\x12@\n" +
	"\tjob_steps\x18\x03 \x01(\v2!.flexiq.executor.v1.JobStepsFrameH\x00R\bjobSteps\x12=\n" +
	"\bstep_ack\x18\x04 \x01(\v2 .flexiq.executor.v1.StepAckFrameH\x00R\astepAck\x129\n" +
	"\x06cancel\x18\x05 \x01(\v2\x1f.flexiq.executor.v1.CancelFrameH\x00R\x06cancel\x12?\n" +
	"\bshutdown\x18\x06 \x01(\v2!.flexiq.executor.v1.ShutdownFrameH\x00R\bshutdownB\a\n" +
	"\x05frame\"\xd4\x01\n" +
	"\n" +
	"HelloFrame\x12\x1f\n" +
	"\vexecutor_id\x18\x01 \x01(\tR\n" +
	"executorId\x12\x10\n" +
	"\x03sdk\x18\x02 \x01(\tR\x03sdk\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x14\n" +
	"\x05tasks\x18\x04 \x03(\tR\x05tasks\x12\x14\n" +
	"\x05slots\x18\x05 \x01(\rR\x05slots\x12)\n" +
	"\x10protocol_version\x18\x06 \x01(\rR\x0fprotocolVersion\x12\"\n" +
	"\fcapabilities\x18\a \x03(\tR\fcapabilities\"\x81\x01\n" +
	"\rHelloAckFrame\x12!\n" +
	"\fscheduler_id\x18\x01 \x01(\tR\vschedulerId\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\rR\x0fprotocolVersion\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\"\x93\x03\n" +
	"\bJobFrame\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttask_name\x18\x02 \x01(\tR\btaskName\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1f\n" +
	"\vretry_count\x18\x04 \x01(\x05R\n" +
	"retryCount\x12\x1f\n" +
	"\vmax_retries\x18\x05 \x01(\x05R\n" +
	"maxRetries\x12\x14\n" +
	"\x05queue\x18\x06 \x01(\tR\x05queue\x123\n" +
	"\atimeout\x18\a \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12!\n" +
	"\tnamespace\x18\b \x01(\tH\x00R\tnamespace\x88\x01\x01\x12/\n" +
	"\x13disabled_middleware\x18\t \x03(\tR\x12disabledMiddleware\x12\x1f\n" +
	"\bmetadata\x18\n" +
	" \x01(\tH\x01R\bmetadata\x88\x01\x01\x12\x19\n" +
	"\x05lease\x18\v \x01(\fH\x02R\x05lease\x88\x01\x01B\f\n" +
	"\n" +
	"_namespaceB\v\n" +
	"\t_metadataB\b\n" +
	"\x06_lease\"B\n" +
	"\rJobStepsFrame\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1a\n" +
	"\bsnapshot\x18\x02 \x01(\fR\bsnapshot\"\xf6\x01\n" +
	"\fStepAckFrame\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x05R\x03seq\x12\x0e\n" +
	"\x02ok\x18\x03 \x01(\bR\x02ok\x12\x18\n" +
	"\aalready\x18\x04 \x01(\bR\aalready\x123\n" +
	"\awake_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x06wakeAt\x12\x19\n" +
	"\x05error\x18\x06 \x01(\tH\x00R\x05error\x88\x01\x01\x129\n" +
	"\afailure\x18\a \x01(\x0e2\x1f.flexiq.executor.v1.StepFailureR\afailureB\b\n" +
	"\x06_error\"$\n" +
	"\vCancelFrame\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x0f\n" +
	"\rShutdownFrame\"g\n" +
	"\rProgressFrame\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x05R\bprogress\x12\x19\n" +
	"\x05lease\x18\x03 \x01(\fH\x00R\x05lease\x88\x01\x01B\b\n" +
	"\x06_lease\"\xbc\x01\n" +
	"\fTaskLogFrame\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\ttask_name\x18\x02 \x01(\tR\btaskName\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x19\n" +
	"\x05extra\x18\x05 \x01(\fH\x00R\x05extra\x88\x01\x01\x12\x19\n" +
	"\x05lease\x18\x06 \x01(\fH\x01R\x05lease\x88\x01\x01B\b\n" +
	"\x06_extraB\b\n" +
	"\x06_lease\"\xc7\x01\n" +
	"\fSuccessFrame\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\ttask_name\x18\x02 \x01(\tR\btaskName\x12\x1b\n" +
	"\x06result\x18\x03 \x01(\fH\x00R\x06result\x88\x01\x01\x126\n" +
	"\twall_time\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\bwallTime\x12\x19\n" +
	"\x05lease\x18\x05 \x01(\fH\x01R\x05lease\x88\x01\x01B\t\n" +
	"\a_resultB\b\n" +
	"\x06_lease\"\xb7\x02\n" +
	"\fFailureFrame\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\ttask_name\x18\x02 \x01(\tR\btaskName\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1f\n" +
	"\vretry_count\x18\x04 \x01(\x05R\n" +
	"retryCount\x12\x1f\n" +
	"\vmax_retries\x18\x05 \x01(\x05R\n" +
	"maxRetries\x126\n" +
	"\twall_time\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\bwallTime\x12!\n" +
	"\fshould_retry\x18\a \x01(\bR\vshouldRetry\x12\x1b\n" +
	"\ttimed_out\x18\b \x01(\bR\btimedOut\x12\x19\n" +
	"\x05lease\x18\t \x01(\fH\x00R\x05lease\x88\x01\x01B\b\n" +
	"\x06_lease\"\xa1\x01\n" +
	"\x0eCancelledFrame\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\ttask_name\x18\x02 \x01(\tR\btaskName\x126\n" +
	"\twall_time\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\bwallTime\x12\x19\n" +
	"\x05lease\x18\x04 \x01(\fH\x00R\x05lease\x88\x01\x01B\b\n" +
	"\x06_lease\"\xfb\x01\n" +
	"\x0fStepCommitFrame\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x05R\x03seq\x12\x19\n" +
	"\bstep_key\x18\x03 \x01(\tR\astepKey\x120\n" +
	"\x04kind\x18\x04 \x01(\x0e2\x1c.flexiq.executor.v1.StepKindR\x04kind\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x123\n" +
	"\awake_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x06wakeAt\x12\x19\n" +
	"\x05lease\x18\a \x01(\fH\x00R\x05lease\x88\x01\x01B\b\n" +
	"\x06_lease\"\xd2\x01\n" +
	"\n" +
	"SleptFrame\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\ttask_name\x18\x02 \x01(\tR\btaskName\x123\n" +
	"\awake_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06wakeAt\x126\n" +
	"\twall_time\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\bwallTime\x12\x19\n" +
	"\x05lease\x18\x05 \x01(\fH\x00R\x05lease\x88\x01\x01B\b\n" +
	"\x06_lease\"K\n" +
	"\x10HeartbeatRequest\x12\x18\n" +
	"\asession\x18\x01 \x01(\fR\asession\x12\x1d\n" +
	"\n" +
	"free_slots\x18\x02 \x01(\rR\tfreeSlots\"\x13\n" +
	"\x11HeartbeatResponse*M\n" +
	"\bStepKind\x12\x19\n" +
	"\x15STEP_KIND_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTEP_KIND_RUN\x10\x01\x12\x13\n" +
	"\x0fSTEP_KIND_SLEEP\x10\x02*\x80\x01\n" +
	"\vStepFailure\x12\x1c\n" +
	"\x18STEP_FAILURE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16STEP_FAILURE_RETRYABLE\x10\x01\x12\x1a\n" +
	"\x16STEP_FAILURE_PERMANENT\x10\x02\x12\x1b\n" +
	"\x17STEP_FAILURE_SUPERSEDED\x10\x032\xc0\x01\n" +
	"\x0fExecutorService\x12S\n" +
	"\x06Attach\x12!.flexiq.executor.v1.AttachRequest\x1a\".flexiq.executor.v1.AttachResponse(\x010\x01\x12X\n" +
	"\tHeartbeat\x12$.flexiq.executor.v1.HeartbeatRequest\x1a%.flexiq.executor.v1.HeartbeatResponseB\xe9\x01\n" +
	"\x16com.flexiq.executor.v1B\x14ExecutorServiceProtoP\x01ZOgithub.com/ByteVeda/flexiq/sdks/go/v2/internal/pb/flexiq/executor/v1;executorv1\xa2\x02\x03FEX\xaa\x02\x12Flexiq.Executor.V1\xca\x02\x12Flexiq\\Executor\\V1\xe2\x02\x1eFlexiq\\Executor\\V1\\GPBMetadata\xea\x02\x14Flexiq::Executor::V1b\x06proto3"

var (
	file_flexiq_executor_v1_executor_service_proto_rawDescOnce sync.Once
	file_flexiq_executor_v1_executor_service_proto_rawDescData []byte
)

func file_flexiq_executor_v1_executor_service_proto_rawDescGZIP() []byte {
	file_flexiq_executor_v1_executor_service_proto_rawDescOnce.Do(func() {
		file_flexiq_executor_v1_executor_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flexiq_executor_v1_executor_service_proto_rawDesc), len(file_flexiq_executor_v1_executor_service_proto_rawDesc)))
	})
	return file_flexiq_executor_v1_executor_service_proto_rawDescData
}

var file_flexiq_executor_v1_executor_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_flexiq_executor_v1_executor_service_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_flexiq_executor_v1_executor_service_proto_goTypes = []any{
	(StepKind)(0),                 // 0: flexiq.executor.v1.StepKind
	(StepFailure)(0),              // 1: flexiq.executor.v1.StepFailure
	(*AttachRequest)(nil),         // 2: flexiq.executor.v1.AttachRequest
	(*AttachResponse)(nil),        // 3: flexiq.executor.v1.AttachResponse
	(*HelloFrame)(nil),            // 4: flexiq.executor.v1.HelloFrame
	(*HelloAckFrame)(nil),         // 5: flexiq.executor.v1.HelloAckFrame
	(*JobFrame)(nil),              // 6: flexiq.executor.v1.JobFrame
	(*JobStepsFrame)(nil),         // 7: flexiq.executor.v1.JobStepsFrame
	(*StepAckFrame)(nil),          // 8: flexiq.executor.v1.StepAckFrame
	(*CancelFrame)(nil),           // 9: flexiq.executor.v1.CancelFrame
	(*ShutdownFrame)(nil),         // 10: flexiq.executor.v1.ShutdownFrame
	(*ProgressFrame)(nil),         // 11: flexiq.executor.v1.ProgressFrame
	(*TaskLogFrame)(nil),          // 12: flexiq.executor.v1.TaskLogFrame
	(*SuccessFrame)(nil),          // 13: flexiq.executor.v1.SuccessFrame
	(*FailureFrame)(nil),          // 14: flexiq.executor.v1.FailureFrame
	(*CancelledFrame)(nil),        // 15: flexiq.executor.v1.CancelledFrame
	(*StepCommitFrame)(nil),       // 16: flexiq.executor.v1.StepCommitFrame
	(*SleptFrame)(nil),            // 17: flexiq.executor.v1.SleptFrame
	(*HeartbeatRequest)(nil),      // 18: flexiq.executor.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 19: flexiq.executor.v1.HeartbeatResponse
	(*durationpb.Duration)(nil),   // 20: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 21: google.protobuf.Timestamp
}
var file_flexiq_executor_v1_executor_service_proto_depIdxs = []int32{
	4,  // 0: flexiq.executor.v1.AttachRequest.hello:type_name -> flexiq.executor.v1.HelloFrame
	13, // 1: flexiq.executor.v1.AttachRequest.success:type_name -> flexiq.executor.v1.SuccessFrame
	14, // 2: flexiq.executor.v1.AttachRequest.failure:type_name -> flexiq.executor.v1.FailureFrame
	15, // 3: flexiq.executor.v1.AttachRequest.cancelled:type_name -> flexiq.executor.v1.CancelledFrame
	17, // 4: flexiq.executor.v1.AttachRequest.slept:type_name -> flexiq.executor.v1.SleptFrame
	11, // 5: flexiq.executor.v1.AttachRequest.progress:type_name -> flexiq.executor.v1.ProgressFrame
	12, // 6: flexiq.executor.v1.AttachRequest.task_log:type_name -> flexiq.executor.v1.TaskLogFrame
	16, // 7: flexiq.executor.v1.AttachRequest.step_commit:type_name -> flexiq.executor.v1.StepCommitFrame
	5,  // 8: flexiq.executor.v1.AttachResponse.hello_ack:type_name -> flexiq.executor.v1.HelloAckFrame
	6,  // 9: flexiq.executor.v1.AttachResponse.job:type_name -> flexiq.executor.v1.JobFrame
	7,  // 10: flexiq.executor.v1.AttachResponse.job_steps:type_name -> flexiq.executor.v1.JobStepsFrame
	8,  // 11: flexiq.executor.v1.AttachResponse.step_ack:type_name -> flexiq.executor.v1.StepAckFrame
	9,  // 12: flexiq.executor.v1.AttachResponse.cancel:type_name -> flexiq.executor.v1.CancelFrame
	10, // 13: flexiq.executor.v1.AttachResponse.shutdown:type_name -> flexiq.executor.v1.ShutdownFrame
	20, // 14: flexiq.executor.v1.JobFrame.timeout:type_name -> google.protobuf.Duration
	21, // 15: flexiq.executor.v1.StepAckFrame.wake_at:type_name -> google.protobuf.Timestamp
	1,  // 16: flexiq.executor.v1.StepAckFrame.failure:type_name -> flexiq.executor.v1.StepFailure
	20, // 17: flexiq.executor.v1.SuccessFrame.wall_time:type_name -> google.protobuf.Duration
	20, // 18: flexiq.executor.v1.FailureFrame.wall_time:type_name -> google.protobuf.Duration
	20, // 19: flexiq.executor.v1.CancelledFrame.wall_time:type_name -> google.protobuf.Duration
	0,  // 20: flexiq.executor.v1.StepCommitFrame.kind:type_name -> flexiq.executor.v1.StepKind
	21, // 21: flexiq.executor.v1.StepCommitFrame.wake_at:type_name -> google.protobuf.Timestamp
	21, // 22: flexiq.executor.v1.SleptFrame.wake_at:type_name -> google.protobuf.Timestamp
	20, // 23: flexiq.executor.v1.SleptFrame.wall_time:type_name -> google.protobuf.Duration
	2,  // 24: flexiq.executor.v1.ExecutorService.Attach:input_type -> flexiq.executor.v1.AttachRequest
	18, // 25: flexiq.executor.v1.ExecutorService.Heartbeat:input_type -> flexiq.executor.v1.HeartbeatRequest
	3,  // 26: flexiq.executor.v1.ExecutorService.Attach:output_type -> flexiq.executor.v1.AttachResponse
	19, // 27: flexiq.executor.v1.ExecutorService.Heartbeat:output_type -> flexiq.executor.v1.HeartbeatResponse
	26, // [26:28] is the sub-list for method output_type
	24, // [24:26] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_flexiq_executor_v1_executor_service_proto_init() }
func file_flexiq_executor_v1_executor_service_proto_init() {
	if File_flexiq_executor_v1_executor_service_proto != nil {
		return
	}
	file_flexiq_executor_v1_executor_service_proto_msgTypes[0].OneofWrappers = []any{
		(*AttachRequest_Hello)(nil),
		(*AttachRequest_Success)(nil),
		(*AttachRequest_Failure)(nil),
		(*AttachRequest_Cancelled)(nil),
		(*AttachRequest_Slept)(nil),
		(*AttachRequest_Progress)(nil),
		(*AttachRequest_TaskLog)(nil),
		(*AttachRequest_StepCommit)(nil),
	}
	file_flexiq_executor_v1_executor_service_proto_msgTypes[1].OneofWrappers = []any{
		(*AttachResponse_HelloAck)(nil),
		(*AttachResponse_Job)(nil),
		(*AttachResponse_JobSteps)(nil),
		(*AttachResponse_StepAck)(nil),
		(*AttachResponse_Cancel)(nil),
		(*AttachResponse_Shutdown)(nil),
	}
	file_flexiq_executor_v1_executor_service_proto_msgTypes[4].OneofWrappers = []any{}
	file_flexiq_executor_v1_executor_service_proto_msgTypes[6].OneofWrappers = []any{}
	file_flexiq_executor_v1_executor_service_proto_msgTypes[9].OneofWrappers = []any{}
	file_flexiq_executor_v1_executor_service_proto_msgTypes[10].OneofWrappers = []any{}
	file_flexiq_executor_v1_executor_service_proto_msgTypes[11].OneofWrappers = []any{}
	file_flexiq_executor_v1_executor_service_proto_msgTypes[12].OneofWrappers = []any{}
	file_flexiq_executor_v1_executor_service_proto_msgTypes[13].OneofWrappers = []any{}
	file_flexiq_executor_v1_executor_service_proto_msgTypes[14].OneofWrappers = []any{}
	file_flexiq_executor_v1_executor_service_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flexiq_executor_v1_executor_service_proto_rawDesc), len(file_flexiq_executor_v1_executor_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_flexiq_executor_v1_executor_service_proto_goTypes,
		DependencyIndexes: file_flexiq_executor_v1_executor_service_proto_depIdxs,
		EnumInfos:         file_flexiq_executor_v1_executor_service_proto_enumTypes,
		MessageInfos:      file_flexiq_executor_v1_executor_service_proto_msgTypes,
	}.Build()
	File_flexiq_executor_v1_executor_service_proto = out.File
	file_flexiq_executor_v1_executor_service_proto_goTypes = nil
	file_flexiq_executor_v1_executor_service_proto_depIdxs = nil
}
