// STABLE as of 2.0.0, the release that first shipped the gRPC role. Field
// numbers, field names and RPC shapes are permanent from here (§2.2 of
// tasks/specs/2026-09-01-flexiq-v1-proto-design.md): the `proto-breaking`
// label is for reverting a mistake made in the same release train, never for
// changing a shipped shape.
//
// The rules this package is held to, because a client reads the .proto and not
// the design document:
//
//   1. Field numbers are never reused and never renumbered.
//   2. Fields are deprecated in place, and on removal both the number and the
//      name are reserved — the name because JSON clients encode against it.
//   3. New RPCs, messages, fields and enum values are additive and never bump
//      the package version.
//   4. A field's meaning and units are frozen with its number.
//   5. Readers tolerate what they do not know: unknown fields, unknown enum
//      values, unknown oneof arms.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: flexiq/v1/job.proto

package flexiqv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Lifecycle state of a job.
//
// One-to-one with `JobStatus` in crates/flexiq-core/src/job.rs, but offset by
// one: the Rust discriminants start at `Pending = 0` and zero is spent here on
// `_UNSPECIFIED`. The conversion is an exhaustive match with no wildcard, so
// adding a variant on either side fails to compile rather than silently
// mapping to something wrong.
//
// A reader that does not recognise a value must treat the job as **not
// terminal** — never as failed. Only the values it knows are terminal are.
type JobStatus int32

const (
	JobStatus_JOB_STATUS_UNSPECIFIED JobStatus = 0
	// Waiting to be dequeued, or scheduled for the future.
	JobStatus_JOB_STATUS_PENDING JobStatus = 1
	// Claimed by a worker and executing.
	JobStatus_JOB_STATUS_RUNNING JobStatus = 2
	// Finished successfully.
	JobStatus_JOB_STATUS_COMPLETE JobStatus = 3
	// Failed; may still be retried.
	JobStatus_JOB_STATUS_FAILED JobStatus = 4
	// Exhausted its retries and moved to the dead-letter queue.
	JobStatus_JOB_STATUS_DEAD JobStatus = 5
	// Cancelled before or during execution.
	JobStatus_JOB_STATUS_CANCELLED JobStatus = 6
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JOB_STATUS_UNSPECIFIED",
		1: "JOB_STATUS_PENDING",
		2: "JOB_STATUS_RUNNING",
		3: "JOB_STATUS_COMPLETE",
		4: "JOB_STATUS_FAILED",
		5: "JOB_STATUS_DEAD",
		6: "JOB_STATUS_CANCELLED",
	}
	JobStatus_value = map[string]int32{
		"JOB_STATUS_UNSPECIFIED": 0,
		"JOB_STATUS_PENDING":     1,
		"JOB_STATUS_RUNNING":     2,
		"JOB_STATUS_COMPLETE":    3,
		"JOB_STATUS_FAILED":      4,
		"JOB_STATUS_DEAD":        5,
		"JOB_STATUS_CANCELLED":   6,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_flexiq_v1_job_proto_enumTypes[0].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_flexiq_v1_job_proto_enumTypes[0]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_flexiq_v1_job_proto_rawDescGZIP(), []int{0}
}

// A job, as a reader sees it.
//
// Mirrors the read model in crates/flexiq-core/src/job.rs. Numbers 1-15 encode
// in one byte and are spent on the fields every response carries; the optional
// tail starts at 16.
//
// Times are google.protobuf.Timestamp and durations are
// google.protobuf.Duration. Storage keeps Unix milliseconds, so sub-millisecond
// precision is truncated on the way in.
//
// Fields whose absence differs from their zero carry explicit presence. A
// message-typed field has presence inherently in proto3, so `optional` appears
// only on the scalars that need it.
type Job struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque. A UUIDv7 today; read it as a string, never as a UUID.
	Id       string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Queue    string    `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	TaskName string    `protobuf:"bytes,3,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	Status   JobStatus `protobuf:"varint,4,opt,name=status,proto3,enum=flexiq.v1.JobStatus" json:"status,omitempty"`
	// Higher runs first.
	Priority  int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// When the job becomes eligible to run.
	ScheduledAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	RetryCount  int32                  `protobuf:"varint,8,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	MaxRetries  int32                  `protobuf:"varint,9,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	// How long one attempt may run before the scheduler reclaims it.
	Timeout *durationpb.Duration `protobuf:"bytes,10,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// A cancel was requested while the job was running; the task polls for it.
	CancelRequested bool `protobuf:"varint,11,opt,name=cancel_requested,json=cancelRequested,proto3" json:"cancel_requested,omitempty"`
	// The job waits on at least one dependency.
	HasDeps bool `protobuf:"varint,12,opt,name=has_deps,json=hasDeps,proto3" json:"has_deps,omitempty"`
	// Output-only, and always the caller's own. It is here so a client logging a
	// job record has it, not so a client can select one — no request carries a
	// namespace.
	Namespace   string                 `protobuf:"bytes,13,opt,name=namespace,proto3" json:"namespace,omitempty"`
	StartedAt   *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	// The tagged envelope from BINDING_CONTRACT.md, opaque and never re-encoded.
	//
	// Absent means the caller did not ask for it; present and zero-length means
	// the job carries no body. They are different answers, which is why this is
	// `optional bytes` and not a bare `bytes`.
	Payload []byte `protobuf:"bytes,16,opt,name=payload,proto3,oneof" json:"payload,omitempty"`
	// The task's return value, opaque.
	//
	// Absent means the job returned nothing — or that the caller did not ask for
	// it; present and empty means it returned an empty value.
	Result []byte `protobuf:"bytes,17,opt,name=result,proto3,oneof" json:"result,omitempty"`
	// Canonical JSON `{errtype, message, traceback[]}` when whatever produced the
	// error wrote one, and free prose otherwise. Readers fall back on non-JSON.
	Error *string `protobuf:"bytes,18,opt,name=error,proto3,oneof" json:"error,omitempty"`
	// 0-100, reported by the running task.
	Progress *int32 `protobuf:"varint,19,opt,name=progress,proto3,oneof" json:"progress,omitempty"`
	// Opaque JSON text, byte-preserved. Not a Struct: a Struct round trip
	// reorders keys and cannot hold every value this field already carries.
	Metadata  *string `protobuf:"bytes,20,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	Notes     *string `protobuf:"bytes,21,opt,name=notes,proto3,oneof" json:"notes,omitempty"`
	UniqueKey *string `protobuf:"bytes,22,opt,name=unique_key,json=uniqueKey,proto3,oneof" json:"unique_key,omitempty"`
	// After this instant the job is cancelled instead of dispatched.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,23,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// How long the result is kept after completion.
	ResultTtl     *durationpb.Duration `protobuf:"bytes,24,opt,name=result_ttl,json=resultTtl,proto3" json:"result_ttl,omitempty"`
	DebounceKey   *string              `protobuf:"bytes,25,opt,name=debounce_key,json=debounceKey,proto3,oneof" json:"debounce_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_flexiq_v1_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_v1_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_flexiq_v1_job_proto_rawDescGZIP(), []int{0}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *Job) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *Job) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *Job) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Job) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Job) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

func (x *Job) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *Job) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *Job) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *Job) GetCancelRequested() bool {
	if x != nil {
		return x.CancelRequested
	}
	return false
}

func (x *Job) GetHasDeps() bool {
	if x != nil {
		return x.HasDeps
	}
	return false
}

func (x *Job) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Job) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Job) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *Job) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Job) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Job) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *Job) GetProgress() int32 {
	if x != nil && x.Progress != nil {
		return *x.Progress
	}
	return 0
}

func (x *Job) GetMetadata() string {
	if x != nil && x.Metadata != nil {
		return *x.Metadata
	}
	return ""
}

func (x *Job) GetNotes() string {
	if x != nil && x.Notes != nil {
		return *x.Notes
	}
	return ""
}

func (x *Job) GetUniqueKey() string {
	if x != nil && x.UniqueKey != nil {
		return *x.UniqueKey
	}
	return ""
}

func (x *Job) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Job) GetResultTtl() *durationpb.Duration {
	if x != nil {
		return x.ResultTtl
	}
	return nil
}

func (x *Job) GetDebounceKey() string {
	if x != nil && x.DebounceKey != nil {
		return *x.DebounceKey
	}
	return ""
}

// The producer-settable knobs on a job.
//
// Mirrors the producer-settable half of `NewJob` in
// crates/flexiq-core/src/job.rs and invents no second vocabulary for the same
// values. Two things proto3 cannot express and a client cannot guess:
//
//   - an empty `queue` means "default", substituted server-side;
//   - a higher `priority` runs first.
//
// Absent, deliberately: a namespace, which is a property of the credential and
// never of a request; and any `idempotent` flag. The `auto:` key is a sha256
// over the serialized payload and belongs to the SDKs — a client that wants one
// computes it and sends it as `unique_key`.
type EnqueueOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Empty means "default".
	Queue string `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	// Higher runs first.
	Priority int32 `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	// Attempts after the first. Zero means the job is not retried.
	MaxRetries int32 `protobuf:"varint,3,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	// Unset means "as soon as possible".
	ScheduledAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	// Unset takes the server's default.
	Timeout *durationpb.Duration `protobuf:"bytes,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// Dedupes against the **active** job carrying the same key, in the caller's
	// own namespace. It is not an idempotency key without an expiry: a retry
	// that arrives after the original finished enqueues a second job.
	UniqueKey *string `protobuf:"bytes,6,opt,name=unique_key,json=uniqueKey,proto3,oneof" json:"unique_key,omitempty"`
	// Opaque JSON text, byte-preserved (see Job.metadata).
	Metadata *string `protobuf:"bytes,7,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	Notes    *string `protobuf:"bytes,8,opt,name=notes,proto3,oneof" json:"notes,omitempty"`
	// Job ids this job waits on. An id in another namespace is refused exactly as
	// a missing one is, and reports the same reason.
	DependsOn []string `protobuf:"bytes,9,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	// After this instant the job is cancelled instead of dispatched.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// How long to keep the result after completion.
	ResultTtl *durationpb.Duration `protobuf:"bytes,11,opt,name=result_ttl,json=resultTtl,proto3" json:"result_ttl,omitempty"`
	// Present or absent: the three-of-three validation the SDKs do by hand
	// becomes a question about the message.
	Debounce      *Debounce `protobuf:"bytes,12,opt,name=debounce,proto3" json:"debounce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueOptions) Reset() {
	*x = EnqueueOptions{}
	mi := &file_flexiq_v1_job_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueOptions) ProtoMessage() {}

func (x *EnqueueOptions) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_v1_job_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueOptions.ProtoReflect.Descriptor instead.
func (*EnqueueOptions) Descriptor() ([]byte, []int) {
	return file_flexiq_v1_job_proto_rawDescGZIP(), []int{1}
}

func (x *EnqueueOptions) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *EnqueueOptions) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *EnqueueOptions) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *EnqueueOptions) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

func (x *EnqueueOptions) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *EnqueueOptions) GetUniqueKey() string {
	if x != nil && x.UniqueKey != nil {
		return *x.UniqueKey
	}
	return ""
}

func (x *EnqueueOptions) GetMetadata() string {
	if x != nil && x.Metadata != nil {
		return *x.Metadata
	}
	return ""
}

func (x *EnqueueOptions) GetNotes() string {
	if x != nil && x.Notes != nil {
		return *x.Notes
	}
	return ""
}

func (x *EnqueueOptions) GetDependsOn() []string {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

func (x *EnqueueOptions) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *EnqueueOptions) GetResultTtl() *durationpb.Duration {
	if x != nil {
		return x.ResultTtl
	}
	return nil
}

func (x *EnqueueOptions) GetDebounce() *Debounce {
	if x != nil {
		return x.Debounce
	}
	return nil
}

// Collapse a burst of enqueues carrying one key into a single run.
//
// While a job with this key is still pending and unclaimed, its scheduled time
// slides forward instead of a second job being inserted.
type Debounce struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Non-empty. Jobs sharing it share a window.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// How far ahead of now each enqueue pushes the run. Must be positive.
	Window *durationpb.Duration `protobuf:"bytes,2,opt,name=window,proto3" json:"window,omitempty"`
	// Ceiling on the total delay, measured from the pending job's creation.
	// Mandatory, and at least `window`: without it a producer that never stops
	// enqueuing starves the job forever.
	MaxWait *durationpb.Duration `protobuf:"bytes,3,opt,name=max_wait,json=maxWait,proto3" json:"max_wait,omitempty"`
	// Overwrite the pending job's payload with this one. False keeps the payload
	// the window opened with.
	ReplacePayload bool `protobuf:"varint,4,opt,name=replace_payload,json=replacePayload,proto3" json:"replace_payload,omitempty"`
	// The producer's own admission cap for the target queue, mirroring the SDK
	// app config rather than any server-side policy. Absent means uncapped, and
	// then nothing is counted. Non-negative.
	MaxPending    *int64 `protobuf:"varint,5,opt,name=max_pending,json=maxPending,proto3,oneof" json:"max_pending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Debounce) Reset() {
	*x = Debounce{}
	mi := &file_flexiq_v1_job_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Debounce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Debounce) ProtoMessage() {}

func (x *Debounce) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_v1_job_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Debounce.ProtoReflect.Descriptor instead.
func (*Debounce) Descriptor() ([]byte, []int) {
	return file_flexiq_v1_job_proto_rawDescGZIP(), []int{2}
}

func (x *Debounce) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Debounce) GetWindow() *durationpb.Duration {
	if x != nil {
		return x.Window
	}
	return nil
}

func (x *Debounce) GetMaxWait() *durationpb.Duration {
	if x != nil {
		return x.MaxWait
	}
	return nil
}

func (x *Debounce) GetReplacePayload() bool {
	if x != nil {
		return x.ReplacePayload
	}
	return false
}

func (x *Debounce) GetMaxPending() int64 {
	if x != nil && x.MaxPending != nil {
		return *x.MaxPending
	}
	return 0
}

// A call the server encodes into the payload envelope on the caller's behalf.
//
// The other arm of EnqueueRequest.body, `raw`, carries the envelope from
// BINDING_CONTRACT.md verbatim and loses nothing; it is what an SDK sends. This
// one exists so a client with no CBOR library — a shell script, `curl`, a
// language whose ecosystem has no codec — can still submit a job. The server
// encodes these values into that same envelope, so storage never holds two
// formats and a worker cannot tell which door a job arrived through.
//
// Two consequences of being JSON-shaped. Both are permanent, and neither is a
// footnote:
//
//  1. **Values JSON cannot hold are refused, not rounded.** A number here is a
//     double, so an integer is carried only up to a magnitude of 9007199254740991
//     (2^53 - 1). 2^53 is refused along with everything past it, because it is
//     also what 2^53 + 1 rounds to and no server can tell the two apart.
//     Anything beyond the range fails with INVALID_ARGUMENT rather than being
//     silently truncated, and a non-finite number is refused outright. Byte strings and CBOR tags have no Value arm at all.
//     contracts/wire-vectors.json pins exactly those cases as decode-only
//     because no JSON-shaped writer can produce them — `raw` is the door that
//     carries them.
//  2. **Object key order is not preserved.** A protobuf map is unordered, so
//     keys reach the envelope sorted. Nothing decodes differently, a CBOR map
//     being unordered too — but the bytes differ from what an SDK would have
//     sent for the same call, so an SDK's automatic `auto:` idempotency key,
//     which is a hash over those bytes, will not match across the two doors. A
//     caller that wants deduplication sets EnqueueOptions.unique_key, which is
//     the only mechanism this door has in any case.
type StructuredArgs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Positional arguments, in order.
	Args []*structpb.Value `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
	// Keyword arguments. A language with no keyword arguments sends none; the
	// envelope still carries the empty map, because the call body is always a
	// two-element array.
	Kwargs        map[string]*structpb.Value `protobuf:"bytes,2,rep,name=kwargs,proto3" json:"kwargs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StructuredArgs) Reset() {
	*x = StructuredArgs{}
	mi := &file_flexiq_v1_job_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StructuredArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructuredArgs) ProtoMessage() {}

func (x *StructuredArgs) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_v1_job_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructuredArgs.ProtoReflect.Descriptor instead.
func (*StructuredArgs) Descriptor() ([]byte, []int) {
	return file_flexiq_v1_job_proto_rawDescGZIP(), []int{3}
}

func (x *StructuredArgs) GetArgs() []*structpb.Value {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *StructuredArgs) GetKwargs() map[string]*structpb.Value {
	if x != nil {
		return x.Kwargs
	}
	return nil
}

var File_flexiq_v1_job_proto protoreflect.FileDescriptor

const file_flexiq_v1_job_proto_rawDesc = "" +
	"\n" +
	"\x13flexiq/v1/job.proto\x12\tflexiq.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbb\b\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12\x1b\n" +
	"\ttask_name\x18\x03 \x01(\tR\btaskName\x12,\n" +
	"\x06status\x18\x04 \x01(\x0e2\x14.flexiq.v1.JobStatusR\x06status\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fscheduled_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\x12\x1f\n" +
	"\vretry_count\x18\b \x01(\x05R\n" +
	"retryCount\x12\x1f\n" +
	"\vmax_retries\x18\t \x01(\x05R\n" +
	"maxRetries\x123\n" +
	"\atimeout\x18\n" +
	" \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12)\n" +
	"\x10cancel_requested\x18\v \x01(\bR\x0fcancelRequested\x12\x19\n" +
	"\bhas_deps\x18\f \x01(\bR\ahasDeps\x12\x1c\n" +
	"\tnamespace\x18\r \x01(\tR\tnamespace\x129\n" +
	"\n" +
	"started_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12\x1d\n" +
	"\apayload\x18\x10 \x01(\fH\x00R\apayload\x88\x01\x01\x12\x1b\n" +
	"\x06result\x18\x11 \x01(\fH\x01R\x06result\x88\x01\x01\x12\x19\n" +
	"\x05error\x18\x12 \x01(\tH\x02R\x05error\x88\x01\x01\x12\x1f\n" +
	"\bprogress\x18\x13 \x01(\x05H\x03R\bprogress\x88\x01\x01\x12\x1f\n" +
	"\bmetadata\x18\x14 \x01(\tH\x04R\bmetadata\x88\x01\x01\x12\x19\n" +
	"\x05notes\x18\x15 \x01(\tH\x05R\x05notes\x88\x01\x01\x12\"\n" +
	"\n" +
	"unique_key\x18\x16 \x01(\tH\x06R\tuniqueKey\x88\x01\x01\x129\n" +
	"\n" +
	"expires_at\x18\x17 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x128\n" +
	"\n" +
	"result_ttl\x18\x18 \x01(\v2\x19.google.protobuf.DurationR\tresultTtl\x12&\n" +
	"\fdebounce_key\x18\x19 \x01(\tH\aR\vdebounceKey\x88\x01\x01B\n" +
	"\n" +
	"\b_payloadB\t\n" +
	"\a_resultB\b\n" +
	"\x06_errorB\v\n" +
	"\t_progressB\v\n" +
	"\t_metadataB\b\n" +
	"\x06_notesB\r\n" +
	"\v_unique_keyB\x0f\n" +
	"\r_debounce_key\"\xa2\x04\n" +
	"\x0eEnqueueOptions\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\x05R\bpriority\x12\x1f\n" +
	"\vmax_retries\x18\x03 \x01(\x05R\n" +
	"maxRetries\x12=\n" +
	"\fscheduled_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\x123\n" +
	"\atimeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\"\n" +
	"\n" +
	"unique_key\x18\x06 \x01(\tH\x00R\tuniqueKey\x88\x01\x01\x12\x1f\n" +
	"\bmetadata\x18\a \x01(\tH\x01R\bmetadata\x88\x01\x01\x12\x19\n" +
	"\x05notes\x18\b \x01(\tH\x02R\x05notes\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"depends_on\x18\t \x03(\tR\tdependsOn\x129\n" +
	"\n" +
	"expires_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x128\n" +
	"\n" +
	"result_ttl\x18\v \x01(\v2\x19.google.protobuf.DurationR\tresultTtl\x12/\n" +
	"\bdebounce\x18\f \x01(\v2\x13.flexiq.v1.DebounceR\bdebounceB\r\n" +
	"\v_unique_keyB\v\n" +
	"\t_metadataB\b\n" +
	"\x06_notes\"\xe4\x01\n" +
	"\bDebounce\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x06window\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x06window\x124\n" +
	"\bmax_wait\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\amaxWait\x12'\n" +
	"\x0freplace_payload\x18\x04 \x01(\bR\x0ereplacePayload\x12$\n" +
	"\vmax_pending\x18\x05 \x01(\x03H\x00R\n" +
	"maxPending\x88\x01\x01B\x0e\n" +
	"\f_max_pending\"\xce\x01\n" +
	"\x0eStructuredArgs\x12*\n" +
	"\x04args\x18\x01 \x03(\v2\x16.google.protobuf.ValueR\x04args\x12=\n" +
	"\x06kwargs\x18\x02 \x03(\v2%.flexiq.v1.StructuredArgs.KwargsEntryR\x06kwargs\x1aQ\n" +
	"\vKwargsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01*\xb6\x01\n" +
	"\tJobStatus\x12\x1a\n" +
	"\x16JOB_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12JOB_STATUS_PENDING\x10\x01\x12\x16\n" +
	"\x12JOB_STATUS_RUNNING\x10\x02\x12\x17\n" +
	"\x13JOB_STATUS_COMPLETE\x10\x03\x12\x15\n" +
	"\x11JOB_STATUS_FAILED\x10\x04\x12\x13\n" +
	"\x0fJOB_STATUS_DEAD\x10\x05\x12\x18\n" +
	"\x14JOB_STATUS_CANCELLED\x10\x06B\xa4\x01\n" +
	"\rcom.flexiq.v1B\bJobProtoP\x01ZDgithub.com/ByteVeda/flexiq/sdks/go/v2/internal/pb/flexiq/v1;flexiqv1\xa2\x02\x03FXX\xaa\x02\tFlexiq.V1\xca\x02\tFlexiq\\V1\xe2\x02\x15Flexiq\\V1\\GPBMetadata\xea\x02\n" +
	"Flexiq::V1b\x06proto3"

var (
	file_flexiq_v1_job_proto_rawDescOnce sync.Once
	file_flexiq_v1_job_proto_rawDescData []byte
)

func file_flexiq_v1_job_proto_rawDescGZIP() []byte {
	file_flexiq_v1_job_proto_rawDescOnce.Do(func() {
		file_flexiq_v1_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flexiq_v1_job_proto_rawDesc), len(file_flexiq_v1_job_proto_rawDesc)))
	})
	return file_flexiq_v1_job_proto_rawDescData
}

var file_flexiq_v1_job_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_flexiq_v1_job_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_flexiq_v1_job_proto_goTypes = []any{
	(JobStatus)(0),                // 0: flexiq.v1.JobStatus
	(*Job)(nil),                   // 1: flexiq.v1.Job
	(*EnqueueOptions)(nil),        // 2: flexiq.v1.EnqueueOptions
	(*Debounce)(nil),              // 3: flexiq.v1.Debounce
	(*StructuredArgs)(nil),        // 4: flexiq.v1.StructuredArgs
	nil,                           // 5: flexiq.v1.StructuredArgs.KwargsEntry
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 7: google.protobuf.Duration
	(*structpb.Value)(nil),        // 8: google.protobuf.Value
}
var file_flexiq_v1_job_proto_depIdxs = []int32{
	0,  // 0: flexiq.v1.Job.status:type_name -> flexiq.v1.JobStatus
	6,  // 1: flexiq.v1.Job.created_at:type_name -> google.protobuf.Timestamp
	6,  // 2: flexiq.v1.Job.scheduled_at:type_name -> google.protobuf.Timestamp
	7,  // 3: flexiq.v1.Job.timeout:type_name -> google.protobuf.Duration
	6,  // 4: flexiq.v1.Job.started_at:type_name -> google.protobuf.Timestamp
	6,  // 5: flexiq.v1.Job.completed_at:type_name -> google.protobuf.Timestamp
	6,  // 6: flexiq.v1.Job.expires_at:type_name -> google.protobuf.Timestamp
	7,  // 7: flexiq.v1.Job.result_ttl:type_name -> google.protobuf.Duration
	6,  // 8: flexiq.v1.EnqueueOptions.scheduled_at:type_name -> google.protobuf.Timestamp
	7,  // 9: flexiq.v1.EnqueueOptions.timeout:type_name -> google.protobuf.Duration
	6,  // 10: flexiq.v1.EnqueueOptions.expires_at:type_name -> google.protobuf.Timestamp
	7,  // 11: flexiq.v1.EnqueueOptions.result_ttl:type_name -> google.protobuf.Duration
	3,  // 12: flexiq.v1.EnqueueOptions.debounce:type_name -> flexiq.v1.Debounce
	7,  // 13: flexiq.v1.Debounce.window:type_name -> google.protobuf.Duration
	7,  // 14: flexiq.v1.Debounce.max_wait:type_name -> google.protobuf.Duration
	8,  // 15: flexiq.v1.StructuredArgs.args:type_name -> google.protobuf.Value
	5,  // 16: flexiq.v1.StructuredArgs.kwargs:type_name -> flexiq.v1.StructuredArgs.KwargsEntry
	8,  // 17: flexiq.v1.StructuredArgs.KwargsEntry.value:type_name -> google.protobuf.Value
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_flexiq_v1_job_proto_init() }
func file_flexiq_v1_job_proto_init() {
	if File_flexiq_v1_job_proto != nil {
		return
	}
	file_flexiq_v1_job_proto_msgTypes[0].OneofWrappers = []any{}
	file_flexiq_v1_job_proto_msgTypes[1].OneofWrappers = []any{}
	file_flexiq_v1_job_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flexiq_v1_job_proto_rawDesc), len(file_flexiq_v1_job_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_flexiq_v1_job_proto_goTypes,
		DependencyIndexes: file_flexiq_v1_job_proto_depIdxs,
		EnumInfos:         file_flexiq_v1_job_proto_enumTypes,
		MessageInfos:      file_flexiq_v1_job_proto_msgTypes,
	}.Build()
	File_flexiq_v1_job_proto = out.File
	file_flexiq_v1_job_proto_goTypes = nil
	file_flexiq_v1_job_proto_depIdxs = nil
}
