// STABLE as of 2.0.0, the release that first shipped the gRPC role. Field
// numbers, field names and RPC shapes are permanent from here (§2.2 of
// tasks/specs/2026-09-01-flexiq-v1-proto-design.md): the `proto-breaking`
// label is for reverting a mistake made in the same release train, never for
// changing a shipped shape.
//
// The rules this package is held to are stated in full in job.proto, because a
// client reads the .proto and not the design document.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: flexiq/v1/producer_service.proto

package flexiqv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnqueueRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The registered task to run. Not validated here; see the service comment.
	TaskName string `protobuf:"bytes,1,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	// The job's body.
	//
	// Setting no arm is an error: an absent body is not an empty one, and
	// `raw = ""` is a zero-length payload.
	//
	// Both arms end up as the same envelope in storage. They differ in what they
	// can express: `raw` carries anything the format does, `structured` carries
	// what JSON does. Pick `raw` if you have a CBOR library.
	//
	// Types that are valid to be assigned to Body:
	//
	//	*EnqueueRequest_Raw
	//	*EnqueueRequest_Structured
	Body          isEnqueueRequest_Body `protobuf_oneof:"body"`
	Options       *EnqueueOptions       `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueRequest) Reset() {
	*x = EnqueueRequest{}
	mi := &file_flexiq_v1_producer_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueRequest) ProtoMessage() {}

func (x *EnqueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_v1_producer_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueRequest.ProtoReflect.Descriptor instead.
func (*EnqueueRequest) Descriptor() ([]byte, []int) {
	return file_flexiq_v1_producer_service_proto_rawDescGZIP(), []int{0}
}

func (x *EnqueueRequest) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *EnqueueRequest) GetBody() isEnqueueRequest_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *EnqueueRequest) GetRaw() []byte {
	if x != nil {
		if x, ok := x.Body.(*EnqueueRequest_Raw); ok {
			return x.Raw
		}
	}
	return nil
}

func (x *EnqueueRequest) GetStructured() *StructuredArgs {
	if x != nil {
		if x, ok := x.Body.(*EnqueueRequest_Structured); ok {
			return x.Structured
		}
	}
	return nil
}

func (x *EnqueueRequest) GetOptions() *EnqueueOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type isEnqueueRequest_Body interface {
	isEnqueueRequest_Body()
}

type EnqueueRequest_Raw struct {
	// The tagged envelope from BINDING_CONTRACT.md — one tag byte followed by
	// CBOR [args, kwargs]. Reaches storage untouched.
	Raw []byte `protobuf:"bytes,2,opt,name=raw,proto3,oneof"`
}

type EnqueueRequest_Structured struct {
	// Arguments the server encodes into that same envelope. Refuses the values
	// it cannot encode losslessly rather than rounding them, and does not
	// preserve object key order — see StructuredArgs.
	Structured *StructuredArgs `protobuf:"bytes,3,opt,name=structured,proto3,oneof"`
}

func (*EnqueueRequest_Raw) isEnqueueRequest_Body() {}

func (*EnqueueRequest_Structured) isEnqueueRequest_Body() {}

type EnqueueResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Job   *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	// The unique_key matched a job that was already active, and this is that job
	// rather than a new one.
	//
	// Every other response field describes resulting state rather than what the
	// call did. This one is the exception, because it is the whole reason a
	// producer sets a unique_key: without it the two calls are indistinguishable.
	Deduplicated  bool `protobuf:"varint,2,opt,name=deduplicated,proto3" json:"deduplicated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueResponse) Reset() {
	*x = EnqueueResponse{}
	mi := &file_flexiq_v1_producer_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueResponse) ProtoMessage() {}

func (x *EnqueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_v1_producer_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueResponse.ProtoReflect.Descriptor instead.
func (*EnqueueResponse) Descriptor() ([]byte, []int) {
	return file_flexiq_v1_producer_service_proto_rawDescGZIP(), []int{1}
}

func (x *EnqueueResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

func (x *EnqueueResponse) GetDeduplicated() bool {
	if x != nil {
		return x.Deduplicated
	}
	return false
}

type EnqueueBatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The same shape one Enqueue takes, so a client's single-enqueue handling
	// works unchanged per item.
	Items         []*EnqueueRequest `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueBatchRequest) Reset() {
	*x = EnqueueBatchRequest{}
	mi := &file_flexiq_v1_producer_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueBatchRequest) ProtoMessage() {}

func (x *EnqueueBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_v1_producer_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueBatchRequest.ProtoReflect.Descriptor instead.
func (*EnqueueBatchRequest) Descriptor() ([]byte, []int) {
	return file_flexiq_v1_producer_service_proto_rawDescGZIP(), []int{2}
}

func (x *EnqueueBatchRequest) GetItems() []*EnqueueRequest {
	if x != nil {
		return x.Items
	}
	return nil
}

type EnqueueBatchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One result per input item, in input order.
	//
	// **No atomicity is promised**, because not every backend can keep such a
	// promise. Where a batch is one transaction, an item failure fails the whole
	// RPC — returning earlier items as enqueued would report jobs that do not
	// exist — and the error carries the failing item's `index`. Where a batch can
	// partially apply, the RPC succeeds and an `error` arm means that item alone
	// did not land. Treating an `enqueued` arm as durable is correct under both.
	Results       []*EnqueueBatchItemResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueBatchResponse) Reset() {
	*x = EnqueueBatchResponse{}
	mi := &file_flexiq_v1_producer_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueBatchResponse) ProtoMessage() {}

func (x *EnqueueBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_v1_producer_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueBatchResponse.ProtoReflect.Descriptor instead.
func (*EnqueueBatchResponse) Descriptor() ([]byte, []int) {
	return file_flexiq_v1_producer_service_proto_rawDescGZIP(), []int{3}
}

func (x *EnqueueBatchResponse) GetResults() []*EnqueueBatchItemResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type EnqueueBatchItemResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Outcome:
	//
	//	*EnqueueBatchItemResult_Enqueued
	//	*EnqueueBatchItemResult_Error
	Outcome       isEnqueueBatchItemResult_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueBatchItemResult) Reset() {
	*x = EnqueueBatchItemResult{}
	mi := &file_flexiq_v1_producer_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueBatchItemResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueBatchItemResult) ProtoMessage() {}

func (x *EnqueueBatchItemResult) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_v1_producer_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueBatchItemResult.ProtoReflect.Descriptor instead.
func (*EnqueueBatchItemResult) Descriptor() ([]byte, []int) {
	return file_flexiq_v1_producer_service_proto_rawDescGZIP(), []int{4}
}

func (x *EnqueueBatchItemResult) GetOutcome() isEnqueueBatchItemResult_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *EnqueueBatchItemResult) GetEnqueued() *EnqueueResponse {
	if x != nil {
		if x, ok := x.Outcome.(*EnqueueBatchItemResult_Enqueued); ok {
			return x.Enqueued
		}
	}
	return nil
}

func (x *EnqueueBatchItemResult) GetError() *status.Status {
	if x != nil {
		if x, ok := x.Outcome.(*EnqueueBatchItemResult_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isEnqueueBatchItemResult_Outcome interface {
	isEnqueueBatchItemResult_Outcome()
}

type EnqueueBatchItemResult_Enqueued struct {
	// Exactly what Enqueue answers, deduplicated included.
	Enqueued *EnqueueResponse `protobuf:"bytes,1,opt,name=enqueued,proto3,oneof"`
}

type EnqueueBatchItemResult_Error struct {
	// This item alone did not land.
	Error *status.Status `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*EnqueueBatchItemResult_Enqueued) isEnqueueBatchItemResult_Outcome() {}

func (*EnqueueBatchItemResult_Error) isEnqueueBatchItemResult_Outcome() {}

type GetJobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	JobId string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Send Job.payload back. Off by default: a payload is the largest thing a job
	// carries and most readers do not want it.
	IncludePayload bool `protobuf:"varint,2,opt,name=include_payload,json=includePayload,proto3" json:"include_payload,omitempty"`
	// Send Job.result back.
	IncludeResult bool `protobuf:"varint,3,opt,name=include_result,json=includeResult,proto3" json:"include_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_flexiq_v1_producer_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_v1_producer_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_flexiq_v1_producer_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetJobRequest) GetIncludePayload() bool {
	if x != nil {
		return x.IncludePayload
	}
	return false
}

func (x *GetJobRequest) GetIncludeResult() bool {
	if x != nil {
		return x.IncludeResult
	}
	return false
}

type GetJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobResponse) Reset() {
	*x = GetJobResponse{}
	mi := &file_flexiq_v1_producer_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResponse) ProtoMessage() {}

func (x *GetJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_v1_producer_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResponse.ProtoReflect.Descriptor instead.
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return file_flexiq_v1_producer_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type ListJobsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unset lists every status.
	Status *JobStatus `protobuf:"varint,1,opt,name=status,proto3,enum=flexiq.v1.JobStatus,oneof" json:"status,omitempty"`
	// Unset lists every queue.
	Queue *string `protobuf:"bytes,2,opt,name=queue,proto3,oneof" json:"queue,omitempty"`
	// Unset lists every task.
	TaskName *string `protobuf:"bytes,3,opt,name=task_name,json=taskName,proto3,oneof" json:"task_name,omitempty"`
	// Rows per page. Zero takes the server's default; the server may return
	// fewer, and may cap a large value.
	PageSize int32 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// The previous response's next_page_token. Opaque: its contents are free to
	// change between backends and between releases, so a client passes it back
	// and interprets nothing.
	PageToken     string `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_flexiq_v1_producer_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_v1_producer_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_flexiq_v1_producer_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListJobsRequest) GetStatus() JobStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *ListJobsRequest) GetQueue() string {
	if x != nil && x.Queue != nil {
		return *x.Queue
	}
	return ""
}

func (x *ListJobsRequest) GetTaskName() string {
	if x != nil && x.TaskName != nil {
		return *x.TaskName
	}
	return ""
}

func (x *ListJobsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListJobsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListJobsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Newest first. Rows never carry payload or result — a page of a hundred jobs
	// would otherwise be a page of a hundred payloads. Read one with GetJob.
	Jobs []*Job `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	// Empty when this is the last page.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_flexiq_v1_producer_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_v1_producer_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_flexiq_v1_producer_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListJobsResponse) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ListJobsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CancelJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobRequest) Reset() {
	*x = CancelJobRequest{}
	mi := &file_flexiq_v1_producer_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobRequest) ProtoMessage() {}

func (x *CancelJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_v1_producer_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobRequest.ProtoReflect.Descriptor instead.
func (*CancelJobRequest) Descriptor() ([]byte, []int) {
	return file_flexiq_v1_producer_service_proto_rawDescGZIP(), []int{9}
}

func (x *CancelJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type CancelJobResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The job as it stands after the call, carrying neither payload nor result.
	//
	// A pending job is CANCELLED outright. A running one cannot be stopped from
	// outside, so it comes back RUNNING with cancel_requested set and the task
	// stops at its next check. A job already in a terminal state comes back
	// unchanged, which is what makes calling this twice safe.
	Job           *Job `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobResponse) Reset() {
	*x = CancelJobResponse{}
	mi := &file_flexiq_v1_producer_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobResponse) ProtoMessage() {}

func (x *CancelJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_v1_producer_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobResponse.ProtoReflect.Descriptor instead.
func (*CancelJobResponse) Descriptor() ([]byte, []int) {
	return file_flexiq_v1_producer_service_proto_rawDescGZIP(), []int{10}
}

func (x *CancelJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type QueueStatsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Which queue to count. A request that does not name one counts every queue
	// in the namespace; the queue-scoped path always names one.
	Queue         *string `protobuf:"bytes,1,opt,name=queue,proto3,oneof" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueStatsRequest) Reset() {
	*x = QueueStatsRequest{}
	mi := &file_flexiq_v1_producer_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStatsRequest) ProtoMessage() {}

func (x *QueueStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_v1_producer_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStatsRequest.ProtoReflect.Descriptor instead.
func (*QueueStatsRequest) Descriptor() ([]byte, []int) {
	return file_flexiq_v1_producer_service_proto_rawDescGZIP(), []int{11}
}

func (x *QueueStatsRequest) GetQueue() string {
	if x != nil && x.Queue != nil {
		return *x.Queue
	}
	return ""
}

type QueueStatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Waiting to run.
	Pending int64 `protobuf:"varint,1,opt,name=pending,proto3" json:"pending,omitempty"`
	// Currently executing.
	Running int64 `protobuf:"varint,2,opt,name=running,proto3" json:"running,omitempty"`
	// Finished successfully.
	Completed int64 `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	// Failed terminally.
	Failed int64 `protobuf:"varint,4,opt,name=failed,proto3" json:"failed,omitempty"`
	// Moved to the dead-letter queue.
	Dead int64 `protobuf:"varint,5,opt,name=dead,proto3" json:"dead,omitempty"`
	// Cancelled.
	Cancelled     int64 `protobuf:"varint,6,opt,name=cancelled,proto3" json:"cancelled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueStatsResponse) Reset() {
	*x = QueueStatsResponse{}
	mi := &file_flexiq_v1_producer_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStatsResponse) ProtoMessage() {}

func (x *QueueStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_v1_producer_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStatsResponse.ProtoReflect.Descriptor instead.
func (*QueueStatsResponse) Descriptor() ([]byte, []int) {
	return file_flexiq_v1_producer_service_proto_rawDescGZIP(), []int{12}
}

func (x *QueueStatsResponse) GetPending() int64 {
	if x != nil {
		return x.Pending
	}
	return 0
}

func (x *QueueStatsResponse) GetRunning() int64 {
	if x != nil {
		return x.Running
	}
	return 0
}

func (x *QueueStatsResponse) GetCompleted() int64 {
	if x != nil {
		return x.Completed
	}
	return 0
}

func (x *QueueStatsResponse) GetFailed() int64 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *QueueStatsResponse) GetDead() int64 {
	if x != nil {
		return x.Dead
	}
	return 0
}

func (x *QueueStatsResponse) GetCancelled() int64 {
	if x != nil {
		return x.Cancelled
	}
	return 0
}

var File_flexiq_v1_producer_service_proto protoreflect.FileDescriptor

const file_flexiq_v1_producer_service_proto_rawDesc = "" +
	"\n" +
	" flexiq/v1/producer_service.proto\x12\tflexiq.v1\x1a\x13flexiq/v1/job.proto\x1a\x18flexiq/v1/workflow.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x17google/rpc/status.proto\"\xbb\x01\n" +
	"\x0eEnqueueRequest\x12\x1b\n" +
	"\ttask_name\x18\x01 \x01(\tR\btaskName\x12\x12\n" +
	"\x03raw\x18\x02 \x01(\fH\x00R\x03raw\x12;\n" +
	"\n" +
	"structured\x18\x03 \x01(\v2\x19.flexiq.v1.StructuredArgsH\x00R\n" +
	"structured\x123\n" +
	"\aoptions\x18\x04 \x01(\v2\x19.flexiq.v1.EnqueueOptionsR\aoptionsB\x06\n" +
	"\x04body\"W\n" +
	"\x0fEnqueueResponse\x12 \n" +
	"\x03job\x18\x01 \x01(\v2\x0e.flexiq.v1.JobR\x03job\x12\"\n" +
	"\fdeduplicated\x18\x02 \x01(\bR\fdeduplicated\"F\n" +
	"\x13EnqueueBatchRequest\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.flexiq.v1.EnqueueRequestR\x05items\"S\n" +
	"\x14EnqueueBatchResponse\x12;\n" +
	"\aresults\x18\x01 \x03(\v2!.flexiq.v1.EnqueueBatchItemResultR\aresults\"\x89\x01\n" +
	"\x16EnqueueBatchItemResult\x128\n" +
	"\benqueued\x18\x01 \x01(\v2\x1a.flexiq.v1.EnqueueResponseH\x00R\benqueued\x12*\n" +
	"\x05error\x18\x02 \x01(\v2\x12.google.rpc.StatusH\x00R\x05errorB\t\n" +
	"\aoutcome\"v\n" +
	"\rGetJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12'\n" +
	"\x0finclude_payload\x18\x02 \x01(\bR\x0eincludePayload\x12%\n" +
	"\x0einclude_result\x18\x03 \x01(\bR\rincludeResult\"2\n" +
	"\x0eGetJobResponse\x12 \n" +
	"\x03job\x18\x01 \x01(\v2\x0e.flexiq.v1.JobR\x03job\"\xe0\x01\n" +
	"\x0fListJobsRequest\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x14.flexiq.v1.JobStatusH\x00R\x06status\x88\x01\x01\x12\x19\n" +
	"\x05queue\x18\x02 \x01(\tH\x01R\x05queue\x88\x01\x01\x12 \n" +
	"\ttask_name\x18\x03 \x01(\tH\x02R\btaskName\x88\x01\x01\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageTokenB\t\n" +
	"\a_statusB\b\n" +
	"\x06_queueB\f\n" +
	"\n" +
	"_task_name\"^\n" +
	"\x10ListJobsResponse\x12\"\n" +
	"\x04jobs\x18\x01 \x03(\v2\x0e.flexiq.v1.JobR\x04jobs\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\")\n" +
	"\x10CancelJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"5\n" +
	"\x11CancelJobResponse\x12 \n" +
	"\x03job\x18\x01 \x01(\v2\x0e.flexiq.v1.JobR\x03job\"8\n" +
	"\x11QueueStatsRequest\x12\x19\n" +
	"\x05queue\x18\x01 \x01(\tH\x00R\x05queue\x88\x01\x01B\b\n" +
	"\x06_queue\"\xb0\x01\n" +
	"\x12QueueStatsResponse\x12\x18\n" +
	"\apending\x18\x01 \x01(\x03R\apending\x12\x18\n" +
	"\arunning\x18\x02 \x01(\x03R\arunning\x12\x1c\n" +
	"\tcompleted\x18\x03 \x01(\x03R\tcompleted\x12\x16\n" +
	"\x06failed\x18\x04 \x01(\x03R\x06failed\x12\x12\n" +
	"\x04dead\x18\x05 \x01(\x03R\x04dead\x12\x1c\n" +
	"\tcancelled\x18\x06 \x01(\x03R\tcancelled2\xe7\x06\n" +
	"\x0fProducerService\x12U\n" +
	"\aEnqueue\x12\x19.flexiq.v1.EnqueueRequest\x1a\x1a.flexiq.v1.EnqueueResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/jobs\x12q\n" +
	"\fEnqueueBatch\x12\x1e.flexiq.v1.EnqueueBatchRequest\x1a\x1f.flexiq.v1.EnqueueBatchResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/jobs:batchEnqueue\x12[\n" +
	"\x06GetJob\x12\x18.flexiq.v1.GetJobRequest\x1a\x19.flexiq.v1.GetJobResponse\"\x1c\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/jobs/{job_id}\x90\x02\x01\x12X\n" +
	"\bListJobs\x12\x1a.flexiq.v1.ListJobsRequest\x1a\x1b.flexiq.v1.ListJobsResponse\"\x13\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/v1/jobs\x90\x02\x01\x12k\n" +
	"\tCancelJob\x12\x1b.flexiq.v1.CancelJobRequest\x1a\x1c.flexiq.v1.CancelJobResponse\"#\x82\xd3\xe4\x93\x02\x1a\"\x18/v1/jobs/{job_id}:cancel\x90\x02\x02\x12{\n" +
	"\n" +
	"QueueStats\x12\x1c.flexiq.v1.QueueStatsRequest\x1a\x1d.flexiq.v1.QueueStatsResponse\"0\x82\xd3\xe4\x93\x02'Z\v\x12\t/v1/stats\x12\x18/v1/queues/{queue}/stats\x90\x02\x01\x12o\n" +
	"\x0eSubmitWorkflow\x12 .flexiq.v1.SubmitWorkflowRequest\x1a!.flexiq.v1.SubmitWorkflowResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/workflows\x12x\n" +
	"\x0eGetWorkflowRun\x12 .flexiq.v1.GetWorkflowRunRequest\x1a!.flexiq.v1.GetWorkflowRunResponse\"!\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/workflows/{run_id}\x90\x02\x01B\xb0\x01\n" +
	"\rcom.flexiq.v1B\x14ProducerServiceProtoP\x01ZDgithub.com/ByteVeda/flexiq/sdks/go/v2/internal/pb/flexiq/v1;flexiqv1\xa2\x02\x03FXX\xaa\x02\tFlexiq.V1\xca\x02\tFlexiq\\V1\xe2\x02\x15Flexiq\\V1\\GPBMetadata\xea\x02\n" +
	"Flexiq::V1b\x06proto3"

var (
	file_flexiq_v1_producer_service_proto_rawDescOnce sync.Once
	file_flexiq_v1_producer_service_proto_rawDescData []byte
)

func file_flexiq_v1_producer_service_proto_rawDescGZIP() []byte {
	file_flexiq_v1_producer_service_proto_rawDescOnce.Do(func() {
		file_flexiq_v1_producer_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flexiq_v1_producer_service_proto_rawDesc), len(file_flexiq_v1_producer_service_proto_rawDesc)))
	})
	return file_flexiq_v1_producer_service_proto_rawDescData
}

var file_flexiq_v1_producer_service_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_flexiq_v1_producer_service_proto_goTypes = []any{
	(*EnqueueRequest)(nil),         // 0: flexiq.v1.EnqueueRequest
	(*EnqueueResponse)(nil),        // 1: flexiq.v1.EnqueueResponse
	(*EnqueueBatchRequest)(nil),    // 2: flexiq.v1.EnqueueBatchRequest
	(*EnqueueBatchResponse)(nil),   // 3: flexiq.v1.EnqueueBatchResponse
	(*EnqueueBatchItemResult)(nil), // 4: flexiq.v1.EnqueueBatchItemResult
	(*GetJobRequest)(nil),          // 5: flexiq.v1.GetJobRequest
	(*GetJobResponse)(nil),         // 6: flexiq.v1.GetJobResponse
	(*ListJobsRequest)(nil),        // 7: flexiq.v1.ListJobsRequest
	(*ListJobsResponse)(nil),       // 8: flexiq.v1.ListJobsResponse
	(*CancelJobRequest)(nil),       // 9: flexiq.v1.CancelJobRequest
	(*CancelJobResponse)(nil),      // 10: flexiq.v1.CancelJobResponse
	(*QueueStatsRequest)(nil),      // 11: flexiq.v1.QueueStatsRequest
	(*QueueStatsResponse)(nil),     // 12: flexiq.v1.QueueStatsResponse
	(*StructuredArgs)(nil),         // 13: flexiq.v1.StructuredArgs
	(*EnqueueOptions)(nil),         // 14: flexiq.v1.EnqueueOptions
	(*Job)(nil),                    // 15: flexiq.v1.Job
	(*status.Status)(nil),          // 16: google.rpc.Status
	(JobStatus)(0),                 // 17: flexiq.v1.JobStatus
	(*SubmitWorkflowRequest)(nil),  // 18: flexiq.v1.SubmitWorkflowRequest
	(*GetWorkflowRunRequest)(nil),  // 19: flexiq.v1.GetWorkflowRunRequest
	(*SubmitWorkflowResponse)(nil), // 20: flexiq.v1.SubmitWorkflowResponse
	(*GetWorkflowRunResponse)(nil), // 21: flexiq.v1.GetWorkflowRunResponse
}
var file_flexiq_v1_producer_service_proto_depIdxs = []int32{
	13, // 0: flexiq.v1.EnqueueRequest.structured:type_name -> flexiq.v1.StructuredArgs
	14, // 1: flexiq.v1.EnqueueRequest.options:type_name -> flexiq.v1.EnqueueOptions
	15, // 2: flexiq.v1.EnqueueResponse.job:type_name -> flexiq.v1.Job
	0,  // 3: flexiq.v1.EnqueueBatchRequest.items:type_name -> flexiq.v1.EnqueueRequest
	4,  // 4: flexiq.v1.EnqueueBatchResponse.results:type_name -> flexiq.v1.EnqueueBatchItemResult
	1,  // 5: flexiq.v1.EnqueueBatchItemResult.enqueued:type_name -> flexiq.v1.EnqueueResponse
	16, // 6: flexiq.v1.EnqueueBatchItemResult.error:type_name -> google.rpc.Status
	15, // 7: flexiq.v1.GetJobResponse.job:type_name -> flexiq.v1.Job
	17, // 8: flexiq.v1.ListJobsRequest.status:type_name -> flexiq.v1.JobStatus
	15, // 9: flexiq.v1.ListJobsResponse.jobs:type_name -> flexiq.v1.Job
	15, // 10: flexiq.v1.CancelJobResponse.job:type_name -> flexiq.v1.Job
	0,  // 11: flexiq.v1.ProducerService.Enqueue:input_type -> flexiq.v1.EnqueueRequest
	2,  // 12: flexiq.v1.ProducerService.EnqueueBatch:input_type -> flexiq.v1.EnqueueBatchRequest
	5,  // 13: flexiq.v1.ProducerService.GetJob:input_type -> flexiq.v1.GetJobRequest
	7,  // 14: flexiq.v1.ProducerService.ListJobs:input_type -> flexiq.v1.ListJobsRequest
	9,  // 15: flexiq.v1.ProducerService.CancelJob:input_type -> flexiq.v1.CancelJobRequest
	11, // 16: flexiq.v1.ProducerService.QueueStats:input_type -> flexiq.v1.QueueStatsRequest
	18, // 17: flexiq.v1.ProducerService.SubmitWorkflow:input_type -> flexiq.v1.SubmitWorkflowRequest
	19, // 18: flexiq.v1.ProducerService.GetWorkflowRun:input_type -> flexiq.v1.GetWorkflowRunRequest
	1,  // 19: flexiq.v1.ProducerService.Enqueue:output_type -> flexiq.v1.EnqueueResponse
	3,  // 20: flexiq.v1.ProducerService.EnqueueBatch:output_type -> flexiq.v1.EnqueueBatchResponse
	6,  // 21: flexiq.v1.ProducerService.GetJob:output_type -> flexiq.v1.GetJobResponse
	8,  // 22: flexiq.v1.ProducerService.ListJobs:output_type -> flexiq.v1.ListJobsResponse
	10, // 23: flexiq.v1.ProducerService.CancelJob:output_type -> flexiq.v1.CancelJobResponse
	12, // 24: flexiq.v1.ProducerService.QueueStats:output_type -> flexiq.v1.QueueStatsResponse
	20, // 25: flexiq.v1.ProducerService.SubmitWorkflow:output_type -> flexiq.v1.SubmitWorkflowResponse
	21, // 26: flexiq.v1.ProducerService.GetWorkflowRun:output_type -> flexiq.v1.GetWorkflowRunResponse
	19, // [19:27] is the sub-list for method output_type
	11, // [11:19] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_flexiq_v1_producer_service_proto_init() }
func file_flexiq_v1_producer_service_proto_init() {
	if File_flexiq_v1_producer_service_proto != nil {
		return
	}
	file_flexiq_v1_job_proto_init()
	file_flexiq_v1_workflow_proto_init()
	file_flexiq_v1_producer_service_proto_msgTypes[0].OneofWrappers = []any{
		(*EnqueueRequest_Raw)(nil),
		(*EnqueueRequest_Structured)(nil),
	}
	file_flexiq_v1_producer_service_proto_msgTypes[4].OneofWrappers = []any{
		(*EnqueueBatchItemResult_Enqueued)(nil),
		(*EnqueueBatchItemResult_Error)(nil),
	}
	file_flexiq_v1_producer_service_proto_msgTypes[7].OneofWrappers = []any{}
	file_flexiq_v1_producer_service_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flexiq_v1_producer_service_proto_rawDesc), len(file_flexiq_v1_producer_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_flexiq_v1_producer_service_proto_goTypes,
		DependencyIndexes: file_flexiq_v1_producer_service_proto_depIdxs,
		MessageInfos:      file_flexiq_v1_producer_service_proto_msgTypes,
	}.Build()
	File_flexiq_v1_producer_service_proto = out.File
	file_flexiq_v1_producer_service_proto_goTypes = nil
	file_flexiq_v1_producer_service_proto_depIdxs = nil
}
