// STABLE as of 2.0.0, the release that first shipped the gRPC role. Field
// numbers, field names and RPC shapes are permanent from here (§2.2 of
// tasks/specs/2026-09-01-flexiq-v1-proto-design.md): the `proto-breaking`
// label is for reverting a mistake made in the same release train, never for
// changing a shipped shape.
//
// The rules this package is held to are stated in full in job.proto, because a
// client reads the .proto and not the design document.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: flexiq/v1/producer_service.proto

package flexiqv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProducerService_Enqueue_FullMethodName        = "/flexiq.v1.ProducerService/Enqueue"
	ProducerService_EnqueueBatch_FullMethodName   = "/flexiq.v1.ProducerService/EnqueueBatch"
	ProducerService_GetJob_FullMethodName         = "/flexiq.v1.ProducerService/GetJob"
	ProducerService_ListJobs_FullMethodName       = "/flexiq.v1.ProducerService/ListJobs"
	ProducerService_CancelJob_FullMethodName      = "/flexiq.v1.ProducerService/CancelJob"
	ProducerService_QueueStats_FullMethodName     = "/flexiq.v1.ProducerService/QueueStats"
	ProducerService_SubmitWorkflow_FullMethodName = "/flexiq.v1.ProducerService/SubmitWorkflow"
	ProducerService_GetWorkflowRun_FullMethodName = "/flexiq.v1.ProducerService/GetWorkflowRun"
)

// ProducerServiceClient is the client API for ProducerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The producer door: submit work, read it back, cancel it, count it.
//
// What this service deliberately does not offer, and will not grow:
//
//   - An admin surface. Pausing queues, settings, dead-letter operations,
//     webhook secrets and circuit-breaker internals stay behind the dashboard's
//     session and role check. An operator surface and a producer surface have
//     different audiences and must not share a credential.
//   - A way to name a namespace. One listener serves exactly one namespace, and
//     it comes from the server's own configuration. A read for a job in another
//     namespace is indistinguishable from a job that does not exist.
//   - Uniqueness, debouncing and batching as verbs. They are options and
//     shapes: one Enqueue, one EnqueueBatch.
//
// And what it does not promise:
//
//   - No ordering. Priority and scheduled_at influence dispatch; nothing
//     promises two jobs enqueued in order run in order.
//   - No exactly-once execution. A unique_key dedupes an *enqueue*. Execution
//     is at-least-once.
//   - No batch atomicity. See EnqueueBatchResponse.
//   - No task-name validation. The server holds no task registry, so enqueuing
//     a task nobody implements succeeds and the job eventually dead-letters.
//   - No completion notification. There is no watch and no server stream in v1;
//     poll GetJob or use a webhook subscription.
//   - No permanent job ids. Retention archives and then deletes, so a NOT_FOUND
//     does not mean the job never existed.
//   - No safe blind retry of a write. UNAVAILABLE, DEADLINE_EXCEEDED and
//     CANCELLED on an Enqueue may all mean the write landed and the connection
//     dropped afterwards, and no field on the wire can tell. A client that
//     retries sets a unique_key — see EnqueueOptions.unique_key for the
//     window that key covers.
type ProducerServiceClient interface {
	// Submit one job.
	//
	// Not idempotent, even with a unique_key: the level is a property of the
	// method, and one that held only for some requests is one a proxy would apply
	// to the others.
	Enqueue(ctx context.Context, in *EnqueueRequest, opts ...grpc.CallOption) (*EnqueueResponse, error)
	// Submit many jobs, with one result per input item in input order.
	EnqueueBatch(ctx context.Context, in *EnqueueBatchRequest, opts ...grpc.CallOption) (*EnqueueBatchResponse, error)
	// Read one job by id.
	GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error)
	// Page through jobs, newest first.
	ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error)
	// Cancel a job, and report the state that leaves it in.
	//
	// Idempotent because the response describes state rather than what the call
	// did: a second call answers the same thing as the first.
	CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*CancelJobResponse, error)
	// Per-status job counts, for one queue or for the whole namespace.
	QueueStats(ctx context.Context, in *QueueStatsRequest, opts ...grpc.CallOption) (*QueueStatsResponse, error)
	// Submit a workflow graph for execution.
	//
	// Not idempotent: there is no unique_key equivalent for a workflow, so a
	// retried call after a dropped connection can submit twice. See
	// SubmitWorkflowRequest.
	SubmitWorkflow(ctx context.Context, in *SubmitWorkflowRequest, opts ...grpc.CallOption) (*SubmitWorkflowResponse, error)
	// Read a workflow run's state and every node's.
	GetWorkflowRun(ctx context.Context, in *GetWorkflowRunRequest, opts ...grpc.CallOption) (*GetWorkflowRunResponse, error)
}

type producerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProducerServiceClient(cc grpc.ClientConnInterface) ProducerServiceClient {
	return &producerServiceClient{cc}
}

func (c *producerServiceClient) Enqueue(ctx context.Context, in *EnqueueRequest, opts ...grpc.CallOption) (*EnqueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnqueueResponse)
	err := c.cc.Invoke(ctx, ProducerService_Enqueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *producerServiceClient) EnqueueBatch(ctx context.Context, in *EnqueueBatchRequest, opts ...grpc.CallOption) (*EnqueueBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnqueueBatchResponse)
	err := c.cc.Invoke(ctx, ProducerService_EnqueueBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *producerServiceClient) GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobResponse)
	err := c.cc.Invoke(ctx, ProducerService_GetJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *producerServiceClient) ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJobsResponse)
	err := c.cc.Invoke(ctx, ProducerService_ListJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *producerServiceClient) CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*CancelJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelJobResponse)
	err := c.cc.Invoke(ctx, ProducerService_CancelJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *producerServiceClient) QueueStats(ctx context.Context, in *QueueStatsRequest, opts ...grpc.CallOption) (*QueueStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueueStatsResponse)
	err := c.cc.Invoke(ctx, ProducerService_QueueStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *producerServiceClient) SubmitWorkflow(ctx context.Context, in *SubmitWorkflowRequest, opts ...grpc.CallOption) (*SubmitWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitWorkflowResponse)
	err := c.cc.Invoke(ctx, ProducerService_SubmitWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *producerServiceClient) GetWorkflowRun(ctx context.Context, in *GetWorkflowRunRequest, opts ...grpc.CallOption) (*GetWorkflowRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkflowRunResponse)
	err := c.cc.Invoke(ctx, ProducerService_GetWorkflowRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProducerServiceServer is the server API for ProducerService service.
// All implementations must embed UnimplementedProducerServiceServer
// for forward compatibility.
//
// The producer door: submit work, read it back, cancel it, count it.
//
// What this service deliberately does not offer, and will not grow:
//
//   - An admin surface. Pausing queues, settings, dead-letter operations,
//     webhook secrets and circuit-breaker internals stay behind the dashboard's
//     session and role check. An operator surface and a producer surface have
//     different audiences and must not share a credential.
//   - A way to name a namespace. One listener serves exactly one namespace, and
//     it comes from the server's own configuration. A read for a job in another
//     namespace is indistinguishable from a job that does not exist.
//   - Uniqueness, debouncing and batching as verbs. They are options and
//     shapes: one Enqueue, one EnqueueBatch.
//
// And what it does not promise:
//
//   - No ordering. Priority and scheduled_at influence dispatch; nothing
//     promises two jobs enqueued in order run in order.
//   - No exactly-once execution. A unique_key dedupes an *enqueue*. Execution
//     is at-least-once.
//   - No batch atomicity. See EnqueueBatchResponse.
//   - No task-name validation. The server holds no task registry, so enqueuing
//     a task nobody implements succeeds and the job eventually dead-letters.
//   - No completion notification. There is no watch and no server stream in v1;
//     poll GetJob or use a webhook subscription.
//   - No permanent job ids. Retention archives and then deletes, so a NOT_FOUND
//     does not mean the job never existed.
//   - No safe blind retry of a write. UNAVAILABLE, DEADLINE_EXCEEDED and
//     CANCELLED on an Enqueue may all mean the write landed and the connection
//     dropped afterwards, and no field on the wire can tell. A client that
//     retries sets a unique_key — see EnqueueOptions.unique_key for the
//     window that key covers.
type ProducerServiceServer interface {
	// Submit one job.
	//
	// Not idempotent, even with a unique_key: the level is a property of the
	// method, and one that held only for some requests is one a proxy would apply
	// to the others.
	Enqueue(context.Context, *EnqueueRequest) (*EnqueueResponse, error)
	// Submit many jobs, with one result per input item in input order.
	EnqueueBatch(context.Context, *EnqueueBatchRequest) (*EnqueueBatchResponse, error)
	// Read one job by id.
	GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error)
	// Page through jobs, newest first.
	ListJobs(context.Context, *ListJobsRequest) (*ListJobsResponse, error)
	// Cancel a job, and report the state that leaves it in.
	//
	// Idempotent because the response describes state rather than what the call
	// did: a second call answers the same thing as the first.
	CancelJob(context.Context, *CancelJobRequest) (*CancelJobResponse, error)
	// Per-status job counts, for one queue or for the whole namespace.
	QueueStats(context.Context, *QueueStatsRequest) (*QueueStatsResponse, error)
	// Submit a workflow graph for execution.
	//
	// Not idempotent: there is no unique_key equivalent for a workflow, so a
	// retried call after a dropped connection can submit twice. See
	// SubmitWorkflowRequest.
	SubmitWorkflow(context.Context, *SubmitWorkflowRequest) (*SubmitWorkflowResponse, error)
	// Read a workflow run's state and every node's.
	GetWorkflowRun(context.Context, *GetWorkflowRunRequest) (*GetWorkflowRunResponse, error)
	mustEmbedUnimplementedProducerServiceServer()
}

// UnimplementedProducerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProducerServiceServer struct{}

func (UnimplementedProducerServiceServer) Enqueue(context.Context, *EnqueueRequest) (*EnqueueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Enqueue not implemented")
}
func (UnimplementedProducerServiceServer) EnqueueBatch(context.Context, *EnqueueBatchRequest) (*EnqueueBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnqueueBatch not implemented")
}
func (UnimplementedProducerServiceServer) GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJob not implemented")
}
func (UnimplementedProducerServiceServer) ListJobs(context.Context, *ListJobsRequest) (*ListJobsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListJobs not implemented")
}
func (UnimplementedProducerServiceServer) CancelJob(context.Context, *CancelJobRequest) (*CancelJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelJob not implemented")
}
func (UnimplementedProducerServiceServer) QueueStats(context.Context, *QueueStatsRequest) (*QueueStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueueStats not implemented")
}
func (UnimplementedProducerServiceServer) SubmitWorkflow(context.Context, *SubmitWorkflowRequest) (*SubmitWorkflowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitWorkflow not implemented")
}
func (UnimplementedProducerServiceServer) GetWorkflowRun(context.Context, *GetWorkflowRunRequest) (*GetWorkflowRunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkflowRun not implemented")
}
func (UnimplementedProducerServiceServer) mustEmbedUnimplementedProducerServiceServer() {}
func (UnimplementedProducerServiceServer) testEmbeddedByValue()                         {}

// UnsafeProducerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProducerServiceServer will
// result in compilation errors.
type UnsafeProducerServiceServer interface {
	mustEmbedUnimplementedProducerServiceServer()
}

func RegisterProducerServiceServer(s grpc.ServiceRegistrar, srv ProducerServiceServer) {
	// If the following call pancis, it indicates UnimplementedProducerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProducerService_ServiceDesc, srv)
}

func _ProducerService_Enqueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProducerServiceServer).Enqueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProducerService_Enqueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProducerServiceServer).Enqueue(ctx, req.(*EnqueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProducerService_EnqueueBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueueBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProducerServiceServer).EnqueueBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProducerService_EnqueueBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProducerServiceServer).EnqueueBatch(ctx, req.(*EnqueueBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProducerService_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProducerServiceServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProducerService_GetJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProducerServiceServer).GetJob(ctx, req.(*GetJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProducerService_ListJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProducerServiceServer).ListJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProducerService_ListJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProducerServiceServer).ListJobs(ctx, req.(*ListJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProducerService_CancelJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProducerServiceServer).CancelJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProducerService_CancelJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProducerServiceServer).CancelJob(ctx, req.(*CancelJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProducerService_QueueStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueueStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProducerServiceServer).QueueStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProducerService_QueueStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProducerServiceServer).QueueStats(ctx, req.(*QueueStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProducerService_SubmitWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProducerServiceServer).SubmitWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProducerService_SubmitWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProducerServiceServer).SubmitWorkflow(ctx, req.(*SubmitWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProducerService_GetWorkflowRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkflowRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProducerServiceServer).GetWorkflowRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProducerService_GetWorkflowRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProducerServiceServer).GetWorkflowRun(ctx, req.(*GetWorkflowRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProducerService_ServiceDesc is the grpc.ServiceDesc for ProducerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProducerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flexiq.v1.ProducerService",
	HandlerType: (*ProducerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enqueue",
			Handler:    _ProducerService_Enqueue_Handler,
		},
		{
			MethodName: "EnqueueBatch",
			Handler:    _ProducerService_EnqueueBatch_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _ProducerService_GetJob_Handler,
		},
		{
			MethodName: "ListJobs",
			Handler:    _ProducerService_ListJobs_Handler,
		},
		{
			MethodName: "CancelJob",
			Handler:    _ProducerService_CancelJob_Handler,
		},
		{
			MethodName: "QueueStats",
			Handler:    _ProducerService_QueueStats_Handler,
		},
		{
			MethodName: "SubmitWorkflow",
			Handler:    _ProducerService_SubmitWorkflow_Handler,
		},
		{
			MethodName: "GetWorkflowRun",
			Handler:    _ProducerService_GetWorkflowRun_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flexiq/v1/producer_service.proto",
}
