// STABLE as of 2.0.0, the release that first shipped the gRPC role. Field
// numbers, field names and RPC shapes are permanent from here (§2.2 of
// tasks/specs/2026-09-01-flexiq-v1-proto-design.md): the `proto-breaking`
// label is for reverting a mistake made in the same release train, never for
// changing a shipped shape.
//
// The rules this package is held to are stated in full in job.proto, because a
// client reads the .proto and not the design document.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: flexiq/v1/workflow.proto

package flexiqv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// How an edge into a node gates that node, evaluated against its
// predecessor's outcome. The callable predicates some SDKs also support are
// not representable here — they are code, not data — so a workflow using one
// is not submittable over this RPC; its language SDK's own submission path is
// unaffected.
type EdgeCondition int32

const (
	// No filter — the same behavior as ALWAYS. A node's WorkflowNodeConfig
	// that sets no condition reads as this.
	EdgeCondition_EDGE_CONDITION_UNSPECIFIED EdgeCondition = 0
	// Only if every predecessor succeeded.
	EdgeCondition_EDGE_CONDITION_ON_SUCCESS EdgeCondition = 1
	// Only if a predecessor failed.
	EdgeCondition_EDGE_CONDITION_ON_FAILURE EdgeCondition = 2
	// Regardless of predecessor outcome. Identical to UNSPECIFIED; exists so a
	// caller can say "always" explicitly rather than by omission.
	EdgeCondition_EDGE_CONDITION_ALWAYS EdgeCondition = 3
)

// Enum value maps for EdgeCondition.
var (
	EdgeCondition_name = map[int32]string{
		0: "EDGE_CONDITION_UNSPECIFIED",
		1: "EDGE_CONDITION_ON_SUCCESS",
		2: "EDGE_CONDITION_ON_FAILURE",
		3: "EDGE_CONDITION_ALWAYS",
	}
	EdgeCondition_value = map[string]int32{
		"EDGE_CONDITION_UNSPECIFIED": 0,
		"EDGE_CONDITION_ON_SUCCESS":  1,
		"EDGE_CONDITION_ON_FAILURE":  2,
		"EDGE_CONDITION_ALWAYS":      3,
	}
)

func (x EdgeCondition) Enum() *EdgeCondition {
	p := new(EdgeCondition)
	*p = x
	return p
}

func (x EdgeCondition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EdgeCondition) Descriptor() protoreflect.EnumDescriptor {
	return file_flexiq_v1_workflow_proto_enumTypes[0].Descriptor()
}

func (EdgeCondition) Type() protoreflect.EnumType {
	return &file_flexiq_v1_workflow_proto_enumTypes[0]
}

func (x EdgeCondition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EdgeCondition.Descriptor instead.
func (EdgeCondition) EnumDescriptor() ([]byte, []int) {
	return file_flexiq_v1_workflow_proto_rawDescGZIP(), []int{0}
}

// What a gate does if its timeout elapses with no decision.
type OnTimeout int32

const (
	OnTimeout_ON_TIMEOUT_UNSPECIFIED OnTimeout = 0
	OnTimeout_ON_TIMEOUT_APPROVE     OnTimeout = 1
	OnTimeout_ON_TIMEOUT_REJECT      OnTimeout = 2
)

// Enum value maps for OnTimeout.
var (
	OnTimeout_name = map[int32]string{
		0: "ON_TIMEOUT_UNSPECIFIED",
		1: "ON_TIMEOUT_APPROVE",
		2: "ON_TIMEOUT_REJECT",
	}
	OnTimeout_value = map[string]int32{
		"ON_TIMEOUT_UNSPECIFIED": 0,
		"ON_TIMEOUT_APPROVE":     1,
		"ON_TIMEOUT_REJECT":      2,
	}
)

func (x OnTimeout) Enum() *OnTimeout {
	p := new(OnTimeout)
	*p = x
	return p
}

func (x OnTimeout) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OnTimeout) Descriptor() protoreflect.EnumDescriptor {
	return file_flexiq_v1_workflow_proto_enumTypes[1].Descriptor()
}

func (OnTimeout) Type() protoreflect.EnumType {
	return &file_flexiq_v1_workflow_proto_enumTypes[1]
}

func (x OnTimeout) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OnTimeout.Descriptor instead.
func (OnTimeout) EnumDescriptor() ([]byte, []int) {
	return file_flexiq_v1_workflow_proto_rawDescGZIP(), []int{1}
}

// Lifecycle state of a workflow run.
//
// One-to-one with `WorkflowState` in crates/flexiq-workflows/src/state.rs,
// offset by one the same way JobStatus is: zero is spent here on
// `_UNSPECIFIED`, and the conversion is an exhaustive match with no wildcard.
// A reader that does not recognise a value must treat the run as **not
// terminal**.
type WorkflowState int32

const (
	WorkflowState_WORKFLOW_STATE_UNSPECIFIED WorkflowState = 0
	WorkflowState_WORKFLOW_STATE_PENDING     WorkflowState = 1
	WorkflowState_WORKFLOW_STATE_RUNNING     WorkflowState = 2
	WorkflowState_WORKFLOW_STATE_PAUSED      WorkflowState = 3
	WorkflowState_WORKFLOW_STATE_COMPLETED   WorkflowState = 4
	// Every node reached a terminal state, but at least one failed and the run
	// was constructed to continue rather than fail fast.
	WorkflowState_WORKFLOW_STATE_COMPLETED_WITH_FAILURES WorkflowState = 5
	WorkflowState_WORKFLOW_STATE_FAILED                  WorkflowState = 6
	WorkflowState_WORKFLOW_STATE_CANCELLED               WorkflowState = 7
	// Saga rollback is in flight.
	WorkflowState_WORKFLOW_STATE_COMPENSATING WorkflowState = 8
	// Saga rollback finished successfully.
	WorkflowState_WORKFLOW_STATE_COMPENSATED WorkflowState = 9
	// Saga rollback itself failed.
	WorkflowState_WORKFLOW_STATE_COMPENSATION_FAILED WorkflowState = 10
)

// Enum value maps for WorkflowState.
var (
	WorkflowState_name = map[int32]string{
		0:  "WORKFLOW_STATE_UNSPECIFIED",
		1:  "WORKFLOW_STATE_PENDING",
		2:  "WORKFLOW_STATE_RUNNING",
		3:  "WORKFLOW_STATE_PAUSED",
		4:  "WORKFLOW_STATE_COMPLETED",
		5:  "WORKFLOW_STATE_COMPLETED_WITH_FAILURES",
		6:  "WORKFLOW_STATE_FAILED",
		7:  "WORKFLOW_STATE_CANCELLED",
		8:  "WORKFLOW_STATE_COMPENSATING",
		9:  "WORKFLOW_STATE_COMPENSATED",
		10: "WORKFLOW_STATE_COMPENSATION_FAILED",
	}
	WorkflowState_value = map[string]int32{
		"WORKFLOW_STATE_UNSPECIFIED":             0,
		"WORKFLOW_STATE_PENDING":                 1,
		"WORKFLOW_STATE_RUNNING":                 2,
		"WORKFLOW_STATE_PAUSED":                  3,
		"WORKFLOW_STATE_COMPLETED":               4,
		"WORKFLOW_STATE_COMPLETED_WITH_FAILURES": 5,
		"WORKFLOW_STATE_FAILED":                  6,
		"WORKFLOW_STATE_CANCELLED":               7,
		"WORKFLOW_STATE_COMPENSATING":            8,
		"WORKFLOW_STATE_COMPENSATED":             9,
		"WORKFLOW_STATE_COMPENSATION_FAILED":     10,
	}
)

func (x WorkflowState) Enum() *WorkflowState {
	p := new(WorkflowState)
	*p = x
	return p
}

func (x WorkflowState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowState) Descriptor() protoreflect.EnumDescriptor {
	return file_flexiq_v1_workflow_proto_enumTypes[2].Descriptor()
}

func (WorkflowState) Type() protoreflect.EnumType {
	return &file_flexiq_v1_workflow_proto_enumTypes[2]
}

func (x WorkflowState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowState.Descriptor instead.
func (WorkflowState) EnumDescriptor() ([]byte, []int) {
	return file_flexiq_v1_workflow_proto_rawDescGZIP(), []int{2}
}

// Status of one node within a run.
//
// One-to-one with `WorkflowNodeStatus` in crates/flexiq-workflows/src/node.rs.
// The numbers were the core's discriminants offset by one until READY was
// removed in 2.0.0; they are wire values now, so the mapping is the explicit
// table in grpc/producer/convert.rs and nothing may be renumbered to restore
// the arithmetic.
type WorkflowNodeStatus int32

const (
	WorkflowNodeStatus_WORKFLOW_NODE_STATUS_UNSPECIFIED         WorkflowNodeStatus = 0
	WorkflowNodeStatus_WORKFLOW_NODE_STATUS_PENDING             WorkflowNodeStatus = 1
	WorkflowNodeStatus_WORKFLOW_NODE_STATUS_RUNNING             WorkflowNodeStatus = 3
	WorkflowNodeStatus_WORKFLOW_NODE_STATUS_COMPLETED           WorkflowNodeStatus = 4
	WorkflowNodeStatus_WORKFLOW_NODE_STATUS_FAILED              WorkflowNodeStatus = 5
	WorkflowNodeStatus_WORKFLOW_NODE_STATUS_SKIPPED             WorkflowNodeStatus = 6
	WorkflowNodeStatus_WORKFLOW_NODE_STATUS_WAITING_APPROVAL    WorkflowNodeStatus = 7
	WorkflowNodeStatus_WORKFLOW_NODE_STATUS_CACHE_HIT           WorkflowNodeStatus = 8
	WorkflowNodeStatus_WORKFLOW_NODE_STATUS_COMPENSATING        WorkflowNodeStatus = 9
	WorkflowNodeStatus_WORKFLOW_NODE_STATUS_COMPENSATED         WorkflowNodeStatus = 10
	WorkflowNodeStatus_WORKFLOW_NODE_STATUS_COMPENSATION_FAILED WorkflowNodeStatus = 11
)

// Enum value maps for WorkflowNodeStatus.
var (
	WorkflowNodeStatus_name = map[int32]string{
		0:  "WORKFLOW_NODE_STATUS_UNSPECIFIED",
		1:  "WORKFLOW_NODE_STATUS_PENDING",
		3:  "WORKFLOW_NODE_STATUS_RUNNING",
		4:  "WORKFLOW_NODE_STATUS_COMPLETED",
		5:  "WORKFLOW_NODE_STATUS_FAILED",
		6:  "WORKFLOW_NODE_STATUS_SKIPPED",
		7:  "WORKFLOW_NODE_STATUS_WAITING_APPROVAL",
		8:  "WORKFLOW_NODE_STATUS_CACHE_HIT",
		9:  "WORKFLOW_NODE_STATUS_COMPENSATING",
		10: "WORKFLOW_NODE_STATUS_COMPENSATED",
		11: "WORKFLOW_NODE_STATUS_COMPENSATION_FAILED",
	}
	WorkflowNodeStatus_value = map[string]int32{
		"WORKFLOW_NODE_STATUS_UNSPECIFIED":         0,
		"WORKFLOW_NODE_STATUS_PENDING":             1,
		"WORKFLOW_NODE_STATUS_RUNNING":             3,
		"WORKFLOW_NODE_STATUS_COMPLETED":           4,
		"WORKFLOW_NODE_STATUS_FAILED":              5,
		"WORKFLOW_NODE_STATUS_SKIPPED":             6,
		"WORKFLOW_NODE_STATUS_WAITING_APPROVAL":    7,
		"WORKFLOW_NODE_STATUS_CACHE_HIT":           8,
		"WORKFLOW_NODE_STATUS_COMPENSATING":        9,
		"WORKFLOW_NODE_STATUS_COMPENSATED":         10,
		"WORKFLOW_NODE_STATUS_COMPENSATION_FAILED": 11,
	}
)

func (x WorkflowNodeStatus) Enum() *WorkflowNodeStatus {
	p := new(WorkflowNodeStatus)
	*p = x
	return p
}

func (x WorkflowNodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowNodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_flexiq_v1_workflow_proto_enumTypes[3].Descriptor()
}

func (WorkflowNodeStatus) Type() protoreflect.EnumType {
	return &file_flexiq_v1_workflow_proto_enumTypes[3]
}

func (x WorkflowNodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowNodeStatus.Descriptor instead.
func (WorkflowNodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_flexiq_v1_workflow_proto_rawDescGZIP(), []int{3}
}

// A workflow's shape: which steps exist, how they depend on one another, and
// each step's own configuration.
//
// Two independent pieces, matching how a workflow is actually built and
// compiled server-side (crates/flexiq-python/src/py_workflow/mod.rs): a bare
// graph of node names and edges, and a name-keyed configuration map. Neither
// this message nor WorkflowNodeConfig ever carries `dag_data` — the JSON
// dagron_core::SerializableGraph produces internally. This message compiles
// into that form; it does not transmit it.
type WorkflowGraph struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Nodes []*WorkflowGraphNode   `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Edges []*WorkflowGraphEdge   `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	// Every non-empty node in `nodes` must have exactly one entry here, keyed by
	// WorkflowNodeConfig.name.
	NodeConfigs   []*WorkflowNodeConfig `protobuf:"bytes,3,rep,name=node_configs,json=nodeConfigs,proto3" json:"node_configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowGraph) Reset() {
	*x = WorkflowGraph{}
	mi := &file_flexiq_v1_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowGraph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowGraph) ProtoMessage() {}

func (x *WorkflowGraph) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_v1_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowGraph.ProtoReflect.Descriptor instead.
func (*WorkflowGraph) Descriptor() ([]byte, []int) {
	return file_flexiq_v1_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *WorkflowGraph) GetNodes() []*WorkflowGraphNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *WorkflowGraph) GetEdges() []*WorkflowGraphEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *WorkflowGraph) GetNodeConfigs() []*WorkflowNodeConfig {
	if x != nil {
		return x.NodeConfigs
	}
	return nil
}

// One node in the graph's shape. The node's configuration lives in the
// matching WorkflowNodeConfig, not here — this message carries only what the
// DAG itself needs.
type WorkflowGraphNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowGraphNode) Reset() {
	*x = WorkflowGraphNode{}
	mi := &file_flexiq_v1_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowGraphNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowGraphNode) ProtoMessage() {}

func (x *WorkflowGraphNode) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_v1_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowGraphNode.ProtoReflect.Descriptor instead.
func (*WorkflowGraphNode) Descriptor() ([]byte, []int) {
	return file_flexiq_v1_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *WorkflowGraphNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// One edge, `from` must complete before `to` becomes eligible.
type WorkflowGraphEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowGraphEdge) Reset() {
	*x = WorkflowGraphEdge{}
	mi := &file_flexiq_v1_workflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowGraphEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowGraphEdge) ProtoMessage() {}

func (x *WorkflowGraphEdge) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_v1_workflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowGraphEdge.ProtoReflect.Descriptor instead.
func (*WorkflowGraphEdge) Descriptor() ([]byte, []int) {
	return file_flexiq_v1_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *WorkflowGraphEdge) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *WorkflowGraphEdge) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

// A gate: the node pauses and waits for an external decision before running.
//
// **`SubmitWorkflow` refuses any graph where a node sets this field.** Gate
// evaluation is driven by a live SDK tracker process today, and nothing
// reachable from the producer door can drive one — see WorkflowNodeConfig.
// The field exists so the wire never needs a second, breaking pass to add it
// once that changes.
type GateConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unset waits indefinitely.
	Timeout       *durationpb.Duration `protobuf:"bytes,1,opt,name=timeout,proto3" json:"timeout,omitempty"`
	OnTimeout     OnTimeout            `protobuf:"varint,2,opt,name=on_timeout,json=onTimeout,proto3,enum=flexiq.v1.OnTimeout" json:"on_timeout,omitempty"`
	Message       *string              `protobuf:"bytes,3,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GateConfig) Reset() {
	*x = GateConfig{}
	mi := &file_flexiq_v1_workflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GateConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateConfig) ProtoMessage() {}

func (x *GateConfig) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_v1_workflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateConfig.ProtoReflect.Descriptor instead.
func (*GateConfig) Descriptor() ([]byte, []int) {
	return file_flexiq_v1_workflow_proto_rawDescGZIP(), []int{3}
}

func (x *GateConfig) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *GateConfig) GetOnTimeout() OnTimeout {
	if x != nil {
		return x.OnTimeout
	}
	return OnTimeout_ON_TIMEOUT_UNSPECIFIED
}

func (x *GateConfig) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

// Memoize this node's result and skip re-running it on a later, otherwise
// identical, submission.
//
// **`SubmitWorkflow` refuses any graph where a node sets this field**, for the
// same reason as GateConfig: nothing reachable from the producer door
// resolves a cache hit yet.
type CacheConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unset caches indefinitely.
	Ttl           *durationpb.Duration `protobuf:"bytes,1,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheConfig) Reset() {
	*x = CacheConfig{}
	mi := &file_flexiq_v1_workflow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheConfig) ProtoMessage() {}

func (x *CacheConfig) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_v1_workflow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheConfig.ProtoReflect.Descriptor instead.
func (*CacheConfig) Descriptor() ([]byte, []int) {
	return file_flexiq_v1_workflow_proto_rawDescGZIP(), []int{4}
}

func (x *CacheConfig) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

// Expand this node into one job per item at runtime.
//
// **`SubmitWorkflow` refuses any graph where a node sets this field.** Runtime
// expansion is exactly the kind of thing a live SDK tracker does and a
// stateless RPC cannot.
type FanOutConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The node whose result supplies the items to expand over. Unset infers the
	// single predecessor structurally, the same inference a fan-out with no
	// explicit source already falls back to in every shell.
	ItemsFrom     *string `protobuf:"bytes,1,opt,name=items_from,json=itemsFrom,proto3,oneof" json:"items_from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FanOutConfig) Reset() {
	*x = FanOutConfig{}
	mi := &file_flexiq_v1_workflow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FanOutConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FanOutConfig) ProtoMessage() {}

func (x *FanOutConfig) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_v1_workflow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FanOutConfig.ProtoReflect.Descriptor instead.
func (*FanOutConfig) Descriptor() ([]byte, []int) {
	return file_flexiq_v1_workflow_proto_rawDescGZIP(), []int{5}
}

func (x *FanOutConfig) GetItemsFrom() string {
	if x != nil && x.ItemsFrom != nil {
		return *x.ItemsFrom
	}
	return ""
}

// Collect a fan-out's expanded results back into one node.
//
// **`SubmitWorkflow` refuses any graph where a node sets this field**, for the
// same reason as FanOutConfig.
type FanInConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The fan-out node this collects.
	From          string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FanInConfig) Reset() {
	*x = FanInConfig{}
	mi := &file_flexiq_v1_workflow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FanInConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FanInConfig) ProtoMessage() {}

func (x *FanInConfig) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_v1_workflow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FanInConfig.ProtoReflect.Descriptor instead.
func (*FanInConfig) Descriptor() ([]byte, []int) {
	return file_flexiq_v1_workflow_proto_rawDescGZIP(), []int{6}
}

func (x *FanInConfig) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

// A child workflow, submitted and tracked as part of running this node.
//
// **`SubmitWorkflow` refuses any graph where a node sets this field.**
// Recursive on WorkflowGraph rather than a bespoke transport: a child node
// already carries its own args on its own `body` oneof, so nothing here needs
// a second, parallel payload map the way today's per-SDK sub-workflow
// transports each independently invented one.
type SubWorkflowSpec struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Name    string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Graph   *WorkflowGraph         `protobuf:"bytes,3,opt,name=graph,proto3" json:"graph,omitempty"`
	// Node names in `graph` whose job is not pre-enqueued at submission — an
	// SDK tracker creates it at runtime once its gating condition resolves.
	DeferredNodeNames []string `protobuf:"bytes,4,rep,name=deferred_node_names,json=deferredNodeNames,proto3" json:"deferred_node_names,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SubWorkflowSpec) Reset() {
	*x = SubWorkflowSpec{}
	mi := &file_flexiq_v1_workflow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubWorkflowSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubWorkflowSpec) ProtoMessage() {}

func (x *SubWorkflowSpec) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_v1_workflow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubWorkflowSpec.ProtoReflect.Descriptor instead.
func (*SubWorkflowSpec) Descriptor() ([]byte, []int) {
	return file_flexiq_v1_workflow_proto_rawDescGZIP(), []int{7}
}

func (x *SubWorkflowSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubWorkflowSpec) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SubWorkflowSpec) GetGraph() *WorkflowGraph {
	if x != nil {
		return x.Graph
	}
	return nil
}

func (x *SubWorkflowSpec) GetDeferredNodeNames() []string {
	if x != nil {
		return x.DeferredNodeNames
	}
	return nil
}

// One node's configuration: what it runs, and how it relates to the workflow
// around it.
//
// Every StepMetadata field (crates/flexiq-workflows/src/definition.rs:9-45)
// has a typed home here, including the five that are opaque JSON strings
// server-side today — gate, cache, fan_out, fan_in, sub_workflow — so the wire
// never needs a breaking pass to type them later. `args_template` and
// `kwargs_template` do not appear: a node's arguments travel on `body`, the
// same oneof EnqueueRequest already uses, and `kwargs_template` had no reader
// in any shell.
//
// Fields 1-15 fit the one-byte range (see job.proto's Job message) because
// every field here is a real per-node decision, not a hot path some caller
// skips.
type WorkflowNodeConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Matches a WorkflowGraphNode.name in the same WorkflowGraph.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The registered task to run. Not validated here; see ProducerService.
	TaskName string `protobuf:"bytes,2,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	// Empty means "default".
	Queue *string `protobuf:"bytes,3,opt,name=queue,proto3,oneof" json:"queue,omitempty"`
	// The node's arguments. Setting no arm is an error, the same as
	// EnqueueRequest.body.
	//
	// Types that are valid to be assigned to Body:
	//
	//	*WorkflowNodeConfig_Raw
	//	*WorkflowNodeConfig_Structured
	Body       isWorkflowNodeConfig_Body `protobuf_oneof:"body"`
	MaxRetries *int32                    `protobuf:"varint,6,opt,name=max_retries,json=maxRetries,proto3,oneof" json:"max_retries,omitempty"`
	Timeout    *durationpb.Duration      `protobuf:"bytes,7,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Priority   *int32                    `protobuf:"varint,8,opt,name=priority,proto3,oneof" json:"priority,omitempty"`
	// How an inbound edge gates this node. Unset behaves as ALWAYS.
	Condition   EdgeCondition    `protobuf:"varint,9,opt,name=condition,proto3,enum=flexiq.v1.EdgeCondition" json:"condition,omitempty"`
	Gate        *GateConfig      `protobuf:"bytes,10,opt,name=gate,proto3,oneof" json:"gate,omitempty"`
	Cache       *CacheConfig     `protobuf:"bytes,11,opt,name=cache,proto3,oneof" json:"cache,omitempty"`
	FanOut      *FanOutConfig    `protobuf:"bytes,12,opt,name=fan_out,json=fanOut,proto3,oneof" json:"fan_out,omitempty"`
	FanIn       *FanInConfig     `protobuf:"bytes,13,opt,name=fan_in,json=fanIn,proto3,oneof" json:"fan_in,omitempty"`
	SubWorkflow *SubWorkflowSpec `protobuf:"bytes,14,opt,name=sub_workflow,json=subWorkflow,proto3,oneof" json:"sub_workflow,omitempty"`
	// The task to run if this node needs to be rolled back by a saga
	// compensation. A task name, never JSON.
	Compensate    *string `protobuf:"bytes,15,opt,name=compensate,proto3,oneof" json:"compensate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowNodeConfig) Reset() {
	*x = WorkflowNodeConfig{}
	mi := &file_flexiq_v1_workflow_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowNodeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowNodeConfig) ProtoMessage() {}

func (x *WorkflowNodeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_v1_workflow_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowNodeConfig.ProtoReflect.Descriptor instead.
func (*WorkflowNodeConfig) Descriptor() ([]byte, []int) {
	return file_flexiq_v1_workflow_proto_rawDescGZIP(), []int{8}
}

func (x *WorkflowNodeConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkflowNodeConfig) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *WorkflowNodeConfig) GetQueue() string {
	if x != nil && x.Queue != nil {
		return *x.Queue
	}
	return ""
}

func (x *WorkflowNodeConfig) GetBody() isWorkflowNodeConfig_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *WorkflowNodeConfig) GetRaw() []byte {
	if x != nil {
		if x, ok := x.Body.(*WorkflowNodeConfig_Raw); ok {
			return x.Raw
		}
	}
	return nil
}

func (x *WorkflowNodeConfig) GetStructured() *StructuredArgs {
	if x != nil {
		if x, ok := x.Body.(*WorkflowNodeConfig_Structured); ok {
			return x.Structured
		}
	}
	return nil
}

func (x *WorkflowNodeConfig) GetMaxRetries() int32 {
	if x != nil && x.MaxRetries != nil {
		return *x.MaxRetries
	}
	return 0
}

func (x *WorkflowNodeConfig) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *WorkflowNodeConfig) GetPriority() int32 {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return 0
}

func (x *WorkflowNodeConfig) GetCondition() EdgeCondition {
	if x != nil {
		return x.Condition
	}
	return EdgeCondition_EDGE_CONDITION_UNSPECIFIED
}

func (x *WorkflowNodeConfig) GetGate() *GateConfig {
	if x != nil {
		return x.Gate
	}
	return nil
}

func (x *WorkflowNodeConfig) GetCache() *CacheConfig {
	if x != nil {
		return x.Cache
	}
	return nil
}

func (x *WorkflowNodeConfig) GetFanOut() *FanOutConfig {
	if x != nil {
		return x.FanOut
	}
	return nil
}

func (x *WorkflowNodeConfig) GetFanIn() *FanInConfig {
	if x != nil {
		return x.FanIn
	}
	return nil
}

func (x *WorkflowNodeConfig) GetSubWorkflow() *SubWorkflowSpec {
	if x != nil {
		return x.SubWorkflow
	}
	return nil
}

func (x *WorkflowNodeConfig) GetCompensate() string {
	if x != nil && x.Compensate != nil {
		return *x.Compensate
	}
	return ""
}

type isWorkflowNodeConfig_Body interface {
	isWorkflowNodeConfig_Body()
}

type WorkflowNodeConfig_Raw struct {
	Raw []byte `protobuf:"bytes,4,opt,name=raw,proto3,oneof"`
}

type WorkflowNodeConfig_Structured struct {
	Structured *StructuredArgs `protobuf:"bytes,5,opt,name=structured,proto3,oneof"`
}

func (*WorkflowNodeConfig_Raw) isWorkflowNodeConfig_Body() {}

func (*WorkflowNodeConfig_Structured) isWorkflowNodeConfig_Body() {}

// A workflow run, as a reader sees it.
//
// Mirrors crates/flexiq-workflows/src/run.rs. Fields whose absence differs
// from their zero carry explicit presence.
type WorkflowRun struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DefinitionId string                 `protobuf:"bytes,2,opt,name=definition_id,json=definitionId,proto3" json:"definition_id,omitempty"`
	State        WorkflowState          `protobuf:"varint,3,opt,name=state,proto3,enum=flexiq.v1.WorkflowState" json:"state,omitempty"`
	StartedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Error        *string                `protobuf:"bytes,6,opt,name=error,proto3,oneof" json:"error,omitempty"`
	// Set when this run is a sub-workflow: the parent run and the node in it
	// that started this run.
	ParentRunId    *string                `protobuf:"bytes,7,opt,name=parent_run_id,json=parentRunId,proto3,oneof" json:"parent_run_id,omitempty"`
	ParentNodeName *string                `protobuf:"bytes,8,opt,name=parent_node_name,json=parentNodeName,proto3,oneof" json:"parent_node_name,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WorkflowRun) Reset() {
	*x = WorkflowRun{}
	mi := &file_flexiq_v1_workflow_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowRun) ProtoMessage() {}

func (x *WorkflowRun) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_v1_workflow_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowRun.ProtoReflect.Descriptor instead.
func (*WorkflowRun) Descriptor() ([]byte, []int) {
	return file_flexiq_v1_workflow_proto_rawDescGZIP(), []int{9}
}

func (x *WorkflowRun) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkflowRun) GetDefinitionId() string {
	if x != nil {
		return x.DefinitionId
	}
	return ""
}

func (x *WorkflowRun) GetState() WorkflowState {
	if x != nil {
		return x.State
	}
	return WorkflowState_WORKFLOW_STATE_UNSPECIFIED
}

func (x *WorkflowRun) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *WorkflowRun) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *WorkflowRun) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *WorkflowRun) GetParentRunId() string {
	if x != nil && x.ParentRunId != nil {
		return *x.ParentRunId
	}
	return ""
}

func (x *WorkflowRun) GetParentNodeName() string {
	if x != nil && x.ParentNodeName != nil {
		return *x.ParentNodeName
	}
	return ""
}

func (x *WorkflowRun) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// One node's state within a run.
type WorkflowNode struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Name   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status WorkflowNodeStatus     `protobuf:"varint,2,opt,name=status,proto3,enum=flexiq.v1.WorkflowNodeStatus" json:"status,omitempty"`
	// Unset while the node has not yet been enqueued (deferred nodes, before an
	// SDK tracker creates their job).
	JobId         *string                `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3,oneof" json:"job_id,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Error         *string                `protobuf:"bytes,6,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowNode) Reset() {
	*x = WorkflowNode{}
	mi := &file_flexiq_v1_workflow_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowNode) ProtoMessage() {}

func (x *WorkflowNode) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_v1_workflow_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowNode.ProtoReflect.Descriptor instead.
func (*WorkflowNode) Descriptor() ([]byte, []int) {
	return file_flexiq_v1_workflow_proto_rawDescGZIP(), []int{10}
}

func (x *WorkflowNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkflowNode) GetStatus() WorkflowNodeStatus {
	if x != nil {
		return x.Status
	}
	return WorkflowNodeStatus_WORKFLOW_NODE_STATUS_UNSPECIFIED
}

func (x *WorkflowNode) GetJobId() string {
	if x != nil && x.JobId != nil {
		return *x.JobId
	}
	return ""
}

func (x *WorkflowNode) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *WorkflowNode) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *WorkflowNode) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

// Submit a workflow graph for execution.
//
// Refused, FAILED_PRECONDITION, naming the offending node, if any
// WorkflowNodeConfig sets gate, cache, fan_out, fan_in or sub_workflow — see
// WorkflowNodeConfig's per-field comments. A graph that clears that check is
// pre-enqueued as one Job per node, chained by the graph's edges, exactly as
// an equivalent call through an SDK's own submit_workflow would be; any
// worker with workflow tracking enabled advances it, whether or not it is the
// caller that submitted the graph.
//
// There is no caller-supplied version: every submission is version 1 of
// `name`. Resubmitting `name` with a graph that differs from what version 1
// already holds is refused, INVALID_ARGUMENT — never silently reused —
// because a run's definition must describe the graph that produced its jobs.
// Submit a materially different graph under a different `name` until this
// gains a real version field.
type SubmitWorkflowRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Graph *WorkflowGraph         `protobuf:"bytes,2,opt,name=graph,proto3" json:"graph,omitempty"`
	// Arbitrary caller data attached to the run, opaque JSON text and
	// byte-preserved — the same convention as Job.metadata, not the raw/structured
	// envelope: it is data the run carries, never a call a task receives.
	ParamsJson    *string `protobuf:"bytes,3,opt,name=params_json,json=paramsJson,proto3,oneof" json:"params_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitWorkflowRequest) Reset() {
	*x = SubmitWorkflowRequest{}
	mi := &file_flexiq_v1_workflow_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitWorkflowRequest) ProtoMessage() {}

func (x *SubmitWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_v1_workflow_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitWorkflowRequest.ProtoReflect.Descriptor instead.
func (*SubmitWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_flexiq_v1_workflow_proto_rawDescGZIP(), []int{11}
}

func (x *SubmitWorkflowRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubmitWorkflowRequest) GetGraph() *WorkflowGraph {
	if x != nil {
		return x.Graph
	}
	return nil
}

func (x *SubmitWorkflowRequest) GetParamsJson() string {
	if x != nil && x.ParamsJson != nil {
		return *x.ParamsJson
	}
	return ""
}

type SubmitWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitWorkflowResponse) Reset() {
	*x = SubmitWorkflowResponse{}
	mi := &file_flexiq_v1_workflow_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitWorkflowResponse) ProtoMessage() {}

func (x *SubmitWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_v1_workflow_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitWorkflowResponse.ProtoReflect.Descriptor instead.
func (*SubmitWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_flexiq_v1_workflow_proto_rawDescGZIP(), []int{12}
}

func (x *SubmitWorkflowResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type GetWorkflowRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowRunRequest) Reset() {
	*x = GetWorkflowRunRequest{}
	mi := &file_flexiq_v1_workflow_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowRunRequest) ProtoMessage() {}

func (x *GetWorkflowRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_v1_workflow_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowRunRequest.ProtoReflect.Descriptor instead.
func (*GetWorkflowRunRequest) Descriptor() ([]byte, []int) {
	return file_flexiq_v1_workflow_proto_rawDescGZIP(), []int{13}
}

func (x *GetWorkflowRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type GetWorkflowRunResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Run   *WorkflowRun           `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	// Every node the run has, in no particular order.
	Nodes         []*WorkflowNode `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowRunResponse) Reset() {
	*x = GetWorkflowRunResponse{}
	mi := &file_flexiq_v1_workflow_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowRunResponse) ProtoMessage() {}

func (x *GetWorkflowRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flexiq_v1_workflow_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowRunResponse.ProtoReflect.Descriptor instead.
func (*GetWorkflowRunResponse) Descriptor() ([]byte, []int) {
	return file_flexiq_v1_workflow_proto_rawDescGZIP(), []int{14}
}

func (x *GetWorkflowRunResponse) GetRun() *WorkflowRun {
	if x != nil {
		return x.Run
	}
	return nil
}

func (x *GetWorkflowRunResponse) GetNodes() []*WorkflowNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_flexiq_v1_workflow_proto protoreflect.FileDescriptor

const file_flexiq_v1_workflow_proto_rawDesc = "" +
	"\n" +
	"\x18flexiq/v1/workflow.proto\x12\tflexiq.v1\x1a\x13flexiq/v1/job.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb9\x01\n" +
	"\rWorkflowGraph\x122\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1c.flexiq.v1.WorkflowGraphNodeR\x05nodes\x122\n" +
	"\x05edges\x18\x02 \x03(\v2\x1c.flexiq.v1.WorkflowGraphEdgeR\x05edges\x12@\n" +
	"\fnode_configs\x18\x03 \x03(\v2\x1d.flexiq.v1.WorkflowNodeConfigR\vnodeConfigs\"'\n" +
	"\x11WorkflowGraphNode\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"7\n" +
	"\x11WorkflowGraphEdge\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\"\xa1\x01\n" +
	"\n" +
	"GateConfig\x123\n" +
	"\atimeout\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x123\n" +
	"\n" +
	"on_timeout\x18\x02 \x01(\x0e2\x14.flexiq.v1.OnTimeoutR\tonTimeout\x12\x1d\n" +
	"\amessage\x18\x03 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message\":\n" +
	"\vCacheConfig\x12+\n" +
	"\x03ttl\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x03ttl\"A\n" +
	"\fFanOutConfig\x12\"\n" +
	"\n" +
	"items_from\x18\x01 \x01(\tH\x00R\titemsFrom\x88\x01\x01B\r\n" +
	"\v_items_from\"!\n" +
	"\vFanInConfig\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\"\x9f\x01\n" +
	"\x0fSubWorkflowSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12.\n" +
	"\x05graph\x18\x03 \x01(\v2\x18.flexiq.v1.WorkflowGraphR\x05graph\x12.\n" +
	"\x13deferred_node_names\x18\x04 \x03(\tR\x11deferredNodeNames\"\x95\x06\n" +
	"\x12WorkflowNodeConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\ttask_name\x18\x02 \x01(\tR\btaskName\x12\x19\n" +
	"\x05queue\x18\x03 \x01(\tH\x01R\x05queue\x88\x01\x01\x12\x12\n" +
	"\x03raw\x18\x04 \x01(\fH\x00R\x03raw\x12;\n" +
	"\n" +
	"structured\x18\x05 \x01(\v2\x19.flexiq.v1.StructuredArgsH\x00R\n" +
	"structured\x12$\n" +
	"\vmax_retries\x18\x06 \x01(\x05H\x02R\n" +
	"maxRetries\x88\x01\x01\x123\n" +
	"\atimeout\x18\a \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x1f\n" +
	"\bpriority\x18\b \x01(\x05H\x03R\bpriority\x88\x01\x01\x126\n" +
	"\tcondition\x18\t \x01(\x0e2\x18.flexiq.v1.EdgeConditionR\tcondition\x12.\n" +
	"\x04gate\x18\n" +
	" \x01(\v2\x15.flexiq.v1.GateConfigH\x04R\x04gate\x88\x01\x01\x121\n" +
	"\x05cache\x18\v \x01(\v2\x16.flexiq.v1.CacheConfigH\x05R\x05cache\x88\x01\x01\x125\n" +
	"\afan_out\x18\f \x01(\v2\x17.flexiq.v1.FanOutConfigH\x06R\x06fanOut\x88\x01\x01\x122\n" +
	"\x06fan_in\x18\r \x01(\v2\x16.flexiq.v1.FanInConfigH\aR\x05fanIn\x88\x01\x01\x12B\n" +
	"\fsub_workflow\x18\x0e \x01(\v2\x1a.flexiq.v1.SubWorkflowSpecH\bR\vsubWorkflow\x88\x01\x01\x12#\n" +
	"\n" +
	"compensate\x18\x0f \x01(\tH\tR\n" +
	"compensate\x88\x01\x01B\x06\n" +
	"\x04bodyB\b\n" +
	"\x06_queueB\x0e\n" +
	"\f_max_retriesB\v\n" +
	"\t_priorityB\a\n" +
	"\x05_gateB\b\n" +
	"\x06_cacheB\n" +
	"\n" +
	"\b_fan_outB\t\n" +
	"\a_fan_inB\x0f\n" +
	"\r_sub_workflowB\r\n" +
	"\v_compensate\"\xcb\x03\n" +
	"\vWorkflowRun\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rdefinition_id\x18\x02 \x01(\tR\fdefinitionId\x12.\n" +
	"\x05state\x18\x03 \x01(\x0e2\x18.flexiq.v1.WorkflowStateR\x05state\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12\x19\n" +
	"\x05error\x18\x06 \x01(\tH\x00R\x05error\x88\x01\x01\x12'\n" +
	"\rparent_run_id\x18\a \x01(\tH\x01R\vparentRunId\x88\x01\x01\x12-\n" +
	"\x10parent_node_name\x18\b \x01(\tH\x02R\x0eparentNodeName\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\b\n" +
	"\x06_errorB\x10\n" +
	"\x0e_parent_run_idB\x13\n" +
	"\x11_parent_node_name\"\x9f\x02\n" +
	"\fWorkflowNode\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.flexiq.v1.WorkflowNodeStatusR\x06status\x12\x1a\n" +
	"\x06job_id\x18\x03 \x01(\tH\x00R\x05jobId\x88\x01\x01\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12\x19\n" +
	"\x05error\x18\x06 \x01(\tH\x01R\x05error\x88\x01\x01B\t\n" +
	"\a_job_idB\b\n" +
	"\x06_error\"\x91\x01\n" +
	"\x15SubmitWorkflowRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12.\n" +
	"\x05graph\x18\x02 \x01(\v2\x18.flexiq.v1.WorkflowGraphR\x05graph\x12$\n" +
	"\vparams_json\x18\x03 \x01(\tH\x00R\n" +
	"paramsJson\x88\x01\x01B\x0e\n" +
	"\f_params_json\"/\n" +
	"\x16SubmitWorkflowResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\".\n" +
	"\x15GetWorkflowRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"q\n" +
	"\x16GetWorkflowRunResponse\x12(\n" +
	"\x03run\x18\x01 \x01(\v2\x16.flexiq.v1.WorkflowRunR\x03run\x12-\n" +
	"\x05nodes\x18\x02 \x03(\v2\x17.flexiq.v1.WorkflowNodeR\x05nodes*\x88\x01\n" +
	"\rEdgeCondition\x12\x1e\n" +
	"\x1aEDGE_CONDITION_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19EDGE_CONDITION_ON_SUCCESS\x10\x01\x12\x1d\n" +
	"\x19EDGE_CONDITION_ON_FAILURE\x10\x02\x12\x19\n" +
	"\x15EDGE_CONDITION_ALWAYS\x10\x03*V\n" +
	"\tOnTimeout\x12\x1a\n" +
	"\x16ON_TIMEOUT_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ON_TIMEOUT_APPROVE\x10\x01\x12\x15\n" +
	"\x11ON_TIMEOUT_REJECT\x10\x02*\xee\x02\n" +
	"\rWorkflowState\x12\x1e\n" +
	"\x1aWORKFLOW_STATE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16WORKFLOW_STATE_PENDING\x10\x01\x12\x1a\n" +
	"\x16WORKFLOW_STATE_RUNNING\x10\x02\x12\x19\n" +
	"\x15WORKFLOW_STATE_PAUSED\x10\x03\x12\x1c\n" +
	"\x18WORKFLOW_STATE_COMPLETED\x10\x04\x12*\n" +
	"&WORKFLOW_STATE_COMPLETED_WITH_FAILURES\x10\x05\x12\x19\n" +
	"\x15WORKFLOW_STATE_FAILED\x10\x06\x12\x1c\n" +
	"\x18WORKFLOW_STATE_CANCELLED\x10\a\x12\x1f\n" +
	"\x1bWORKFLOW_STATE_COMPENSATING\x10\b\x12\x1e\n" +
	"\x1aWORKFLOW_STATE_COMPENSATED\x10\t\x12&\n" +
	"\"WORKFLOW_STATE_COMPENSATION_FAILED\x10\n" +
	"*\xd1\x03\n" +
	"\x12WorkflowNodeStatus\x12$\n" +
	" WORKFLOW_NODE_STATUS_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cWORKFLOW_NODE_STATUS_PENDING\x10\x01\x12 \n" +
	"\x1cWORKFLOW_NODE_STATUS_RUNNING\x10\x03\x12\"\n" +
	"\x1eWORKFLOW_NODE_STATUS_COMPLETED\x10\x04\x12\x1f\n" +
	"\x1bWORKFLOW_NODE_STATUS_FAILED\x10\x05\x12 \n" +
	"\x1cWORKFLOW_NODE_STATUS_SKIPPED\x10\x06\x12)\n" +
	"%WORKFLOW_NODE_STATUS_WAITING_APPROVAL\x10\a\x12\"\n" +
	"\x1eWORKFLOW_NODE_STATUS_CACHE_HIT\x10\b\x12%\n" +
	"!WORKFLOW_NODE_STATUS_COMPENSATING\x10\t\x12$\n" +
	" WORKFLOW_NODE_STATUS_COMPENSATED\x10\n" +
	"\x12,\n" +
	"(WORKFLOW_NODE_STATUS_COMPENSATION_FAILED\x10\v\"\x04\b\x02\x10\x02*\x1aWORKFLOW_NODE_STATUS_READYB\xa9\x01\n" +
	"\rcom.flexiq.v1B\rWorkflowProtoP\x01ZDgithub.com/ByteVeda/flexiq/sdks/go/v2/internal/pb/flexiq/v1;flexiqv1\xa2\x02\x03FXX\xaa\x02\tFlexiq.V1\xca\x02\tFlexiq\\V1\xe2\x02\x15Flexiq\\V1\\GPBMetadata\xea\x02\n" +
	"Flexiq::V1b\x06proto3"

var (
	file_flexiq_v1_workflow_proto_rawDescOnce sync.Once
	file_flexiq_v1_workflow_proto_rawDescData []byte
)

func file_flexiq_v1_workflow_proto_rawDescGZIP() []byte {
	file_flexiq_v1_workflow_proto_rawDescOnce.Do(func() {
		file_flexiq_v1_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flexiq_v1_workflow_proto_rawDesc), len(file_flexiq_v1_workflow_proto_rawDesc)))
	})
	return file_flexiq_v1_workflow_proto_rawDescData
}

var file_flexiq_v1_workflow_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_flexiq_v1_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_flexiq_v1_workflow_proto_goTypes = []any{
	(EdgeCondition)(0),             // 0: flexiq.v1.EdgeCondition
	(OnTimeout)(0),                 // 1: flexiq.v1.OnTimeout
	(WorkflowState)(0),             // 2: flexiq.v1.WorkflowState
	(WorkflowNodeStatus)(0),        // 3: flexiq.v1.WorkflowNodeStatus
	(*WorkflowGraph)(nil),          // 4: flexiq.v1.WorkflowGraph
	(*WorkflowGraphNode)(nil),      // 5: flexiq.v1.WorkflowGraphNode
	(*WorkflowGraphEdge)(nil),      // 6: flexiq.v1.WorkflowGraphEdge
	(*GateConfig)(nil),             // 7: flexiq.v1.GateConfig
	(*CacheConfig)(nil),            // 8: flexiq.v1.CacheConfig
	(*FanOutConfig)(nil),           // 9: flexiq.v1.FanOutConfig
	(*FanInConfig)(nil),            // 10: flexiq.v1.FanInConfig
	(*SubWorkflowSpec)(nil),        // 11: flexiq.v1.SubWorkflowSpec
	(*WorkflowNodeConfig)(nil),     // 12: flexiq.v1.WorkflowNodeConfig
	(*WorkflowRun)(nil),            // 13: flexiq.v1.WorkflowRun
	(*WorkflowNode)(nil),           // 14: flexiq.v1.WorkflowNode
	(*SubmitWorkflowRequest)(nil),  // 15: flexiq.v1.SubmitWorkflowRequest
	(*SubmitWorkflowResponse)(nil), // 16: flexiq.v1.SubmitWorkflowResponse
	(*GetWorkflowRunRequest)(nil),  // 17: flexiq.v1.GetWorkflowRunRequest
	(*GetWorkflowRunResponse)(nil), // 18: flexiq.v1.GetWorkflowRunResponse
	(*durationpb.Duration)(nil),    // 19: google.protobuf.Duration
	(*StructuredArgs)(nil),         // 20: flexiq.v1.StructuredArgs
	(*timestamppb.Timestamp)(nil),  // 21: google.protobuf.Timestamp
}
var file_flexiq_v1_workflow_proto_depIdxs = []int32{
	5,  // 0: flexiq.v1.WorkflowGraph.nodes:type_name -> flexiq.v1.WorkflowGraphNode
	6,  // 1: flexiq.v1.WorkflowGraph.edges:type_name -> flexiq.v1.WorkflowGraphEdge
	12, // 2: flexiq.v1.WorkflowGraph.node_configs:type_name -> flexiq.v1.WorkflowNodeConfig
	19, // 3: flexiq.v1.GateConfig.timeout:type_name -> google.protobuf.Duration
	1,  // 4: flexiq.v1.GateConfig.on_timeout:type_name -> flexiq.v1.OnTimeout
	19, // 5: flexiq.v1.CacheConfig.ttl:type_name -> google.protobuf.Duration
	4,  // 6: flexiq.v1.SubWorkflowSpec.graph:type_name -> flexiq.v1.WorkflowGraph
	20, // 7: flexiq.v1.WorkflowNodeConfig.structured:type_name -> flexiq.v1.StructuredArgs
	19, // 8: flexiq.v1.WorkflowNodeConfig.timeout:type_name -> google.protobuf.Duration
	0,  // 9: flexiq.v1.WorkflowNodeConfig.condition:type_name -> flexiq.v1.EdgeCondition
	7,  // 10: flexiq.v1.WorkflowNodeConfig.gate:type_name -> flexiq.v1.GateConfig
	8,  // 11: flexiq.v1.WorkflowNodeConfig.cache:type_name -> flexiq.v1.CacheConfig
	9,  // 12: flexiq.v1.WorkflowNodeConfig.fan_out:type_name -> flexiq.v1.FanOutConfig
	10, // 13: flexiq.v1.WorkflowNodeConfig.fan_in:type_name -> flexiq.v1.FanInConfig
	11, // 14: flexiq.v1.WorkflowNodeConfig.sub_workflow:type_name -> flexiq.v1.SubWorkflowSpec
	2,  // 15: flexiq.v1.WorkflowRun.state:type_name -> flexiq.v1.WorkflowState
	21, // 16: flexiq.v1.WorkflowRun.started_at:type_name -> google.protobuf.Timestamp
	21, // 17: flexiq.v1.WorkflowRun.completed_at:type_name -> google.protobuf.Timestamp
	21, // 18: flexiq.v1.WorkflowRun.created_at:type_name -> google.protobuf.Timestamp
	3,  // 19: flexiq.v1.WorkflowNode.status:type_name -> flexiq.v1.WorkflowNodeStatus
	21, // 20: flexiq.v1.WorkflowNode.started_at:type_name -> google.protobuf.Timestamp
	21, // 21: flexiq.v1.WorkflowNode.completed_at:type_name -> google.protobuf.Timestamp
	4,  // 22: flexiq.v1.SubmitWorkflowRequest.graph:type_name -> flexiq.v1.WorkflowGraph
	13, // 23: flexiq.v1.GetWorkflowRunResponse.run:type_name -> flexiq.v1.WorkflowRun
	14, // 24: flexiq.v1.GetWorkflowRunResponse.nodes:type_name -> flexiq.v1.WorkflowNode
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_flexiq_v1_workflow_proto_init() }
func file_flexiq_v1_workflow_proto_init() {
	if File_flexiq_v1_workflow_proto != nil {
		return
	}
	file_flexiq_v1_job_proto_init()
	file_flexiq_v1_workflow_proto_msgTypes[3].OneofWrappers = []any{}
	file_flexiq_v1_workflow_proto_msgTypes[5].OneofWrappers = []any{}
	file_flexiq_v1_workflow_proto_msgTypes[8].OneofWrappers = []any{
		(*WorkflowNodeConfig_Raw)(nil),
		(*WorkflowNodeConfig_Structured)(nil),
	}
	file_flexiq_v1_workflow_proto_msgTypes[9].OneofWrappers = []any{}
	file_flexiq_v1_workflow_proto_msgTypes[10].OneofWrappers = []any{}
	file_flexiq_v1_workflow_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flexiq_v1_workflow_proto_rawDesc), len(file_flexiq_v1_workflow_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_flexiq_v1_workflow_proto_goTypes,
		DependencyIndexes: file_flexiq_v1_workflow_proto_depIdxs,
		EnumInfos:         file_flexiq_v1_workflow_proto_enumTypes,
		MessageInfos:      file_flexiq_v1_workflow_proto_msgTypes,
	}.Build()
	File_flexiq_v1_workflow_proto = out.File
	file_flexiq_v1_workflow_proto_goTypes = nil
	file_flexiq_v1_workflow_proto_depIdxs = nil
}
