//! SPA delivery: the bundle embedded at build time, or a directory named by
//! `FLEXIQ_DASHBOARD_ASSETS`.
//!
//! Serving the SPA here is the point of the server crate — the SDK packages
//! each ship their own 1.6 MB copy today. A build with no bundle serves the
//! same "assets not bundled" page the SDK dashboards serve, rather than 404s
//! that look like a routing bug.

use std::borrow::Cow;
use std::path::{Path, PathBuf};

// Generated by build.rs: `EMBEDDED_ASSETS: &[(&str, &[u8])]`, empty when no
// SPA build was present at compile time.
include!(concat!(env!("OUT_DIR"), "/dashboard_assets.rs"));

/// Request-path prefix for content-hashed files, which may be cached forever.
pub const IMMUTABLE_PREFIX: &str = "/assets/";

/// Page shown when the binary carries no SPA bundle.
pub const MISSING_ASSETS_HTML: &str = concat!(
    "<!doctype html><html><head><meta charset='utf-8'>",
    "<title>Taskito — dashboard assets missing</title></head>",
    "<body style='font-family:system-ui;padding:2rem;max-width:640px'>",
    "<h1>Dashboard assets not bundled</h1>",
    "<p>This taskito-server build does not embed the compiled dashboard. ",
    "Build the SPA and point the server at it:</p>",
    "<pre>pnpm --dir dashboard install &amp;&amp; pnpm --dir dashboard build\n",
    "FLEXIQ_DASHBOARD_ASSETS=/path/to/dist taskito-server</pre>",
    "</body></html>"
);

const CONTENT_TYPES: &[(&str, &str)] = &[
    ("html", "text/html; charset=utf-8"),
    ("js", "application/javascript; charset=utf-8"),
    ("mjs", "application/javascript; charset=utf-8"),
    ("css", "text/css; charset=utf-8"),
    ("json", "application/json; charset=utf-8"),
    ("map", "application/json; charset=utf-8"),
    ("svg", "image/svg+xml"),
    ("png", "image/png"),
    ("ico", "image/x-icon"),
    ("webmanifest", "application/manifest+json"),
    ("woff2", "font/woff2"),
    ("woff", "font/woff"),
    ("ttf", "font/ttf"),
    ("txt", "text/plain; charset=utf-8"),
];

/// Content-Type for a request path, by extension.
pub fn content_type_for(path: &str) -> &'static str {
    let extension = path.rsplit('.').next().unwrap_or("").to_ascii_lowercase();
    CONTENT_TYPES
        .iter()
        .find(|(suffix, _)| *suffix == extension)
        .map(|(_, mime)| *mime)
        .unwrap_or("application/octet-stream")
}

/// Where the SPA is read from.
enum Source {
    /// Files compiled into the binary.
    Embedded,
    /// A directory on disk, for a custom or externally-mounted bundle.
    Directory(PathBuf),
}

/// An immutable handle to the SPA bundle.
pub struct StaticAssets {
    source: Source,
}

impl StaticAssets {
    /// Read from `directory` when given, otherwise from the embedded bundle.
    pub fn new(directory: Option<PathBuf>) -> Self {
        Self {
            source: match directory {
                Some(path) => Source::Directory(path),
                None => Source::Embedded,
            },
        }
    }

    /// Whether an `index.html` is reachable — i.e. whether a bundle exists.
    pub fn available(&self) -> bool {
        self.read("index.html").is_some()
    }

    /// The SPA entry point, served for every client-routed path.
    pub fn index(&self) -> Option<Cow<'static, [u8]>> {
        self.read("index.html")
    }

    /// Resolve a request path to file bytes, or `None` when it names no file.
    pub fn resolve(&self, request_path: &str) -> Option<Cow<'static, [u8]>> {
        let relative = sanitize(request_path)?;
        self.read(&relative)
    }

    fn read(&self, relative: &str) -> Option<Cow<'static, [u8]>> {
        match &self.source {
            Source::Embedded => EMBEDDED_ASSETS
                .iter()
                .find(|(name, _)| *name == relative)
                .map(|(_, bytes)| Cow::Borrowed(*bytes)),
            Source::Directory(root) => {
                let path = root.join(relative);
                // `sanitize` already rejected traversal, so a path that leaves
                // the root can only come from a symlink inside the bundle.
                if !path.starts_with(root) || !path.is_file() {
                    return None;
                }
                std::fs::read(path).ok().map(Cow::Owned)
            }
        }
    }
}

/// Turn a request path into a safe relative path, or `None` if it is not one.
///
/// Rejects traversal, absolute segments, null bytes, and backslash escapes —
/// the last matters because a Windows host would otherwise treat `..\` as a
/// directory separator the `..` check never sees.
fn sanitize(request_path: &str) -> Option<String> {
    let trimmed = request_path.trim_start_matches('/');
    if trimmed.is_empty() || trimmed.contains('\0') || trimmed.contains('\\') {
        return None;
    }
    let mut parts = Vec::new();
    for part in trimmed.split('/') {
        if part.is_empty() || part == "." || part == ".." {
            return None;
        }
        if Path::new(part).components().count() != 1 {
            return None;
        }
        parts.push(part);
    }
    Some(parts.join("/"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn traversal_attempts_are_rejected() {
        for path in [
            "/../etc/passwd",
            "/assets/../../secret",
            "/assets/..\\windows",
            "/",
            "//",
            "/a\0b",
        ] {
            assert!(sanitize(path).is_none(), "must reject {path}");
        }
    }

    #[test]
    fn ordinary_paths_are_normalised() {
        assert_eq!(sanitize("/index.html").as_deref(), Some("index.html"));
        assert_eq!(
            sanitize("/assets/app-1a2b.js").as_deref(),
            Some("assets/app-1a2b.js")
        );
    }

    #[test]
    fn content_types_cover_the_bundle_and_fall_back() {
        assert_eq!(content_type_for("/index.html"), "text/html; charset=utf-8");
        assert_eq!(
            content_type_for("/assets/app.JS"),
            "application/javascript; charset=utf-8"
        );
        assert_eq!(content_type_for("/unknown.bin"), "application/octet-stream");
    }

    #[test]
    fn a_directory_source_serves_files_and_rejects_escapes() {
        let dir = std::env::temp_dir().join(format!("taskito-assets-{}", std::process::id()));
        std::fs::create_dir_all(&dir).expect("create temp dir");
        std::fs::write(dir.join("index.html"), b"<h1>ok</h1>").expect("write index");

        let assets = StaticAssets::new(Some(dir.clone()));
        assert!(assets.available());
        assert_eq!(
            assets.resolve("/index.html").as_deref(),
            Some(&b"<h1>ok</h1>"[..])
        );
        assert!(assets.resolve("/../index.html").is_none());
        assert!(assets.resolve("/missing.js").is_none());

        std::fs::remove_dir_all(&dir).expect("clean up");
    }
}
